### ISSUE TITLE
Pathfinding mobs (BB #1007)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1007]
This issue was migrated from bitbucket.
**Original Reporter:** bewtihozzy
**Original Date:** 13.06.2015 15:32:51 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1007

<hr>

Some mobs wont attack you/stay with you (pets) thru the water as you can see on [this pictures ](http://imgur.com/a/q4JBs)

Same happens with some humanoids & crabs i think xD

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 20.06.2015 16:26:53 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1007/#comment-19172443

<hr>

I think some creatures can't swim. Some can. Like wolves in duskwood for example cannot. Pets should work though.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Zaffy
**Original Date:** 17.07.2015 14:01:15 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1007/#comment-20289689

<hr>

Pets will follow you. Some creatures can't swim and its ok. They should evade after a few seconds though. IMO crabs should be able to swim and also if there's not much water like you don't have to swim but just walk they should follow you but this is not implemented i think

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 17.07.2015 16:53:16 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1007/#comment-20293691

<hr>

are you sure pets? cause in picture it shows pets not

**Comment by LordUsagi** [comment]
InhabitTypes for all creatures has been resolved.
