### ISSUE TITLE
[Duel bug] Voidwalker doesnt stop attacking after duel end (BB #1098)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1098]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 14.08.2015 19:49:40 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098

<hr>

rev: c07fe354bafbd8c689bf67de1106c8c31ca1ef93

Problem: After a Duel the Voidwalker ( might be other pets as well ) dont stop attacking the other player.. 

How it should be: After player wins duel his voidwalker must stop attacking the other player.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 14.08.2015 22:22:31 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-20932931

<hr>

i have also confirmation that other npc with pets like voidwalker have the same problem, when you get attacked, and kill the npc that has a voidwalker the voidwalker keeps on attacking you until you run towards an guard that kills it for you..

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 15.08.2015 02:52:39 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-20934971

<hr>

I took a look at this. It's not when you kill an NPC but rather when an NPC evades. On death an NPC should despawn his pet (tested and confirmed working).

I also took the liberty of backing out a recent change to PetAI that might have influenced this bug but no avail, the bug exists before commit 483f017e1867c8dc3bf167cf3b5f917c58879e41 and is not caused by it.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** mathman
**Original Date:** 29.08.2015 14:10:53 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-21330587

<hr>

Can you test with last rev

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 31.08.2015 00:43:01 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-21356999

<hr>

Not resolved yet.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** mathman
**Original Date:** 31.08.2015 17:44:26 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-21377878

<hr>

Can you give me an example of npc's pet

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 31.08.2015 17:48:04 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1098/#comment-21377950

<hr>

Murloc Hunters, in relation to the other issue have pets. Also can see Burning Blade Apprentice (ID: 3198) who has a Voidwalker pet.

**Comment by LordUsagi** [comment]
Resolved in 3b87c0f93af488156f655fb8c0f89894d77d2c62
