### ISSUE TITLE
[crash] Defias Blackguard (BB #1099)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1099]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 14.08.2015 22:36:03 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099

<hr>

rev: c07fe354bafbd8c689bf67de1106c8c31ca1ef93

Problem: when Defias Blackguard removes his stealth in DM and makes the emote on agro the server crashes.

how to reproduce: go to DM and agro the npc.

crashdump: http://pastebin.com/MHtdxSgM

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 15.08.2015 02:26:37 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-20934885

<hr>

I can't reproduce this one. Need feedback from other devs.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 15.08.2015 06:49:59 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-20935936

<hr>

its not only that npc, its random.. but we where able to catch from the crashlog that it was this npc.. although there was a raid group in DM so we suspect that it was due this npc, but who knows.
server crashed 3 times or 4 times in a row as soon as it was up and people joined we got same crash.. until it stopped.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** HEGladios
**Original Date:** 15.08.2015 17:53:11 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-20941131

<hr>

Creature AI scripts id 63602 causes the crash. When trying to remove the aura from itself, it was already removed for some reason. (maybe dispelled? Or didn't cast the spell to begin with?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 04.12.2015 12:11:33 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-23805594

<hr>

Does the crash still occur? since I can't reproduce it.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 04.12.2015 12:26:24 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-23805942

<hr>

as far as i know this is a random crash and hard to reproduce, but it is due removed aura's form creatures that are scripted with eventai when it is already removed ( due for whatever reason )
what happens is that eventai tries to remove an aura from a npc that doesnt have the aura anymore ( might be due various reasons as @gladios mentioned )
the code then goes fucky fucky and crash the core :p at least thats how gladios and me are thinking it goes.
So reproducing is hard to do, since its luck of the draw that this happens

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 04.12.2015 12:33:44 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-23806151

<hr>

I see. I have fully scripted Deadmines on my Core, but I have scripted this npc by custom script, rather than DB and no matter how many times I try I can't get a crash. Maybe try custom scripting him, so it would solve the problem?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 04.12.2015 12:36:21 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1099/#comment-23806216

<hr>

i just tried to reproduce this with the same npc, but now it doesnt crash, but it has to be something wider, its not as i mentioned npc specific.
its when the core wants to remove an aura from a npc that doesnt have that aura anymore due whatever reason, then it crashes with above crashlog.
we assumed since in the crashlog it mentioned that script/npc that it was only that npcs, but gladios took a better look on how it crashes and it could be litterly ANY npc that has this..
and yes get rid of eventai will solve this, since its in the code of eventai remove aura where this problem occurs.

**Comment by AbraKabastard** [comment]
No longer reproducable.
