### ISSUE TITLE
[Spell] Stealth/Prowl (BB #1115)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1115]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 20.08.2015 20:35:33 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1115

<hr>

![e78997b6-4366-11e5-9640-1b1cb9928025.jpg](https://bitbucket.org/repo/kMeMB/images/3140775891-e78997b6-4366-11e5-9640-1b1cb9928025.jpg)problem: It Seems like Npcs (even grey ones) can see me while I'm prowling/stealthed if I'm walking in front of them. maybe it's 'work as intended' but npcs with 6 level below me shouldn't be able to see me like if I was unstealthed. 
After testing I can't even stay stealthed more than 1 second BEHIND them.

**Comment by LordUsagi** [comment]
This is fixed with the most recent stealth changes.
