### ISSUE TITLE
[Spell] Shield Bash (BB #1116)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1116]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 20.08.2015 20:36:54 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** invalid
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1116

<hr>

Shield bash should prevent casting of magic school which was interupted, but its not working.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** adeutscher
**Original Date:** 21.08.2015 22:42:37 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1116/#comment-21093383

<hr>

Which spells and ranks were you testing this with?

I was not able to reproduce that with Rank 4 Shield Bash on a either a Paladin target casting Holy Light or a Mage target casting Blizzard (to confirm that only Frost would be locked out).

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 25.08.2015 01:41:35 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1116/#comment-21213095

<hr>

Tested on priest casting Mind Control also. Confirmed works.

**Comment by dikkedeur** [comment]
bumping this.

Sorry for bringing this up, but shieldbashing (http://http://db.hellground.net/?spell=72) a Murloc Oracle (http://http://db.hellground.net/?npc=517 casting Holy Smite (http://http://db.hellground.net/?spell=9734) does NOT prevent it to cast another Holy Smite right away. Same goes for alot of NPCs.

Same with Earth Shock http://db.hellground.net/?spell=25454
It interrupts the cast but doesn't lock out the appropriate magic school.
In fact a lot of different mobs are able to cast the same previously interrupted spell immediately again.

I could imagine same behavior can be observed with other interrupt spells like Counterspell, Kick or Pummel.

**Comment by dikkedeur** [comment]
Side note: This is most likely to do with creature AI. Some creatures seem to be able to ignore spell school lockouts.
