### ISSUE TITLE
[quest[ To legion hold (BB #1126)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1126]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 30.08.2015 18:59:14 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** on hold
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1126

<hr>

problem: when you accept quest and go to legion hold and you use the item, the event doesn't start.

how it should work: accept quest, go to legion hold, use the item to disguise.. after that 2 demons do some talking.
when thats done you should have quest completed..

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 07.09.2015 01:37:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1126/#comment-21571982

<hr>

On hold, we've got code for this with the introduction of SmartAI.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 07.09.2015 01:38:14 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1126/#comment-21571984

<hr>

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 07.09.2015 06:04:46 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1126/#comment-21575093

<hr>

great :P

**Comment by Selphius** [comment]
Fixed in commit: https://github.com/OregonCore/OregonCore/commit/a033d639223d21a2605f9f322d82abcbd639de27#diff-939af6d173267033b4888b19464c4156
