### ISSUE TITLE
[NPC] some are swimming instead of walking (BB #1143)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1143]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 15.10.2015 09:28:48 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** resolved
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143

<hr>

I dont know since when, it might be due the new vmaps/mmaps change but again im not sure.
Some mobs are swimming instead of moving.

a good example would be..

go to ghostland to the southeast to Zeb'nowa.

![Schermafbeelding 2015-10-15 om 11.26.59.png](https://bitbucket.org/repo/kMeMB/images/2446165101-Schermafbeelding%202015-10-15%20om%2011.26.59.png)

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 15.10.2015 09:38:23 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22515360

<hr>

Confirmed. The same issue can be seen in Terokkar Forest -> Firewing Point.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 15.10.2015 09:39:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22515413

<hr>

and around the dead scar... and i think many other places.

i tried with the old vmaps and mmaps, but same, so it has to be something else..

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 18.10.2015 11:29:01 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22580831

<hr>

ehhhh what??? might explain?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** oregon
**Original Date:** 18.10.2015 16:15:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22583889

<hr>

no idea :)

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 19.10.2015 00:02:42 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22588593

<hr>

Are you using the latest vmaps and mmaps?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 20.10.2015 22:26:17 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22647268

<hr>

Yes, I use latest vmaps and mmaps, the same problem was on old ones too, found next location where npc's do swim in the air: Bloodmaul Camp in BEM.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 21.10.2015 06:22:06 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22666852

<hr>

Lord i use the one that where posted by zaffy on the forum, so yes, i also tried it with the older one, and then we have same result.
the picture that i took was at a spot where you can see the npcs walk.. a few steps, then swim, then walk again... but it is always on the same spot where they are walking and or swimming so it has nothing to do with the npc itself.
but it has i think to do with that the core thinks that at that point there is water...

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** PadreWoW
**Original Date:** 21.10.2015 13:01:42 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22677615

<hr>

Confirm

Trouble is with water points!

`InhabitType` = '1' is NOT a fix!

NPCs with waypoints start lagging and can not walk through the water if `InhabitType` = '1'!

See screenshot (quest Escape from Umbrafen - npc Kayra Longmane)

![WoWScrnShot_102115_155750.jpg](https://bitbucket.org/repo/kMeMB/images/1414117473-WoWScrnShot_102115_155750.jpg)

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** mathman
**Original Date:** 21.10.2015 21:41:51 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22692419

<hr>

Movement flags are set dynamically atm you can check to disable updatemovementflag in creature class and enable movement flags from db (creature_addon i think)

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** PadreWoW
**Original Date:** 21.10.2015 23:17:47 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-22693817

<hr>

This is not fix

There was no such problem on old commits

You can not use flags_extra = 524288 for all mobs - some of them SHOULD swim and walk but there is a problem with InhabitType = '3' - you can see this problem on screenshots

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 18.11.2015 10:19:25 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23399175

<hr>

so the only fix would be in this case go trough all the mobs that are swimming ON land and use flags_extra = 524288  ???

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 05.12.2015 13:10:03 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23826043

<hr>

okay on a temp. fix until this is truly fixed, the use of flags_extra= 524288 will indeed make the creature walk and not float/swim.

so this is hacky temp. fix..

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 05.12.2015 13:43:38 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23826373

<hr>

You can also change InhabitType from 3 to 1. Though use it only for creatures which are NOT near water, I prefer it that way. For example in Dun Morogh Leper Gnome does swim in air but there is no water where they are. So it doesn't matter what InhabitType they have or flag.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 05.12.2015 22:16:56 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23831800

<hr>

i have truly no idea how many more mobs are affected by this "bug" so that means going trough the whole world and find them :(

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 06.12.2015 08:25:29 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23835732

<hr>

@Dikke deur 
We can make list on the forum, with creatures/zones affected by it.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Dikkedeur
**Original Date:** 06.12.2015 10:10:12 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-23836513

<hr>

fine by me, and i can even make the sql if you want to update the correct creature so that they are fixed..

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 14.12.2015 01:02:11 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1143/#comment-24020858

<hr>

Resolved!

**Comment by PadreWoW** [comment]
Not resolved
