### ISSUE TITLE
Fires Over Skettis (11008) (BB #1157)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1157]
This issue was migrated from bitbucket.
**Original Reporter:** AlphafoxBHN
**Original Date:** 28.11.2015 21:15:21 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** resolved
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1157

<hr>

Visuals working but if you drop the bombs on the eggs they don'T count for the quest
wowhead.com/quest=11008/feuer-uber-skettis

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** AlphafoxBHN
**Original Date:** 28.11.2015 21:18:41 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1157/#comment-23651309

<hr>

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 09.12.2015 22:33:36 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1157/#comment-23934625

<hr>

Fix Issue #1157, Fires Over Skettis

→ <<cset cdf1d606aa33>>

**Comment by ghost** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3402

This fix works please put it in :D
