### ISSUE TITLE
Boss Mobs HP Problem (BB #1169)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1169]
This issue was migrated from bitbucket.
**Original Reporter:** lyrl
**Original Date:** 08.12.2015 15:13:30 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** resolved
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169

<hr>

Boss Mobs HP Problem 

![1.jpg](https://bitbucket.org/repo/kMeMB/images/2095726214-1.jpg)

![2.jpg](https://bitbucket.org/repo/kMeMB/images/3545867519-2.jpg)

i think that return a percentage not a actual number .
look at second picture , obvious  i am not select [Display Percentage]

how to fix it.... 

core reversion 3089

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** lyrl
**Original Date:** 08.12.2015 15:14:15 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23892841

<hr>

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 08.12.2015 15:14:47 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23892855

<hr>

If I am not mistaken it only occurs, when you're using .gm on. Didn't see it on normal account.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** lyrl
**Original Date:** 08.12.2015 15:15:42 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23892888

<hr>

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** lyrl
**Original Date:** 08.12.2015 15:17:01 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23892926

<hr>

@Selphius real? i will confirm it.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Selphius
**Original Date:** 08.12.2015 15:18:10 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23892964

<hr>

It doesn't matter if you change there, since you've percentages set up in your server config. 
"oregoncore.conf" you can change it here, between % and total.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** lyrl
**Original Date:** 08.12.2015 15:30:28 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23893328

<hr>

@Selphius thank you , resolve it .

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** lyrl
**Original Date:** 08.12.2015 15:30:41 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1169/#comment-23893338

<hr>

thanks

**Comment by ghost** [comment]
@LordUsagi This should be re-opened or the option removed/defaulted to 0. The issue occurs with GM off as well if you have healthinpercent in the config file set to 1. The issue is present on all creatures. Additionally, it does not force the percent when players are in an instance. Trash and bosses will display their full health values.

Everything functions fine if you set it 0.
