### ISSUE TITLE
Voidwalker's Consume shadows (BB #1171)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1171]
This issue was migrated from bitbucket.
**Original Reporter:** Dikkedeur
**Original Date:** 11.12.2015 21:56:22 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1171

<hr>

Voidwalker's channeled ability, Consume Shadows, that is supposed to heal it, does not work.
The demon starts channeling, but it gets interrupted immediately. The mana is lost, no HP is gained.

**Comment by LordUsagi** [comment]
This issue is tricky because sometimes I test it and it works 100% and then others it is broken 100%. And it mostly seems to have to do with the initial summon.

**Comment by Goatform** [comment]
I'll look into this tomorrow.

**Comment by dikkedeur** [comment]
thanks goatform, now hope that it gets pushed.
