### ISSUE TITLE
[Spells] Consecration (BB #1199)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1199]
This issue was migrated from bitbucket.
**Original Reporter:** Baynar
**Original Date:** 01.01.2016 11:48:32 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1199

<hr>

Rev = 3183

When Consecration is casted everything seems normal but when the spell expired etc 8 seconds it automatically recasts itself on the same spot but it doesn't do damage to players

The bug only appear on the Caster etc Paladin that casted it he only sees the bug

The enemies or players around him do not see it.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Baynar
**Original Date:** 01.01.2016 17:56:55 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1199/#comment-24419123

<hr>

Video Report of the bug:
http://www.4shared.com/video/KJkQ_ax2ba/Paladin_bug.html

Consecration animation recasts itself
Normaly in retail i think 1 conceration has to override the previous one and here if you cast 2 you have to wait the first one to dissapear and then you have to cast your second consecration
Video Report:
http://www.4shared.com/video/M0ESQLhbba/Consecration_Bug.html

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 02.01.2016 14:09:47 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1199/#comment-24424763

<hr>

Confirmed, you can see the visual "poof" of the consecration aura every 8 or so seconds. If you move it'll stop.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** Baynar
**Original Date:** 02.01.2016 14:59:16 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1199/#comment-24425199

<hr>

Ok tested it again and yes if you stay still it does the visual effect over and over. hopefully it's fixed in future updates

**Comment by lyrl** [comment]
confirmed
