### ISSUE TITLE
[Core/Formations] Formations in instances don't begin until creature resets (BB #1205)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#1205]
This issue was migrated from bitbucket.
**Original Reporter:** LordUsagi
**Original Date:** 04.01.2016 14:46:56 GMT+0000
**Original Priority:** minor
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/1205

<hr>

Example Leader GUID: 12467

Her two adds don't follow her, this could b e due to her waypoint not even starting until she resets which is another, and may be the entire, issue.

**Comment by ghost** [comment]
I don't have OregonDB installed atm but I believe I had this issue in the past with a caster in Blood Furnace. Does she have combat movement disabled in SAI?

**Comment by LordUsagi** [comment]
Just letting everyone know after testing the merge, that this issue is still existent and is not solved by the above PR.

**Comment by AbraKabastard** [comment]
@Saben65 Yes, but in EventAI. Nice catch!
