### ISSUE TITLE
Hellfire Wall Miss Creature!

### ISSUE THREAD

**Issue by lyrl** [OregonCore/OregonCore#1215]
**_Hellfire Wall Miss Creature!**_
I Used `OregonDB_for_OregonCore_2943.zip` As Base Database.And Apply Updates To `3204_misc_db_updates.sql`.
But I Found Creature Miss In Many Dungeons, Like Hellfire wall,Zul'Aman....
Why...

**Comment by LordUsagi** [comment]
Each missing NPC pack needs its own seperate issue, along with 2.4.3 proof
of their existence, IDs, pack behaviour.

Thanks!
