### ISSUE TITLE
Vmaps Generate Error

### ISSUE THREAD

**Issue by lyrl** [OregonCore/OregonCore#1217]
when i execute `vmap_assembler Buildings vmaps`

return bellow 

> **\* Error in `vmap_assembler': double free or corruption (!prev): 0x00000000078528e0 ***
> Aborted

**Comment by Applepi** [comment]
This has not been resolved. 
Creating map tree for map 598...
cmpfail, ▒V1▒!=GRP
**\* Error in `./vmap_assembler': double free or corruption (!prev): 0x0000000005a5cc70 ***
Aborted

**Comment by LordUsagi** [comment]
Which OS are you using? Do you have the vmaps folder set up correctly? Did you extract the DBC and map data first? Are you using GitHubs version of OregonCore? (_Some people may be using BitBucket_)

**Comment by Applepi** [comment]
I'm on Debian Jessie I'm using the github repo and I have extracted maps and DBC first.

**Comment by LordUsagi** [comment]
Sounds great. I'll assume you compiled the tools yourself too. I'll compile them shortly and give em a whirl but I'm running on windows. I'll let you know how it goes.

**Comment by Applepi** [comment]
Yes the tools were compiled with the core.

**Comment by LordUsagi** [comment]
In the meantime, we've got vmaps up on the forums you could probably use. I'm sure they're vmaps4 too, but I can't say for certain.

**Comment by Applepi** [comment]
I'll check it out

**Comment by Zaffy** [comment]
@Applepi are you sure its not fixed? Just compile in debug then and use gdb or valgrind and give me the backtrace.

**Comment by AbraKabastard** [comment]
Compiling and running okay for me. This issue is quite old and can be opened anew if the issue occurs for someone else.
