### ISSUE TITLE
Opening Doors

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1221]
Earlier today when I was testing some dungeons I noticed I couldn't open the doors to the Arcatraz or Karazhan even though I had the correct keys.

**Comment by zhy9934** [comment]
i can open the door to the Karazhan.  the Arcatraz not test

**Comment by LordUsagi** [comment]
Which revision are you on? I'm on bdb985b7368a and it's not working at all, even on freshly created characters.

**Comment by zhy9934** [comment]
my revision is also bdb985b ,I test it again. I can open the doors to the Arcatraz or Karazhan though the correct keys

**Comment by LordUsagi** [comment]
Yeah, confirmed. I had the wrong DB in use. Cheers for the reply!
