### ISSUE TITLE
[crash] magtheridon crash error

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1229]
when i test the magtheridon , it occur this crash error

2016-01-17 12:09:35 DoZoneInCombat called for creature that has empty threat list (creature entry = 17257)

**Comment by LordUsagi** [comment]
Can you provide a crash dumb from a Debug mode core?

**Comment by zhy9934** [comment]
sorry . I test it again. this error doesn't occur.......
I continue to test it ..
