### ISSUE TITLE
Improved Shadow Bolt initial proccing spell counts one charge

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1231]
Rev: 70dbe99cf990
The warlock talent Improved Shadow Bolt is procced off the spell that procs it. If you cast Shadow Vulnerability manually, it counts 4 stacks and procCharges = 4. It seems that as the first spell is hitting and triggering the proc, it is also removing the first stack.

**Comment by Zaffy** [comment]
Duplicate of #431
