### ISSUE TITLE
[Core] Build Fix

### ISSUE THREAD

**Issue by MeliodasLIVE** [OregonCore/OregonCore#1234]
Rev. 8af2c7d51c1459848951a04c002e1002e406e494

---

npc_taxi needs to be removed from ScriptLoader.cpp
btw should I use this source or from bitbucket for stable version?

**Comment by dikkedeur** [comment]
use bitbucket for now, there stands DO NOT USE YET

**Comment by LordUsagi** [comment]
You can use this one for sure, but as @dikkedeur mentioned we don't have full support for this branch yet.

**Comment by MeliodasLIVE** [comment]
Alright Sir :+1:
