### ISSUE TITLE
Slow database setup

### ISSUE THREAD

**Issue by kotishe** [OregonCore/OregonCore#1235]
Dear @Zaffy,  maybe I'm wrong, but the use of the individual query inserted into the base of a very very slow. I think one is better to rewrite the query to the data set as it was before. Thank you for attention.

PS: db from here https://github.com/OregonCore/OregonCore/releases/tag/BaseDatabase

**Comment by Zaffy** [comment]
I guess. The reason i turned for this is to eliminate the requirement to configure the max allowed packet setting. I personally didnt notice this much on my ssd disk but for exqmple on travis he loading is slow too. Maybe prepared statements could aolve this

**Comment by kotishe** [comment]
No, no, just tune database export  setting in source db like:
`
INSERT INTO gossip_menu_option VALUES
(0, 0,0,'GOSSIP_OPTION_QUESTGIVER',2,2,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0),
(0, 1,1,'I want to browse your goods',3,128,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0),
(0, 2,2,'I want to travel fast',4,8192,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0),
(0, 3,3,'Train me!',5,16,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0), ...
`
instead
`
INSERT INTO gossip_menu_option VALUES
(0, 0,0,'GOSSIP_OPTION_QUESTGIVER',2,2,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0);
INSERT INTO gossip_menu_option VALUES
(0, 1,1,'I want to browse your goods',3,128,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0);
`
only in this case it makes sense max allowed packet

**Comment by kotishe** [comment]
old database setup run 2 min vs 2 hr in new version

**Comment by Zaffy** [comment]
I know thats what I said. Some tables are really big and users need to change max_allowed_packet in order to populate them - i wanted to avoid that but probably the performance cost is much larger.

I have re-exported so now it should be very compact and fast.

**Comment by kotishe** [comment]
max_allowed_packet is not a question of speed in my case, just the old version is better and faster than the new one.

Add the note in https://github.com/OregonCore/OregonCore/blob/master/sql/README.md

**Comment by kotishe** [comment]
as say dev.mysql.org 

> The server's default max_allowed_packet value is 1MB. 

setup in max INSERT size default value is compromise between speed and compatibility
