### ISSUE TITLE
How OregonCore deals with AntiCheat(such as WowEmuHacker)

### ISSUE THREAD

**Issue by jdk8** [OregonCore/OregonCore#1238]
Pleased see this project develops so well. But I wonder how it deals with AntiCheat except the Warden.
As far as I know, the warden can't work 100% precisely.

Cheats are like speed hack, teleport hack and fly hack.

Thanks.

**Comment by LordUsagi** [comment]
This would be a custom system and we currently aren't looking to support it.

As far as I know there's plenty of publicly available custom anticheat patches that you could implement on your server if you would like.
