### ISSUE TITLE
[Crash] CharmInfo::IsReturning 

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1240]
http://pastebin.com/fHYGq7zY

**Comment by dikkedeur** [comment]
note: it was causing by a hunter orc that was doing the tame pet quest, and got the boar tamed and attacked more then 1 mob with that pet, thats at least how we where able to reproduce.

**Comment by LordUsagi** [comment]
How exactly are you reproducing it?

I've got a hunter, with the tame beast quest. I use the taming rod on the boar. The boar then engages in combat with two creatures. I kill one creature after some fighting. I wait. I kill the other creature. Nothing happens?

Help!

**Comment by dikkedeur** [comment]
its hard to reproduce in some way, although we had 3 crashes in a row with it, but we think... that with the hellboar that the hunter had he was engaging 3 mobs at a time, at some sort i think the hellboar pet died or one of the 3 mobs he engaged died.. we are still not sure how it works, but it happens, he was still on the questchain.. a way to fix this is to ditch the pet, and take a new pet, so it might be related to the pet itself that you get on taming pet questchain, he was still using that one.

**Comment by LordUsagi** [comment]
Perhaps. I noticed some weird issues with "Follow" commands, the pet would never follow me until I clicked "Follow" repeatedly after tame and fight.

**Comment by dikkedeur** [comment]
indeed that was also something that somebody told me, i have no experience with hunters myself that much so i cant tell.

**Comment by LordUsagi** [comment]
I'm hoping its not related to all hunter pets but just these "temporary" pets.

**Comment by dikkedeur** [comment]
as far as i know only temp. once

**Comment by HEGladios** [comment]
Looks like the CharmInfo object is missing or deleted with these temporary pets?

**Comment by LordUsagi** [comment]
Perhaps they're not inheriting the pet class properly
