### ISSUE TITLE
[Crash]ObjectMgr::DeleteRespawnTimeForInstance

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1242]
http://pastebin.com/3uDPAzc9

**Comment by LordUsagi** [comment]
Let me know if it happens again after the update.

**Comment by dikkedeur** [comment]
i didnt got this crash now anymore.. but you never know, for now i close this issue, if it happens again i can always reopen it :+1:

**Comment by LordUsagi** [comment]
Sounds good!
