### ISSUE TITLE
Problem with visibility

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1243]
When you delete a creature, it does not dissapear until you move.

May be related to #1199

**Comment by Baynat** [comment]
While working on my server i saw that this is not only to the spells its also on creatures / game objects and i think that the problems is in map update.. cause the map is updated every time you move or cast something but not when you are standing still

**Comment by Baynar** [comment]
This is not only with spell and creature.... ++gameobjects anything that is visable ingame will not be deleted from your screen unless you move

**Comment by LordUsagi** [comment]
Thanks, this is recent right?

**Comment by PadreWoW** [comment]
This problem was previously on old core

https://bitbucket.org/oregon/oregoncore/issues/748/deleted-mobs-and-objects-dont-disappear

**Comment by Zaffy** [comment]
I think this is highly related to #1199 and #748 and is very annoying.

**Comment by LordUsagi** [comment]
Well #748 was resolved a long time ago. It is potentially related to #1199.

**Comment by Desteny** [comment]
this problem was already there on realy old versions of OC and even on TC2 for some time.
if you are sitting on top of the bank @ OG looking at the city door you soon see player runnung out of sight but for you it looks like they are moving in place (running but not forward) if you moved all disapears.

this was not happen in a consistent way but often, same if a player logout, you see him there until you move even if he logged out a hour ago.

you may need to digg deeper to find the issue, i think there is a missing paket need to be send to the client

**Comment by LordUsagi** [comment]
I think we solved the issue @desteny is mentioning. This ones quite strange. And I can't seem to figure it out.

**Comment by Agyla** [comment]
Is there anything I can do to help with this? @LordUsagi 
Where should I start looking?

**Comment by HEGladios** [comment]
^ Pretend I wrote that from this account!
Didn't know I was signed in with my old account :P

**Comment by LordUsagi** [comment]
Probably look at the commit I did involving visibility, I think its 0023528d952abae5022cdb245aff059df20bf2fa

**Comment by HEGladios** [comment]
That commit looks fine.
Most likely it got bugged from this commit: https://github.com/OregonCore/OregonCore/commit/cb19764d3939a972bc1f705f60578586e700b003#diff-779f79dda311141e707bfd213e2e8e3dL43
I've tried messing around with a couple things, but still running into the same problems.

Could you maybe explain the following to me?
https://github.com/OregonCore/OregonCore/blob/master/src/game/Map.cpp#L614

It creates a ContainerVisitor for grid and world object relocation, but then puts different values into them. One gets default visibility distance, the other gets monster sight radius a few lines up from the config option. Does this not create disparity between grid and world when visiting the cell?

What's the difference between the grid and world relocation objects anyway?
Whenever the cells are visited using Visit(), it's always called twice, once for grid and once for object.

If I ignore the config option for monster sight radius and just use default visibility distance, the problem persists.

Another thing I wonder about is this:
https://github.com/OregonCore/OregonCore/blob/master/src/game/Map.cpp#L431
This check is not in TC. Within that if statement, return is called and the rest of the function is not executed. Is this intended?

I commented the entire if statement, but the problem persists.

Lastly:
https://github.com/OregonCore/OregonCore/blob/master/src/game/Map.cpp#L493
Before calling resetMarkedCells(), TC does this:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Maps/Map.cpp#L686
We don't seem to have that MapSessionFilter, but even so, it calls player Session->Update(diff).
It was removed from OC in this commit: https://github.com/OregonCore/OregonCore/commit/cb19764d3939a972bc1f705f60578586e700b003#diff-779f79dda311141e707bfd213e2e8e3dL509

P.S. the issue @Desteny mentioned with players appearing to be stuck in place after going out of your vision range still persists. Might even be related to the visual bug when you don't see the appropriate buffs on someone. (i.e. party member is in moonkin form but appears as normal to you and you cant see the "moonkin" buff on them either. Even funnier when you see a cow flying around without seeing the Flight Form buff on them, while the player itself does see everything correctly for their own char.)

EDIT: I suspect the issue not to be in map.cpp, but some other file that was changed by the big commit.

**Comment by LordUsagi** [comment]
Have you perhaps tried a rollback of the entire commit?

https://github.com/OregonCore/OregonCore/blob/master/src/game/Map.cpp#L431
This looks like it could be removed. I've not done a lot of work with the Map system in OC to properly get a grasp of it so I can't answer too many of your questions with confidence unfortunately.

See https://github.com/TrinityCore/TrinityCore/commit/26428943423d14e8672682ab1f19925b76c2aa35

**Comment by PadreWoW** [comment]
Any news? Problem fixed?

**Comment by HEGladios** [comment]
I'm still trying to figure out what's causing the issue.
I can 100% confirm that https://github.com/OregonCore/OregonCore/commit/cb19764d3939a972bc1f705f60578586e700b003 started it. The revision before this did not have the bug. I'm not at all experienced with maps, grids, notifiers etc., so any help is appreciated!

**Comment by LordUsagi** [comment]
So you backed it out and it 100% removed it? Good to know its there for sure.

**Comment by HEGladios** [comment]
I found the problem with players being visually stuck when they run out of your range.
Still working on the rest.

**Comment by ghost** [comment]
Can confirm, cb19764 started it, i'm going to take a look and will submit a PR if I fix it

**Comment by ghost** [comment]
Little update : I revert my core to 68fcb0eb059f75bf5251caf50b612df1278fc040
 and manually re-added the visibility change from linencloth, everything works as expected(just tested real quick) I didin't backport other commit related to it yet.

i've made a gist here : https://gist.github.com/Blumfield/37c83234e976d26c22b9

**Comment by LordUsagi** [comment]
If you use meld on your changes and OCs changes at that revision, what are the differences?

**Comment by ghost** [comment]
A lots of codestyle, you should see it for yourself two pair of eyes are better than one

**Comment by LordUsagi** [comment]
for sure

**Comment by ghost** [comment]
I don't understand why the cells are not updating until we move, I think it's a silly typo somewhere in the grid system

**Comment by LordUsagi** [comment]
Even with your fresh changes the cells arent updating?

**Comment by ghost** [comment]
everythings works fine when I revert and re-add the gist ive made, i'm talking about the current change in core

**Comment by ghost** [comment]
Ok, if you do this https://gist.github.com/Blumfield/6a66b26f9226296acb53 the problem is solved( atleast for creature when you remove them) we are missing a backport or a typo was introduced

**Comment by zhy9934** [comment]
Any news? Problem fixed?

**Comment by zhy9934** [comment]
- Tweak ThreatContainer internals.
  - Determine if an object is a WorldObject in class creation
  - Clean & Rewrite parts of grid system.
  - Solve speedy flight path issue created by commmit 7847249
  - Rewrite how we handle various visibility functions.
  - Define unknown AiReaction enum
  - The message deliverer no longer sends packets from a non-visible source
  - Removed a lot of useless Z-Coord checks
  - Limited the grid activation range for creatures
  - Delete objects if it is not successfully added to grid.
  - Make AddToMap return bool for validation checks
  - Make MMap and Vmaps managers threadsafe
  - Begin cleanup of spacing in VMap related files
  - Remove stealth on damage, not on combat enter
  - Creatures now "alert" to stealthed players

the content of the commit  cb19764 is above, who can tell me each correspond to what code，thanks！

**Comment by LordUsagi** [comment]
@Blumfield Can you export your changes in a patch file? The gist you've provided is hard for me to apply.

**Comment by ghost** [comment]
It's only a temporary solution, it might bring more bug.
https://github.com/OregonCore/OregonCore/blob/master/src/game/GridNotifiers.cpp#L168
https://github.com/OregonCore/OregonCore/blob/master/src/game/GridNotifiers.cpp#L199
https://github.com/OregonCore/OregonCore/blob/master/src/game/GridNotifiers.cpp#L220
those are the line in the gist

**Comment by LordUsagi** [comment]
Oh, I meant the backport you did of Linen cloths stuff! But thanks!

**Comment by ghost** [comment]
i'm afraid I don't have it anymore sorry

**Comment by HEGladios** [comment]
Perhaps some interesting information:
If a party member is on the same map as you are, you will not be notified of their location/buffs/etc unless they are in visibility range.
However, you do receive visual updates from party members that are on a different map. Somehow you do receive notifications then.

**Comment by Ozerev** [comment]
I noticed a problem that might be related to this when doing some other stuff. When a temporary summon despawns, it won't disappear until you move. Easiest way to reproduce this is to summon an imp (.cast 688) and dismiss it.

The way objects are removed from the world seem a little strange to me. RemoveFromWorld() is called and then UpdateObjectVisibility(). But UpdateObjectVisibility won't actually do anything if the object is not in the world because of https://github.com/OregonCore/OregonCore/blob/master/src/game/Object.h#l1071-1073

Removing the IsInWorld() check does fix this problem, but I don't know enough about the map system to know if this is a really bad thing to do. The IsInWorld() checks were added in https://github.com/OregonCore/OregonCore/commit/cb19764d3939a972bc1f705f60578586e700b003#diff-779f79dda311141e707bfd213e2e8e3dL43 which was referenced above, but the checks have also been in trinity since 2010. Maybe the order of removing the object from the world and updating visibility needs to be rearranged somehow?

**Comment by LordUsagi** [comment]
@Ozerev I got an email about a reply to this, but I can't see it here.

**Comment by ghost** [comment]
@LordUsagi http://i.imgur.com/Nd9aLEW.png

**Comment by Ozerev** [comment]
Yeah I realized that what I wrote was pretty much exactly what the above commits did, didn't look at them before

**Comment by PadreWoW** [comment]
Problem is still here :(

Not only with mobs

With GOs too

![untitled](https://cloud.githubusercontent.com/assets/6802530/15504044/c02b903c-21c5-11e6-943a-35f21bce5808.png)

**Comment by Ozerev** [comment]
I believe the problem is that obj->UpdateObjectVisibility() does absolutely nothing if obj is not in the world. See https://github.com/OregonCore/OregonCore/blob/master/src/game/Object.h#L1071-1073. Right now, objects are first removed from the world and then obj->UpdateObjectVisibility is called, but this does not actually visit any grid cells.

[This commit](https://github.com/Blumfield/OregonCore/commit/75ea65e24d42352b72a6e67af32989606b7e8519) avoids this problem by making sure visibility is updated anyway. The IsInWorld() checks were added in [this commit](https://github.com/OregonCore/OregonCore/commit/cb19764d3939a972bc1f705f60578586e700b003#diff-779f79dda311141e707bfd213e2e8e3dL43) and removing them does seem to fix the problem, but the same checks have existed in trinity since 2010.

**Comment by LordUsagi** [comment]
the boolean forced does nothing in this case, perhaps the forced was meant to imply it gets past "isinworld" check?

**Comment by ghost** [comment]
obj->RemoveFromGrid();
does nothing aswell if I remember too

**Comment by Ozerev** [comment]
In Trinity the WorldObject class overrides RemoveFromWorld and calls DestroyForNearbyPlayers https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Object/Object.cpp#L1515-1523. This does not happen in Oregon and adding it does seem to fix the problem. It was added in [this commit](https://github.com/TrinityCore/TrinityCore/commit/e87223b453f1f958b077d9f98234d4cb9fc71557) by linencloth two days after the IsInWorld() checks were added, so I guess this is one way to fix the bug.
