### ISSUE TITLE
[crash] _M_find_before_node

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1245]
crashdump: http://pastebin.com/XkTTs8Mq

at this moment i didnt find out how to reproduce the crash..
but maybe logs tells something,
i think by learning a spell from trainer intervene... but not sure.

**Comment by LordUsagi** [comment]
Gee, Many crashes lately coming from your end :D

**Comment by dikkedeur** [comment]
yeah sorry :( i cant do anything about it, dont know how it comes....
