### ISSUE TITLE
Auction House "Usable Items"

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1254]
![Image of Evidence](https://cloud.githubusercontent.com/assets/2672633/11570334/b8f1b1f4-99c4-11e5-9a4e-87ad3fc2bd67.jpg)

Patch 1.4.0:
Recipes you already know will not show up in the auction listing if "Usable Items" is checked.

**Comment by Zaffy** [comment]
Are u sure this ought to implemented on server side? Also wasn't this changed in 2.x.x patch?

**Comment by LordUsagi** [comment]
I'm quite positive this is a server side check, I don't think this was changed in 2.x.x because the same rule applies to WotLK auction house.
