### ISSUE TITLE
Barkeep Kelly incorrect vendor template

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1256]
Barkeep Kelly in the PRESENT southshore should not sell Rumseys black label.

Evidence:
http://wow.gamepedia.com/Barkeep_Kelly

**Comment by dikkedeur** [comment]
This Item is NOT buyable from the normal Barkeeper in Hillsbrad!
It's only obtainable through going into 
Old Hillsbrad Foothills (//www.wowhead.com/?zone=2367)

The Vendor in Hillsbrad is not selling it.

so the fix would be... tadum dadum dadum....

``` sql
DELETE FROM `npc_vendor` WHERE `npc_vendor`.`entry` = 2366 AND `npc_vendor`.`item` = 21151;
```

profit!

**Comment by LordUsagi** [comment]
:100: to go! thanks for the help :)
