### ISSUE TITLE
[crash] WorldObject::GetGridActivationRange >> AreaTrigger_at_commander_dawnforge

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1260]
crashlog: http://pastebin.com/CNyNfDP8

propably related to commander dawnforge script being itchy :+1:

**Comment by Zaffy** [comment]
That commit actually seems to resolved this. Creature (if not found) was deferenced and caused crash, the code is removed now with a better one so this is obsolete.
