### ISSUE TITLE
Feral Swiftness (indoor/outdoor vmap)

### ISSUE THREAD

**Issue by HEGladios** [OregonCore/OregonCore#1262]
https://github.com/OregonCore/OregonCore/commit/8a94bcbe6bc0dc954f7dd8a46252a3dfd50928e8
I think this commit is causing some issues with Cat Form if you have the Feral Swiftness talent.
Feral Swiftness talent gives you movement speed buff outdoors.

When you enter a building in Cat Form it works fine, but if you try to use Cat Form indoors, you get the buff, but bars don't switch and you can't use any cat form abilities.
Also worth noting that upon going indoors as a kitty, you don't lose the speed buff.

**Comment by LordUsagi** [comment]
From a glance this really shouldn't affect it, it was always enabled in the configs by default, this just  removes the ability to toggle it on and off. But I will take a closer look

**Comment by HEGladios** [comment]
Only difference I can see is:
Player.cpp ~line 5786: m_wasOutdoors = isOutdoor;

Looks like it was placed inside brackets before?

**Comment by LordUsagi** [comment]
Nice catch, that's most likely the issue.

**Comment by LordUsagi** [comment]
Still doesn't seem right.

**Comment by HEGladios** [comment]
Hmm, only other thing I can see is you left out a check for GMs in an if statement:
Spell.cpp line 3714
!m_caster->ToPlayer()->isGameMaster()

But that's probably not it.

**Comment by LordUsagi** [comment]
Probably not either. You guys didn't have the config optional disabled originally?

**Comment by LordUsagi** [comment]
I've got it.

**Comment by HEGladios** [comment]
Awesome :)
