### ISSUE TITLE
[Quest] Triage 

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1265]
Problem: You can't target the Injured, Badly Injured and Critically Injured Soldiers with the Triage Bandage to save them.
You hear them dying in the process ( poor souls...)

How it should work: when the soldiers are spawned you should use the badage provided by the doctor to cure the soldiers, when they are cured they will ran to the doctor to thank him.
If you manage to cure at least 15 of those soldiers before 6 of them die, then you get quest credit and can turn it in at the doctor to gain the new first aid skill

**Comment by LordUsagi** [comment]
This quest used to work perfectly.. You're saying its broken now? They don't count for quest credit either?

**Comment by dikkedeur** [comment]
no, you cant target the npc's anymore... i have tested the hord version, and not the alliance version.
so i cant vouch for that one, but propably since they share the same mechanic in npc_special.cpp it might be the same problem there.
i havent tested this quest before, so i cant say if it used to work before, but for now its broken.

**Comment by ghost** [comment]
for horde dont work, i can confirmed :D

**Comment by LordUsagi** [comment]
alliance works, atleast it did. i'll test these again tonight

**Comment by LordUsagi** [comment]
Tested, broken. It looks like the spells not targeting the triage patients. I'm not sure what is the cause of this. 
Edit: But it could potentially break A LOT more spells
