### ISSUE TITLE
Scout Jyoba is not dead

### ISSUE THREAD

**Issue by LordUsagi** [OregonCore/OregonCore#1266]
As the title says, NPC Scout Jyoba located in Zangarmarsh does not have a feign dead state.

Evidence:
https://www.youtube.com/watch?v=D-bgkPonVM0

**Comment by dikkedeur** [comment]
fix:

UPDATE  `creature_template` SET  `dynamicflags` =  '32' WHERE  `creature_template`.`entry` =18035;

that should do the trick.
UNIT_DYNFLAG_DEAD > Makes the creature appear dead (this DOES NOT make the creature's name grey or not attack players).

**Comment by LordUsagi** [comment]
Could you also add a creature addon entry for feign death? :+1:  Spell/Aura is 29266

**Comment by dikkedeur** [comment]
dunno, i took the changes from TC, and they dont have a creature_Addon for that npc in their database.
is that even needed when you set it to dead state with dynamicflags=32???

**Comment by LordUsagi** [comment]
Not sure actually. Good point. I think it prevents attack on players though

**Comment by dikkedeur** [comment]
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `moveflags`, `isActive`, `auras`) VALUES ('84372', '0', '0', '0', '0', '0', '0', '0', '29266');

NOT TESTED :P too lasy been cooking :P and then i mean a real meal cough

**Comment by LordUsagi** [comment]
A real meal hahaa

**Comment by dikkedeur** [comment]
well lets put it this way i needed to help my wife with cooking :p bwuahahaha
ow dont forget for the creature_addon.

first delete then insert ^^
just in case..

**Comment by LordUsagi** [comment]
I might move it to creature_template_addon if I don't find any other instances of Scout Jyoba about.

**Comment by dikkedeur** [comment]
there is no other one indeed,,,

taken from tc

INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(18035, 0, 0, 7, 4097, 0, NULL);

**Comment by Lumber-Jack-2** [comment]
use ```sql for posting fixes

**Comment by LordUsagi** [comment]
We've only recently migrated to github :+1:

**Comment by LordUsagi** [comment]
```
DELETE FROM creature_template_addon WHERE entry = 18035;
INSERT INTO creature_template_addon (entry, path_id, mount, bytes1, bytes2, emote, auras) VALUES
(18035, 0, 0, 7, 4097, 0, '29266 0 29266 1');
```

Even with aura, still attackable. Perhaps need unit flag unattackable.

**Comment by dikkedeur** [comment]
he is attackable if you are alliance, since he is hostile for them, for horde not..
http://www.wowhead.com/npc=18035/scout-jyoba

**Comment by LordUsagi** [comment]
Sure he's hostile but if he's in a dead state he should be immune to combat, he's dead! I think instead of mine we'll remove the feign death aura. Add dynamic flags 32, same as TC and then also add Unit flag unattackable. Should be okay.

**Comment by dikkedeur** [comment]
complete fix now

``` sql
-- make scout jyoba laying dead and not being able to attack at all, since he is dead duh 
-- make scout jyoba unattackable by npc and players, and give him the dead state.
UPDATE  `creature_template` SET  `unit_flags` =  '768',`dynamicflags` =  '32' WHERE  `creature_template`.`entry` =18035;

-- add the aura
DELETE FROM creature_template_addon WHERE entry = 18035;
INSERT INTO creature_template_addon (entry, path_id, mount, bytes1, bytes2, emote, auras) VALUES
(18035, 0, 0, 7, 4097, 0, '29266 0 29266 1');
```

**Comment by LordUsagi** [comment]
nice work, might not keep aura just have unit flags and dynflags :")
