### ISSUE TITLE
I can heal  my friends while they are in duel, shaman and druid bugs too.

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1267]
// Priest.
If i am in party with my friend and this friend make a duel with some one i can heal my friend with Prayer or heal - or something.
Example: Priest are in group with rogue and this rogue make a duel with another player who isn't in our group. The rogue is in duel - and i can heal him because we are in group.

Also and the mass dispel doesn't work. 

// Druid
When i change from human to bear form my HP goes down to 1%.

// Shaman
Poison Cleansing Totem didn't work.

Sorry for my bad english, i hope to understand me and i will be really happy if help me to fix this bugs.

**Comment by LordUsagi** [comment]
You must make seperate issues for each please.

**Comment by LordUsagi** [comment]
Bear form bug is incorrect. Please update your core.
Tested Poison Cleansing totem on Deadly poison. Bug is incorrect. Please update your core.
Mass dispel works. Please update your core.

**Comment by LordUsagi** [comment]
Invalid. Using an old version of the core.
