### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1268]
[1496+_oregon-core.exe_[8-11_15-55-32].txt](https://github.com/OregonCore/OregonCore/files/121163/1496._oregon-core.exe_.8-11_15-55-32.txt)

World Thread is stuck.  Terminating server! 

And that is all. Restarter didn't work too.. I mean when crash.

**Comment by Zaffy** [comment]
Im sorry this rev you use is very very old (plus with c uz tom changes) so I cant help you.

**Comment by kepo123** [comment]
Oh ... How i can to update it?

**Comment by Zaffy** [comment]
Follow installation guide in our [docs](http://docs.oregon-core.net/)
