### ISSUE TITLE
Damage Calculation

### ISSUE THREAD

**Issue by miraco** [OregonCore/OregonCore#1277]
Damage Calculation is wrong.

>    //This formula is not correct
>     //The correct one is (Damage_from_AttackPower + Base_Weapon_Damage) \* Multiplier
>     //We do not know the multiplier, so we assume attack power is about 25% damage
>     //float base_value  = GetModifierValue(unitMod, BASE_VALUE) + GetTotalAttackPowerValue(attType)/ 14.0f \* att_speed;

Thread:
https://forums.oregon-core.net/viewtopic.php?pid=2189#p2189

TC Wotlk Change
https://github.com/TrinityCore/TrinityCore/commit/cd76d3290719161db1c10b4c82de191db1cef7e8#diff-9192fbb21749a5cb201987f5563a7d8e

This include Off Hand attacks

**Comment by LordUsagi** [comment]
Please make a pull request with the changes!

**Comment by miraco** [comment]
I didnt tryed this on OC, thats just something i found the last days
