### ISSUE TITLE
random mobs cant stun

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1279]
Affects all mobs to at low health in the habit of have an ally to run. It makes you think as a villain, then i stunn but time so that you do not cut off. But this has the negative effect that the mob to (still in stun being) directly at the site of the allies teleported.

**Comment by dikkedeur** [comment]
okay to fix english here it comes....

https://github.com/OregonCore/OregonCore/issues/1144

search is your friend :P
