### ISSUE TITLE
[Druid] weapons skill in the shape of an animal

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1281]
The druids increases when the car hits the weapon skill "unarmed" not when you are in Bear or Cat form. This reduces with increasing level the hit rate and the crit rate is enormous, what it even harder makes a Druids to levels. I could make other due to low level do not test. This bug should be a pretty high priority for fixed, because the playability right is severely restricted.

**Comment by LordUsagi** [comment]
I don't quite understand this one. From what I can gather, druids in shapeshift form only level unarmed skills and not their equipped weapon skills, and this makes druids hard to level because they're always in shapeshift form and never getting skill ups for their weapons?

**Comment by dikkedeur** [comment]
well that would be blizzlike isnt it lordusagi? since in shapeshift form you dont "wear" a weapon

**Comment by LordUsagi** [comment]
I think so, but maybe I miss what he means.

**Comment by dikkedeur** [comment]
we both might do... i was just thinking he ment that the unarmed is NOT increased.. so we both read it different :+1:

**Comment by BIOS-THE-ORIGINAL** [comment]
I mean the weapons skill "unarmed" should be skill points if you receive in cats or bear form. This happens but not.

**Comment by LordUsagi** [comment]
I see, do you have any evidence? Even if I somewhat agree I can't seem to find anything stating so.

**Comment by LordUsagi** [comment]
Line 5220, Player.cpp - // always maximized SKILL_FERAL_COMBAT in fact

It seems like your weapon skills are NOT supposed to go up in combat.

Evidence articles:
http://www.gamefaqs.com/boards/534914-world-of-warcraft/56419045
http://www.wowhead.com/forums&topic=8265/mace-skill-shapeshift
http://vanilla-wow.wikia.com/wiki/Druid
