### ISSUE TITLE
Swimming in the sewers in undercity makes you get lava damage

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1284]
**Revision**: https://github.com/OregonCore/OregonCore/commit/894f09c95cc3fd8067b12652058355cd71bab498

**Operating system**: unix

**Current behavior**:  Swimming in undercity in the green slime makes you take damage, 
....

**Expected behavior**:  you should not get damage from swimming in the sewers in undercity in the green what is it.. slime?
...

**Steps to reproduce the problem**: make char go to undercity and take a swim, you will get lava damage... and die from it.

![schermafbeelding 2016-02-18 om 23 53 18](https://cloud.githubusercontent.com/assets/11842306/13160937/f0043a82-d69a-11e5-97d1-b78519818ad2.png)

**Comment by LordUsagi** [comment]
I wonder if this affects other lava/slime pools such as Naxxramas, Lordearon Arena etc.

**Comment by dikkedeur** [comment]
indeed same on naxx, 

and another strange thing, when you stand in it
![schermafbeelding 2016-02-19 om 08 57 35](https://cloud.githubusercontent.com/assets/11842306/13169585/f7a3dcce-d6e6-11e5-8386-e34e27cc97b4.png)

fatigue :P

**Comment by LordUsagi** [comment]
lol wot

**Comment by dikkedeur** [comment]
yeah it gets weirder and weirder indeed ^^

**Comment by LordUsagi** [comment]
I don't think any changes were made to liquid types recently, but I don't think the problem was long existing either. Perhaps its to do with the dreaded vmaps4 stuff.

**Comment by dikkedeur** [comment]
hmmm, could be, i have no idea... i never encountered this before indeed.

**Comment by LordUsagi** [comment]
I think I'm onto it

**Comment by LordUsagi** [comment]
test

**Comment by LordUsagi** [comment]
e5d23103f37c40d2e946fa0e2db66d2f527ad9af TC hash

**Comment by dikkedeur** [comment]
will test when i feel a little bit better.. cough ^^

**Comment by ghost** [comment]
My player says in all water anwehre :D

**Comment by ghost** [comment]
this change
https://github.com/OregonCore/OregonCore/commit/6a77dafe6db7f96492d1d046f3474ccf25081215
makes the problem... ihave change it for me to the old and now works again fine

**Comment by dikkedeur** [comment]
but then you get the old problem that you have in the sewers lava damage right??
since that was the case before the change and it was lords intention to fix it with that commit right?

**Comment by ghost** [comment]
Thats right, but better just there then overall

**Comment by LordUsagi** [comment]
I don't understand Alphafoxes problem

**Comment by ghost** [comment]
Alphafox also :D

**Comment by LordUsagi** [comment]
i mean whats the problem i dont understand

**Comment by ghost** [comment]
9 Compile error for Tools

Fehler  6101    error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""void __cdecl Oregon::at_exit(void (__cdecl_)(void))" (?at_exit@Oregon@@YAXP6AXXZ@Z)" in Funktion ""public: static void __cdecl Oregon::ObjectLifeTime<class Log>::ScheduleCall(void (__cdecl_)(void))" (?ScheduleCall@?$ObjectLifeTime@VLog@@@Oregon@@SAXP6AXXZ@Z)".    D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(VMapManager2.obj) movements_extractor
Fehler  6102    error LNK2001: Nicht aufgelöstes externes Symbol ""void __cdecl Oregon::at_exit(void (__cdecl*)(void))" (?at_exit@Oregon@@YAXP6AXXZ@Z)".   D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(MapTree.obj)  movements_extractor
Fehler  6103    error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: __cdecl Log::Log(void)" (??0Log@@AEAA@XZ)" in Funktion ""public: static class Log \* __cdecl Oregon::OperatorNew<class Log>::Create(void)" (?Create@?$OperatorNew@VLog@@@Oregon@@SAPEAVLog@@XZ)".   D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(VMapManager2.obj) movements_extractor
Fehler  6104    error LNK2001: Nicht aufgelöstes externes Symbol ""private: __cdecl Log::Log(void)" (??0Log@@AEAA@XZ)".    D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(MapTree.obj)  movements_extractor
Fehler  6105    error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""private: __cdecl Log::~Log(void)" (??1Log@@AEAA@XZ)" in Funktion ""private: void \* __cdecl Log::`scalar deleting destructor'(unsigned int)" (??_GLog@@AEAAPEAXI@Z)".    D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(VMapManager2.obj) movements_extractor
Fehler  6106    error LNK2001: Nicht aufgelöstes externes Symbol ""private: __cdecl Log::~Log(void)" (??1Log@@AEAA@XZ)".   D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(MapTree.obj)  movements_extractor
Fehler  6107    error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""public: void __cdecl Log::outError(char const *,...)" (?outError@Log@@QEAAXPEBDZZ)" in Funktion ""public: class VMAP::WorldModel \* __cdecl VMAP::VMapManager2::acquireModelInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?acquireModelInstance@VMapManager2@VMAP@@QEAAPEAVWorldModel@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)".    D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(VMapManager2.obj) movements_extractor
Fehler  6108    error LNK2001: Nicht aufgelöstes externes Symbol ""public: void __cdecl Log::outError(char const *,...)" (?outError@Log@@QEAAXPEBDZZ)".    D:\OregonCoreGITCmake\src\tools\movements_extractor\collision.lib(MapTree.obj)  movements_extractor
Fehler  6109    error LNK1120: 4 nicht aufgelöste Externe  D:\OregonCoreGITCmake\bin\Debug\movements_extractor.exe movements_extractor

**Comment by LordUsagi** [comment]
Clean and rebuild, build in release.

**Comment by ghost** [comment]
Extractor running but problem is always there

**Comment by Thema89** [comment]
@LordUsagi problem encountered by @AlphafoxBHN still persists: after https://github.com/OregonCore/OregonCore/commit/6a77dafe6db7f96492d1d046f3474ccf25081215 you  correctly won't get lava damage in slime anymore, but this hasn't fixed the issue because now you get lava damage from common water (except some ocean-type and, strangely enough, Stormwind sewer) everywhere, every lake or river.
What he tried to say is that things are worse then before with that commit, so he reverted that to deal with this problem only in slime pools and some other spots.


Some quick .go XY coords examples: 
- Crystal Lake (Elwynn Forest) X:-9456   Y:-76 (map: 0)
- Stratholme Lake (Eastern Plaguelands) X:3341  Y:-3356  (map: 0)
- Tarren Mill River (Hillsbrad Foothills) X:8  Y:-1100 (map: 0)
- Darnassus (Teldrassil) X:9962  Y:2489 (map: 1)
- Southfury River (Durotar) X:347  Y:-3786 (map: 1)

Ocean (swimmable) water examples:
- GM Island
- BootyBay (Stranglethorn Vale) X:-14304 Y:526 (map:0)
- Steamwheedle Port (Tanaris) X:-7044 Y:-4848 (map:1)

Odd-Ocean that will be lava (no matter what defines you use):
- Quel'Danas (.tele IsleOfQuel'Danas)
- (there might be more)


I picked up few "random" spots in my local server, but *any* river or not-ocean water in the world is clearly affected, so imho at least Liquidtype still don't get handled properly, but I'd say there's some map-related errors too.
(EDIT: remember to test it in .gm off or you won't trigger lava damage)
