### ISSUE TITLE
Alliance Shaman Water Totem Quest

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1285]
**Revision**: e7036ac+

**Operating system**: Windows Webserver 2008 RC2

**Current behavior**:  Shaman Water Totem Quest
....

**Expected behavior**:  Alliance Shaman Water Totem Quest all Alliance Shami´s becames the horde start Quest
...

**Steps to reproduce the problem**: make char lvl to lvl 20 go to Aqueous and start the quest. first quest is the Horde quest:(http://www.wowhead.com/quest=9501/call-of-water)
Alliance needet:http://www.wowhead.com/quest=9504/call-of-water

**Comment by Zaffy** [comment]
I can not reproduce this. The chain starts in exodar at shaman trainer. I want all the questchain and it works just fine. There are some missing scripts tho like [this one](https://youtu.be/LiJN1fMnAv0?t=39).
