### ISSUE TITLE
[Quest] Thwart the Dark Conclave

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1287]
**Revision**: e7036ac+

**Operating system**: Windows Webserver 2008 RC2

**Current behavior**: [Quest] Thwart the Dark Conclave
....

**Expected behavior**: The spirits of the dark conclave seek to summon an ancient and powerful evil through a ritual conducted at the lava pits to the south of the Sketh'lon Base Camp.

Gul'dan's magic mingled with their own, empowering them to aid this creature in manifesting in our world! We must not allow this to happen, <name>. The death and destruction it would bring are unimaginable!

Carry the staff with you to the site of the summoning and use its magics to stop the dark conclave once and for all! 
...

**Steps to reproduce the problem**:  Cannot be activated. Apparently, one was at the wrong place, this is the error message.

**Comment by LordUsagi** [comment]
Should be fixed as of 54dd56c2e16b9309bc00f89b5bd50cc5b563f1d6

**Comment by Selphius** [comment]
Quest itself work from what I see with this SmartAI commit, But objects are nowhere to be seen to make it work from land not lava.
Should be fixed with: https://github.com/OregonCore/OregonCore/commit/b9d9483c9b5102121e5efc4097eb67674e602c88
