### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1289]
**Revision**: e7036ac+

**Operating system**: Windows Webserver 2008 RC2

**Current behavior**: 
....

**Expected behavior**: The fortress of Legion Hold is your target. You'll have no reinforcements, so a frontal attack is out of the question.

What little information we have shows that the Legion stocks and prepares its infernals at the hold. With the help of a disguise I'll give you, you must sneak into Legion Hold and discover their plans.

Your best hope is to intercept or overhear communication between their commanders. 
...

**Steps to reproduce the problem**: The NPC, actually only comes when you are in the box transforms, is already there. Thus, the call is also not initiated, what you listen to. And if you had it before death, he does not appear to be the case again if you used. Generally, it then not again.

**Comment by Selphius** [comment]
I don't understand what you are trying to say, you mean that when you complete it once, next person can't complete it? or what, since I really can't comprehend it in my mind with such description.

**Comment by dikkedeur** [comment]
the problem with the quest at this moment is as follows:

1) the script is running always, meaning the image of warbringer razuun is talking and jovaan when server starts.. it is not starting when you have the disguise on you and move within range ( as it should if im correct )

2) you get credit for quest if you are in disguise ( good ) and if you want without disguise ( not good ^^ )

i haven tested yet if you can do it once or multiple times, the respawn time is little bit long on high pop. servers maybe.. but who cares.

**Comment by dikkedeur** [comment]
after 30 minutes jovaan doesnt get reserructed, so the script only works instantly at server start then you can propably wait forever since npcs dont respawn

**Comment by Selphius** [comment]
@dikkedeur  I think I found the cause of it, it's a rather stupid cause caused by commiting my fixes, without deleting old ones.

**Comment by dikkedeur** [comment]
ugh okay, well i dont know what the old code or new is.... i think, it works better then before that is for sure, but only 1 time and at start of server :p

**Comment by Selphius** [comment]
@dikkedeur Come on IRC if you can, I will give you fix, so you can test it

**Comment by Selphius** [comment]
Fixed. Though commit will be added, when I catch @Zaffy or get access to commit myself. So hold your balls :D

**Comment by dikkedeur** [comment]
this can be closed.
