### ISSUE TITLE
[NPC/Quest] Wing Commander Dabir'ee

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1291]
**Revision**: e7036ac+

**Operating system**: Windows Webserver 2008 RC2

**Current behavior**:  Taxi and Quest behavior
....

**Expected behavior**: Take Flight Path ("Quest - Hellfire Peninsula (Alliance Path) Start" - "Shatter Point, Hellfire Peninsula")
...

**Steps to reproduce the problem**: The NPC will actually to rubble item fly. The balloon is already available, however, the volume wowhead designated taxi effect not, but there is the other effect for the corresponding Quest. If you have the quest has and the corresponding quest selects option, as it should be the quest rod.

**Comment by AbraKabastard** [comment]
Solved
