### ISSUE TITLE
Quest Help tavara

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1294]
**Revision**: https://github.com/OregonCore/OregonCore/commit/a746d3f497cd2d8c3a35ede474c0caae07f76d7a

**Operating system**: Unix and osx

**Current behavior**: tavara cant be healed since she is NOT selectable, when you cast your healing spell it will cast on you instead of her and there you dont get the questcredit
....

**Expected behavior**:  heal that girl and get quest credit
...

**Steps to reproduce the problem**: make priest, level up to level 5 or 6, then take quest, find tavara, cast lesser healing spell ( 2050 or 2052 ) or gift of the naaru then cast one of those spells on her, you will see that even if you have her targeted it wont credit.
changing the unit_flag from 4096 to 4104 as trinity did will not solve the problem, dont know why.
i also used their smartai just in case, still no luck

in case you want the smartai

``` sql
-- Tavara SAI
SET @ENTRY := 17551;
SET @SPELL_GIFT_OF_THE_NAARU_PR := 59544; -- Gift of the Naaru - Priest
SET @SPELL_LESSER_HEAL_R1 := 2050; -- Lesser Heal R1
SET @SPELL_LESSER_HEAL_R2 := 2052; -- Lesser Heal R2
SET @SPELL_RENEW_R1 := 139; -- Renew R1 (they don't have R2 yet)
UPDATE `creature_template` SET `AIName`='SmartAI',`RegenHealth`=0 WHERE `entry`=@ENTRY;
UPDATE `quest_template` SET `ReqSpellCast1`=0 WHERE `entry`=9586;
DELETE FROM `creature_ai_scripts` WHERE `creature_id`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@ENTRY,@ENTRY*100);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,8,0,100,1,@SPELL_LESSER_HEAL_R1,0,0,0,33,17551,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Spellhit - Give Quest Credit"),
(@ENTRY,0,1,0,8,0,100,1,@SPELL_LESSER_HEAL_R2,0,0,0,33,17551,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Spellhit - Give Quest Credit"),
(@ENTRY,0,2,0,8,0,100,1,@SPELL_GIFT_OF_THE_NAARU_PR,0,0,0,33,17551,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Spellhit - Give Quest Credit"),
(@ENTRY,0,3,0,8,0,100,1,@SPELL_RENEW_R1,0,0,0,33,17551,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Spellhit - Give Quest Credit");
```

**Comment by LordUsagi** [comment]
I find this is related to the Triage quests where you CAN select a unit but casting spells still forces the cast on yourself

**Comment by dikkedeur** [comment]
it looks indeed to the same problem, that you cant select npcs to cast healing spells to it indeed.

**Comment by ghost** [comment]
Adding the flag UNIT_FLAG_PVP_ATTACKABLE seems to ignore the faction and causes the NPC to appear hostile. You are unable to attack it though, even with `unit_flags` being set to 8 instead of 4104.

**Comment by LordUsagi** [comment]
Zaffy thought this was something due to my grid changes but I feel like this might be due to incorrect flag handling. For example, you can cast Lesser Heal on Stormwind Guards etc.

Edit: Looks like something to do with **flags_extra** in particular, the **civillian** flag
