### ISSUE TITLE
[Spell] Paladin Human Righteous Defense

### ISSUE THREAD

**Issue by BIOS-THE-ORIGINAL** [OregonCore/OregonCore#1295]
**Revision**: a746d3f

**Operating system**: Windows Webserver RC2

**Current behavior**: Come to the defense of a friendly target, commanding up to 3 enemies attacking the target to attack the Paladin instead.
....

**Expected behavior**: Paladin Human spot
...

**Steps to reproduce the problem**: i dont can spot any mobs (Pala lvl70)

**Comment by LordUsagi** [comment]
Duplicate of #985
