### ISSUE TITLE
Vanish not applying stealth

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1296]
**Revision**: 
a746d3f 

**Operating system**: 
Ubuntu

**Current behavior**: 
Use Vanish, only the vanish buff appear

**Expected behavior**: 
When using Vanish, you should get stealth buff

**Steps to reproduce the problem**:

Use vanish, no stealth will be applied

**Comment by LordUsagi** [comment]
Definitely applying stealth for me. Make sure you've learnt Vanish from a Rogue skill trainer and not through any in game commands.

Can I get some feedback from other players?

**Comment by zhy9934** [comment]
i have not this problem ,vanish is fine

**Comment by LordUsagi** [comment]
I see from another issue report #1300 it only happens in combat

**Comment by Tixlenra** [comment]
It is broken in combat. It does not apply "Stealth" - only the visual interpretation by the spell "Improved Stealth"

**Comment by LordUsagi** [comment]
@nairyo #1300 
The only solution I could come up with looking quickly was

``` C++
@@ -2336,6 +2335,9 @@ void Spell::EffectTriggerSpell(SpellEffIndex effIndex)
            if (m_caster->ToPlayer()->HasSpellCooldown(spellInfo->Id))
                m_caster->ToPlayer()->RemoveSpellCooldown(spellInfo->Id);

+           // Remove from combat
+           m_caster->CombatStop();

            m_TriggerSpells.push_back(spellInfo);
            return;
        }
```

Triggered spells don't get to skip the in combat check, which I think is fair and is consistent with other projects. TrinityCore looks to force the sanctuary effect of Vanish first, and then apply stealth, which I imagine is what allows it to cast freely over there.

**Comment by nairyo** [comment]
@LordUsagi Sanctuary is definitly needed as vanish gives the caster a very small time of immunity against all damages ( maybe .1sec or so). This is what allows player to "vanish absorb" spells.
This solution looks good and is working
