### ISSUE TITLE
Arcane Missiles Has No Cast Bar

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1297]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
Arcane Missiles has no cast bar.

Expected behavior: 
Arcane Missiles has a cast bar.

Steps to reproduce the problem:

Use Arcane Missiles

**Comment by dikkedeur** [comment]
confirmed.

**Comment by LordUsagi** [comment]
Confirmed, this is odd!

**Comment by adeutscher** [comment]
The problem seems to come up right out of the gate based on AM's SpellEntry in `Spell::Spell` when the spell's `m_isCastTimeHidden` is set. A bit of a silly question, but is there anything that can be done to challenge this sort of quirk other than the specific fixes like in 4f74edf?
