### ISSUE TITLE
Water Elemental Dismissal Issue

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1299]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
When you dismiss the Water Elemental, he stays in the game but disappears from your pet bar.

Expected behavior: 
When you dismiss the Water Elemental, he should disappear. (despawn)

Steps to reproduce the problem:

Use Water Elemental and dismiss it from the pet bar.

**Comment by LordUsagi** [comment]
Have you tried moving after dismissing him? Does he despawn then?

**Comment by Tixlenra** [comment]
Yes, I dismissed him in the middle of a duel whilst fighting, he just stood there, once the entire duration for the Water Elemental has passed, that is when he despawns.

**Comment by LordUsagi** [comment]
Very odd. Thanks for sharing! 

I'm going to assume it's related to #1243 BUT I will test it personally later on today, and it may be a separate issue in and of itself.

**Comment by Zaffy** [comment]
Resolution?

**Comment by LordUsagi** [comment]
Solved with the visibility update.
