### ISSUE TITLE
Combat Vanish Bug

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1300]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
Vanish only works out of combat.

Expected behavior: 
Vanish should work in and out of combat.

Steps to reproduce the problem:

Attack an enemy player and use vanish, you only get the "Improved Stealth" buff.

**Comment by nairyo** [comment]
I'm not sure of what's happening here. I've tried multiple things, like adding casting stealth when applying the "improved stealth" buff, adding spell triggers on the vanish spell info, but it doesn't seem to work.
Maybe it's related with the fact that vanish is suppose to apply a very short immunity to player ?
http://db.hellground.net/?spell=26889 see effect #3
