### ISSUE TITLE
Removing Stealth Should Remove "Improved Stealth" 

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1301]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
Removing Stealth keeps the buff "Improved Stealth" which has a visual interpretation on the character to still be invisible.

Expected behavior: 
Removing Stealth should also remove the buff "Improved Stealth"

Steps to reproduce the problem:

Use Vanish and cancel Stealth

**Comment by nairyo** [comment]
```
--- a/src/game/Unit.cpp
+++ b/src/game/Unit.cpp
@@ -4139,7 +4139,10 @@ void Unit::RemoveAura(AuraMap::iterator& i, AuraRemoveMode mode)
     // if unit currently update aura list then make safe update iterator shift to next
     if (m_AurasUpdateIterator == i)
         ++m_AurasUpdateIterator;
-
+    if(Aur->GetSpellProto()->Id == 1787) // #nairyo : removing stealth will always remove vanish buff
+    {
+        Aur->GetCaster()->RemoveAurasDueToSpellByCancel(26888); // remove vanish buff
+    }

```

**Comment by nairyo** [comment]
@LordUsagi have you fixed that vanish doesnt apply stealth or should i look into it?

**Comment by nairyo** [comment]
```
diff --git a/src/game/Unit.cpp b/src/game/Unit.cpp
index 5e70860..4da2ef1 100644
--- a/src/game/Unit.cpp
+++ b/src/game/Unit.cpp
@@ -12956,7 +12959,10 @@ void Unit::AddAura(uint32 spellId, Unit* target)
 
     if (target->IsImmuneToSpell(spellInfo))
         return;
-
+    if (spellId == 26888)
+    {
+        target->AddAura(1787,target);
+    }

```

**Comment by LordUsagi** [comment]
@nairyo We don't want anything specifically hard coded into the core like this unless it's a general solution.

The below solution works just as well.

``` SQL
-- Link Stealth and Vanish removal
DELETE FROM spell_linked_spell WHERE spell_effect = -26888;
INSERT INTO spell_linked_spell VALUES
(-1784, -26888, 0, "Removing Stealth Rank 1 Removes Vanish"),
(-1785, -26888, 0, "Removing Stealth Rank 2 Removes Vanish"),
(-1786, -26888, 0, "Removing Stealth Rank 3 Removes Vanish"),
(-1787, -26888, 0, "Removing Stealth Rank 4 Removes Vanish");
```

But I believe this might have something to do with SPELL_ATTR2_UNK1 which is used in Vanish, Ghost Wolf, Shadowform etc. If someone can give me a hard reason why I'm insanely wrong, I'll commit the above SQL.

And if that is the case, then we must do something such as

``` C++
@@ -2855,6 +2856,9 @@ void Aura::HandleAuraModShapeshift(bool apply, bool Real)
                break;
        }

        // Remove auras linked to forms, such as Vanish and Stealth
        m_target->RemoveAurasWithAttribute(SPELL_ATTR2_UNK1);

        /* We need to re-apply any of transform auras:
           Great example is OHF, when you are in cat form and unshapeshift,
           you should be a human not your original model */
```

**Comment by nairyo** [comment]
@LordUsagi Sure, I've got no idea about what happens in DB, but this definitely makes more sense.
did you have time to take a look to combat bug as well ? https://github.com/OregonCore/OregonCore/issues/1300

**Comment by LordUsagi** [comment]
Yeah. This one is next on my list. I think I have a solution, will be
testing and pushing tomorrow.

**Comment by Zaffy** [comment]
@LordUsagi got this one?

**Comment by LordUsagi** [comment]
Both solutions I posted are potentially beneficial. I'd rather the spell
attribute check.
