### ISSUE TITLE
Quest:the-end-of-the-deserters

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1303]
**Revision**:
actual
**Operating system**:
Windows server
**Current behavior**: 
http://www.wowhead.com/npc=23941/gavis-greyshield
Triger to Friendli but quest is not completed

**Expected behavior**: 
must completed

**Steps to reproduce the problem**:

Try it

http://www.wowhead.com/quest=11134/the-end-of-the-deserters

**Comment by delebota** [comment]
He should cast Spell 42660 on the player.
http://db.hellground.net/?spell=42660

Also he seems to be bugged, when he evades and runs back to his spawn point he often re-aggros before he makes it back. He should return to his spawn point and become friendly for two minutes.
