### ISSUE TITLE
MMAPS does not extract properly, says that the ".map" files are the wrong version.

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1304]
Revision: 
a746d3f

Operating system: 
Windows

Current behavior: 
MMAPS says that all of the .map files are the "wrong version"  and to "please extract new .map files"

Expected behavior: 
MMAPS runs and creates files.

Steps to reproduce the problem:

Use movements_extractor in WoW folder.

**Comment by Zaffy** [comment]
Did you try the reextracting?

**Comment by Tixlenra** [comment]
The error still remains

**Comment by LordUsagi** [comment]
This is probably because I updated maps version

**Comment by Tixlenra** [comment]
A fix would be greatly appreciated

**Comment by Tixlenra** [comment]
Can you send the .exe for movements_extractor?

**Comment by qidian008** [comment]
@LordUsagi MMAPS how to extract, there is a tutorial? Thank you very much

**Comment by kotishe** [comment]
Just run un order
map-extractor.exe
vmap-extractor.exe
Create dir vmaps
vmap-assembler.exe Buildings vmaps
movements-extractor.exe

Make it in wow folder

**Comment by qidian008** [comment]
@kotishe I run the movements-extractor.exe program, disappeared.

**Comment by kotishe** [comment]
Need extract all other data
