### ISSUE TITLE
OregonCore database

### ISSUE THREAD

**Issue by qidian008** [OregonCore/OregonCore#1305]
**Revision**:
a746d3f
**Operating system**:
Windows
**Current behavior**: 
Database error

Everybody is good, I use the database startup when a lot of mistakes, can share a new complete database for me? Thank you very much

**Comment by dikkedeur** [comment]
you must use the oregon database, then use the database updater in the config to enable, then it will update the whole databse to the latest revision.

**Comment by LordUsagi** [comment]
There is quite a lot of startup warnings though, and these are posted in
another issue topic. I wouldn't worry too much about them currently.

**Comment by qidian008** [comment]
@dikkedeur  Where can I get Oregon database

**Comment by dikkedeur** [comment]
https://github.com/OregonCore/OregonCore/releases

**Comment by dikkedeur** [comment]
can this be closed?? not related to a bug present if you use oc db.
