### ISSUE TITLE
Quel'Danas

### ISSUE THREAD

**Issue by qidian008** [OregonCore/OregonCore#1306]
**Revision**:
a746d3f
**Operating system**:
Windows

Transfer to Danner Quayle's Island，The creature appeared in the air，server is not responding，
But it does not crash,Ask for help, how to solve this

**Comment by dikkedeur** [comment]
ehhh? https://github.com/OregonCore/OregonCore/issues/1305
did you update it with everything??
maybe be more specific?

**Comment by dikkedeur** [comment]
can this be closed, doesnt seem to happen on a clean oc db.
