### ISSUE TITLE
"Speed" PvP Buff Appears As A Buff Instead Of A Debuff

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1308]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
"Speed" PvP buff that appears in multiple battlegrounds appears as a buff rather than a debuff.

Expected behavior: 
When you get the Speed buff it should appear as a debuff so it cannot be deactivated by the player.

Steps to reproduce the problem:

Go into a battleground and get the Speed buff.

**Comment by LordUsagi** [comment]
Linked with #1307.
Are you certain this is intended behavior? I can't seem to find anything stating either way.

**Comment by Tixlenra** [comment]
Yes. Blizzards servers have always had it as a debuff.
