### ISSUE TITLE
When you enter Battlegrounds (AB/WSG/AV/EOTS) you are constantly teleported to the start point.

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1310]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
When you enter Battlegrounds (AB/WSG/AV/EOTS) you are constantly teleported to the start point.

Expected behavior: 
You should be able to run around behind the gates of all battlegrounds.

Steps to reproduce the problem:

Go into a battleground and try to move in the warm-up phase.

**Comment by talamortis** [comment]
You could fix it by just disabling the safe zone  or you could change the safe zone diamiter in the battleground.cpp
