### ISSUE TITLE
Life Tap Error Message

### ISSUE THREAD

**Issue by Tixlenra** [OregonCore/OregonCore#1311]
Revision: 
a746d3f

Operating system: 
Ubuntu

Current behavior: 
When you use Life Tap with no pet active, it spams the error message "You Do Not Have A Pet" because of the talent "Mana Feed"

Expected behavior: 
When you use Life Tap with no pet active, no error message appears.

Steps to reproduce the problem:

Spec into "Mana Feed" and use Life Tap without a pet active.

**Comment by dikkedeur** [comment]
should this be closed??

**Comment by Goatform** [comment]
No, I think that we need to ignore error reporting in SpellCast from that spell.

**Comment by Zaffy** [comment]
I think this was fixed. When you don't have a pet, then no attempt to restore its mana will be done.
