### ISSUE TITLE
shadowmoon_valley.cpp

### ISSUE THREAD

**Issue by kotishe** [OregonCore/OregonCore#1319]
**Revision**:
last
**Operating system**:
win
**Current behavior**: 
OregonCore/shadowmoon_valley.cpp wrong folder

**Expected behavior**: 
right place is script folder

**Steps to reproduce the problem**:

look source https://github.com/OregonCore/OregonCore/commit/4a4951a74114070ef09f1c8dd1edd1d4124ac88a

**Comment by Selphius** [comment]
It should be removed, it's old file, not needed.

**Comment by kotishe** [comment]
okay sorry, ty for amazing updates!
