### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by reactmay** [OregonCore/OregonCore#1329]
Downloaded via: git clone git://github.com/OregonCore/OregonCore.git

Immediately I began to compile, The inspection does not find ...

Image: [http://www.pixic.ru/i/r091s002D7N9W7w7.png
![default](https://cloud.githubusercontent.com/assets/9634736/13903742/a380bc7c-eedb-11e5-8344-a5366ca8c33f.png)
](http://www.pixic.ru/i/r091s002D7N9W7w7.png)

**Comment by Zaffy** [comment]
Run git status and post here the output

**Comment by reactmay** [comment]
![default](https://cloud.githubusercontent.com/assets/9634736/13980065/6faa1766-f130-11e5-9b23-a5240268600c.png)

It did not help

**Comment by Zaffy** [comment]
If you really didn't modify anything it should be safe for you to run

```
git reset --hard
```

If it persists after that, let me know what OS you're using and also post here or somewhere else output of git diff

**Comment by reactmay** [comment]
​Hi, I did what you said. Did not work out

2016-03-23 23:46 GMT+10:00 Zaffy notifications@github.com:

**Comment by Baynar** [comment]
Same on Windows 10
![image](https://cloud.githubusercontent.com/assets/16941621/15296695/302694b8-1b9f-11e6-8aff-6a4a1e2d810e.png)
![image](https://cloud.githubusercontent.com/assets/16941621/15296722/50bf7d02-1b9f-11e6-8e2f-ce0bceb2dcc9.png)
![image](https://cloud.githubusercontent.com/assets/16941621/15296728/5d541cf8-1b9f-11e6-83c3-ba94ad16c439.png)

**Comment by Baynar** [comment]
This revision problem is caused from VIsual studio.
If you use any other version than VS 2015 the revision will not be generated.
atleast for me on Windows 10

**Comment by Zaffy** [comment]
can i ask for you cmake version?

**Comment by Baynar** [comment]
4.5.2

**Comment by Baynar** [comment]
Update: When u configurate and generate the project revision looks normal with rev 3447 and so on but after compile it becomes like this
![image](https://cloud.githubusercontent.com/assets/16941621/15334385/a41cb8de-1c76-11e6-9eda-f5419b5aa70a.png)

**Comment by Baynar** [comment]
Is someone looking this up ? its not a big problem but its good to have it fixed

**Comment by Zaffy** [comment]
Not sure but could you try to include these in your ~/.gitconfig?

```
[core]
    filemode = false
    autocrlf = false
```

**Comment by kotishe** [comment]
Commit this zaffy :)

**Comment by Zaffy** [comment]
Huh? There's nothing to commit...

**Comment by kotishe** [comment]
Ah, lol ok

**Comment by Zaffy** [comment]
what happens if you run these commands? These are executed by cmake if there's any error it should show up as well. Keep the order.

```
git rev-list HEAD --abbrev-commit --count
git rev-list HEAD --abbrev-commit -1
git diff --quiet HEAD
echo $?
```
