### ISSUE TITLE
Crash dumps

### ISSUE THREAD

**Issue by kotishe** [OregonCore/OregonCore#1330]
**Revision**:
last
**Operating system**:
Win Server x64
**Current behavior**: 
After core crash we have no any crash dump files

**Expected behavior**: 
Crash file need drop to "Crashes" folder

**Steps to reproduce the problem**:
wait core crash

**Comment by LordUsagi** [comment]
Did you build in debug mode?

**Comment by LordUsagi** [comment]
No feedback
