### ISSUE TITLE
[Crashes] need help

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1333]
**Revision**:
last
**Operating system**:
win server 2008 r2
**Current behavior**: 
occur crash repeatedly

**Expected behavior**: 
find the point of error

**Steps to reproduce the problem**:
i analyze the dmp file through WinDbg ,the result is :

---
-                                                                             *
-                        Exception Analysis                                   *
-                                                                             *
  *******************************************************************************

**\* WARNING: Unable to verify timestamp for oregon-core.exe
**\* WARNING: Unable to verify timestamp for ace.dll
**\* ERROR: Module load completed but symbols could not be loaded for ace.dll
**\* WARNING: Unable to verify timestamp for kernel32.dll
**\* ERROR: Module load completed but symbols could not be loaded for kernel32.dll
****\* OS symbols are WRONG. Please fix symbols to do analysis.

****\* OS (WOW64 kernel32) symbols are WRONG. Please fix symbols to do analysis.

Unable to load image C:\Windows\SysWOW64\ole32.dll, Win32 error 0n2
**\* WARNING: Unable to verify timestamp for ole32.dll
**\* ERROR: Module load completed but symbols could not be loaded for ole32.dll
Unable to load image C:\Windows\SysWOW64\KERNELBASE.dll, Win32 error 0n2
**\* WARNING: Unable to verify timestamp for KERNELBASE.dll
**\* ERROR: Module load completed but symbols could not be loaded for KERNELBASE.dll
Unable to load image C:\Windows\System32\mswsock.dll, Win32 error 0n2
**\* WARNING: Unable to verify timestamp for mswsock.dll
**\* ERROR: Module load completed but symbols could not be loaded for mswsock.dll
**\* WARNING: Unable to verify timestamp for ws2_32.dll
**\* ERROR: Module load completed but symbols could not be loaded for ws2_32.dll

FAULTING_IP: 
msvcr120!_uncaught_exception+595
6d0f3b0b 803900          cmp     byte ptr [ecx],0

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 6d0f3b0b (msvcr120!_uncaught_exception+0x00000595)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000004
Attempt to read from address 00000004

PROCESS_NAME:  oregon-core.exe

ADDITIONAL_DEBUG_TEXT:  
Use '!findthebuild' command to search for the target build information.
If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

FAULTING_MODULE: 76b00000 kernel32

DEBUG_FLR_IMAGE_TIMESTAMP:  524f7ce6

MODULE_NAME: msvcr120

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%08lx

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - 0x%08lx

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000004

READ_ADDRESS:  00000004 

FOLLOWUP_IP: 
msvcr120!_uncaught_exception+595
6d0f3b0b 803900          cmp     byte ptr [ecx],0

MOD_LIST: <ANALYSIS/>

FAULTING_THREAD:  000011bc

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_DEREFERENCE_INVALID_POINTER_READ_WRONG_SYMBOLS_FILL_PATTERN_ffffffff

PRIMARY_PROBLEM_CLASS:  NULL_CLASS_PTR_DEREFERENCE_FILL_PATTERN_ffffffff

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_DEREFERENCE_FILL_PATTERN_ffffffff

LAST_CONTROL_TRANSFER:  from 6d0f3eca to 6d0f3b0b

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
0e51ed28 6d0f3eca 0e51ed4c 0bdf82b0 00000000 msvcr120!_uncaught_exception+0x595
0e51ed6c 6d0f3f25 6d0f3bec 0e51ee40 00000800 msvcr120!_uncaught_exception+0x954
0e51ed90 6d10e3ea 0e51ee40 00000800 0bdf82b0 msvcr120!vsprintf_s_l+0x32
0e51edac 01407038 0e51ee40 00000800 0bdf82b0 msvcr120!vsprintf_s+0x16
0e51edc4 01766674 0e51ee40 0bdf82b0 0e51ee10 oregon_core!operator<<+0x178
0e51edcc 0bdf82b0 0e51ee10 0e51ee10 00000004 oregon_core!AddSC_terokkar_forest+0x184
0e51f650 014cfe5a 1af444a8 1594f128 0e51f68c 0xbdf82b0
0e51f660 015069fd 1af444a8 1594f128 1af444a8 oregon_core!CreatureEventAIMgr::LoadCreatureEventAI_Scripts+0x14ea
0e51f68c 0150701a 0094f128 00000093 0000002c oregon_core!Cell::VisitCircleOregon::UnitListSearcher<Oregon::AnyUnfriendlyUnitInObjectRangeCheck,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >+0x1ed
0e51f704 01503334 0e51f720 00000001 1af444a8 oregon_core!Cell::VisitCircleOregon::AIRelocationNotifier,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull > > > > >+0x4a
0e51f75c 01443738 1594f128 00000001 00000000 oregon_core!ArenaTeam::LoadMembersFromDB+0x104
0e51f788 014e08a7 0000006d cd5710b0 08764d48 oregon_core!Player::SendQuestReward+0x178
0e51f7d4 014e283f 23a75e28 23a75e18 0163e209 oregon_core!VisitorHelper<ResetNotifier,Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > >+0x17
0e51f804 6cba3333 08764d48 dea99d87 0cf5a8a0 oregon_core!InstanceMap::AddToMap+0xdf
0e51f83c 6cba326e dea99ddb 00000000 0d010278 ace+0x83333
0e51f860 6d10c01d 0cf5a8a0 dea99d0e 00000000 ace+0x8326e
0e51f898 6d10c001 00000000 0e51f8b0 76b133aa msvcr120!_get_flsindex+0x6f
0e51f8a4 76b133aa 0d00feb0 0e51f8f0 77b09f72 msvcr120!_get_flsindex+0x53
0e51f8b0 77b09f72 0d00feb0 6a257638 00000000 kernel32+0x133aa
0e51f8f0 77b09f45 6d10bfb4 0d00feb0 ffffffff ntdll+0x39f72
0e51f908 00000000 6d10bfb4 0d00feb0 00000000 ntdll+0x39f45

STACK_COMMAND:  ~5s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  msvcr120!_uncaught_exception+595

FOLLOWUP_NAME:  MachineOwner

IMAGE_NAME:  msvcr120.dll

BUCKET_ID:  WRONG_SYMBOLS

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_DEREFERENCE_FILL_PATTERN_ffffffff_c0000005_msvcr120.dll!_uncaught_exception

**Comment by Zaffy** [comment]
Crashes at startup?

**Comment by zhy9934** [comment]
no ,in running process
