### ISSUE TITLE
Unexpected Water Behaviour

### ISSUE THREAD

**Issue by adeutscher** [OregonCore/OregonCore#1334]
**Revision**:  57440cb

**Operating system**: Linux

**Current behavior**: 
Unexpectedly drowning when near some puddles of water (see example below).

**Expected behavior**: 
Being in/near puddles should not cause drowning.

**Steps to reproduce the problem**:

I encountered this problem in the orange area of Maraudon (just outside of the instance). When standing near the puddles, my Breath bar would appear.

Example screenshot:
![selection_009](https://cloud.githubusercontent.com/assets/2055500/14038646/f5a0fbc4-f210-11e5-8f98-ae205000df5e.png)

**Comment by kotishe** [comment]
Confirm, also if you just jump in water without go in deep activate "Breath" too

**Comment by adeutscher** [comment]
Did a bit more poking about. Unexpected underwater behaviour going both ways, it turns out. Could I confirm with someone the following points? I'm hoping that every problem point will involve the same area to fix.

Kotishe, could I get a screenshot of the place where you were getting an unexpected breath bar?

Able to drown (expected):
- Stormwind Canal
- Slave Pens Pools
- Underbog Pools
- Coilfang Reservoir (by meeting stone)

Able to drown (unexpected):
- Maraudon Puddles (see above screenshot)

Not able to drown (expected):
- Blackfathom Deeps, puddles outside instance.
- Slave Pens puddles
- Zangarmarsh Marsh (no swimming)
- Theramore Marsh

Not able to drown (unexpected):
- Ghostlands shore
- Zangarmarsh Lake (by Twin Spire Ruins, 
- Azuremyst Island Shores
- GM Island
- Dustwallow Marsh Ocean
- Wetlands Ocean'
- Loch Modan
- Blackrock Mountain Lava
- Northshire Valley
- Hyjal Raid (Nordrassil)
- Deadmines (Ironclad Cove)
- Westfall/Duskwood River
- Sunken Temple outdoors ("The Broken Hall", X/Y/Z: -10346/3851/-42)

**Comment by adeutscher** [comment]
When I run the `.gps` command, I'm unable to get liquid data for each of the problem areas that I've double-checked so far. Liquid data is stored in maps, so could this be a problem with the recently applied VMaps update? In my next major session, I'll try to do a build of a year or two ago to try and confirm.

**Comment by LordUsagi** [comment]
It shouldn't be a problem, the recent maps update was to address problems with liquids being magma etc. But as you said, liquid data seems to be failing to extract

**Comment by LordUsagi** [comment]
Map: 1
X: -1432.500 Y: 2648.6621 Z: 76.55
Location for Breathing problems
