### ISSUE TITLE
PathFinding not complete in certain terrain

### ISSUE THREAD

**Issue by ryancheung** [OregonCore/OregonCore#1335]
![ca22333d-b811-4fc8-9b9b-288ccf9445ad](https://cloud.githubusercontent.com/assets/240899/14050308/ec50229e-f2f5-11e5-830b-b6847079ad50.png)

and

![image](https://cloud.githubusercontent.com/assets/240899/14050325/10e15434-f2f6-11e5-8dbf-8be2b198502d.png)

This is tested in ZulGurub.

**Comment by ryancheung** [comment]
![image](https://cloud.githubusercontent.com/assets/240899/14063926/759cad38-f41d-11e5-8ba1-5acdebc81698.png)
On retail, mobs should be able to climb any mountain in any slope.

**Comment by ryancheung** [comment]
@Zaffy I'm using mangoszero. Unfortunately, this also doesn't fix the pathfinding issue after I re-extracted the mmaps. I try to set the max angle to 80 to see if that would gonna work.

**Comment by Zaffy** [comment]
Well I'm worried that you will have to reextract mmaps in order to even test this...

**Comment by LordUsagi** [comment]
This is a bug report for an issue on a mangoszero core?
