### ISSUE TITLE
[Quest] Body of Evidence

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1338]
**Revision**: Latest

**Operating system**: Unix

**Current behavior**:  On using the blanket on the blazing Warmaul pyre doesnt summon the ogres, its now scripted in the latest core revision as i saw, but somehow its not activated..
....

**Expected behavior**: Use blanket 2 ogres will summon and event will start, they will talk and on various waypoints plant the bodies of slain Kil'sorrow soldiers... when they are done you get quest credit.
...

**Steps to reproduce the problem**: take quest go to the location use blanket, you will see that the ogres not spawn so event doesnt start.

It was reported before, but was on old tracker and since its now scripted i think we only miss a trigger to activate the event when you use the blanket on the pyre..
so maybe selphius has an idea, since he scripted it.

**Comment by Selphius** [comment]
No, no I didn't script it, all credits go to @LordUsagi and @PandreWoW
I used his script from warpcore, from what I see the problem may lie with missing script in SpellEffects.cpp  so try it.

Source: https://bitbucket.org/LordUsagi/warpcore/commits/a0fd02e3374c719b58e9efd62b913f471dbbd645

Edit: or maybe not, since it's for quest "Returning the favor". Try then with this DB update since it changes some flags.

**Comment by dikkedeur** [comment]
nop, in that commit it is for another quest.. so i dont think its that, what could be is that the sql was not provided..

UPDATE `creature_template` SET `ScriptName` = 'npc_warmaul_pyre' WHERE `entry` = '18395';
UPDATE `creature_template` SET `dynamicflags` = '32' WHERE entry = '18397';
UPDATE `creature_template` SET `flags_extra` = '2' WHERE entry = '18395';

will try that tomorrow.

**Comment by dikkedeur** [comment]
well above makes it work... there are still some problems, i dont recall in any vid that they are fighting the dead bodies.. they do it right now.. they should only plant it i assume.

and another thing, when the ogres die in progress it will make the server crash but will make a new bug report about that.. since it might be happening to more quests.. dont know for sure.

**Comment by Selphius** [comment]
Try changing their factions of the bodies then to 35 or other friendly faction, so the ogres won't attack them, maybe it will help.

Anyway, I didn't have such cause on my end before my give away of fixes, so this must be caused by some other update or changes done to DB, I assume.

**Comment by LordUsagi** [comment]
Yeah, I asked for these to be tested individually before merge to account for errors like these.

**Comment by dikkedeur** [comment]
correct fix would be in this case...... tadum tadum tadum

```
-- Fix quest Body of Evidence
UPDATE `creature_template` SET `ScriptName` = 'npc_warmaul_pyre' WHERE `entry` = '18395';
UPDATE `creature_template` SET `dynamicflags` = '32' WHERE entry = '18397';
UPDATE `creature_template` SET `flags_extra` = '2' WHERE entry = '18395';

UPDATE  `creature_template_addon` SET  `auras` =  '29266 0 29266 1' WHERE  `creature_template_addon`.`entry` =18397;
```
