### ISSUE TITLE
[CRASH] Creature::ForcedDespawn

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1340]
**Revision**: Latest

**Operating system**: Unix

**Current behavior**:  Core crashes when it wants to despawn a creature even if its already dead or despawned
....

**Expected behavior**:  it should not crash the server
...

**Steps to reproduce the problem**: take quest Body of evidence..
use blanket, 2 ogres spawn.. they will plant bodies, in the meantime ogres in the area will attack the summoned ogres.
if 1 of them die before total quest event is over the event will continue.
at the quest cedit after that it will crash the server since script says to despawn creature..
but when a creature is already despawned due death or whatever it will simply crash the server.

crashdump: http://pastebin.com/E3Yri4Eh or https://gist.github.com/dikkedeur/a61a664ca3da80a879a0f34a7e4bd770

**Comment by LordUsagi** [comment]
Is the corpse already faded in this case or just simply dead?

**Comment by dikkedeur** [comment]
both,

to fix it, just change (_itr)->ForcedDespawn(); to (_itr)->DespawnOrUnsummon();
problem solved 👍
