### ISSUE TITLE
Fearie Fire (Feral)

### ISSUE THREAD

**Issue by rhidenor** [OregonCore/OregonCore#1341]
**Revision**: 3376

**Operating system**: Unix

**Current behavior**: If i spent a point to Fearie Fire (Feral) talent, it is not show in the "Points spent in Feral Combat talents", but the available talent points is decreas by one.
....

**Expected behavior**: Show spent point in talent tree
...

**Steps to reproduce the problem**:  tried many times, the error is repeatable (retalent)

**Comment by rhidenor** [comment]
Working correctly on new created characters.

**Comment by LordUsagi** [comment]
This is fixed? We've got another issue like it too! #1106

**Comment by rhidenor** [comment]
It works before i learn higher ranks of spell. Then the visual bug is here again.

**Comment by dikkedeur** [comment]
it has been broken for some time.
you can spend the point in the talent tree and learn the higher skills, but when you relog you will see in the talent tree its back to '0'

**Comment by dikkedeur** [comment]
you gain in your spellbook the higher rank(s) so its truly only visual, also i had 35 points left after relog and it was set to 0 it was still 35 points, you can't spend then on that talent again, since it has already been learned.
its just visual, and bugged for a long time.

**Comment by LordUsagi** [comment]
Yeah I remember we had a really weird hacky solution for this one too. If I find it I'll post it here.

**Comment by LordUsagi** [comment]
http://pastebin.com/3EJGmYtr

**Comment by dikkedeur** [comment]
lord if thats from your warpcore.. dont bother.. doesnt work... tried it, not to even say it gave compile errors on unix, so we changed it here and there.. maybe thats why it didnt work ^^

**Comment by Desteny** [comment]
this issue exists since TC1 for sure already since 2009.

its like you say, it exists only i higher rank of FF is learned, and its only a visual bug, if you set the skillpoint it works and the point will be decremented, but it will not be shown on the skill tree.

**Comment by Schaka** [comment]
https://bitbucket.org/lukaasm/hellground-wowemu/commits/all?search=faerie

**Comment by Desteny** [comment]
I know that FF worked correctly on HG Core (Link Upon) but be carefully by porting changes, cause some subsystems have chnaged a lot on HG.

But it seems to be a good hint, even if maybe some related changes are missing, but it worth to give it a try

**Comment by Zaffy** [comment]
I figured out on my own why this was happening and have working fix for this but I'm quite unsure about "spell superceding" - because that is causing this bug. So my question is when you shuold see all ranks of spell in spellbook and when not?

**Comment by LordUsagi** [comment]
Attributes based.

**Comment by Zaffy** [comment]
i dont mean show/hide a particular spell in spellbook...

Now some spells like mortal strike, faerie fire (feral).... work like every new rank replaces the old rank in spell book so you can cast only the higher rank. I ask whether all ranks shuold we always visible @ 2.4.3
