### ISSUE TITLE
[Paladin] auras, SoC, blessings are broken in groups

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1344]
**Revision**: Latest

**Operating system**: Unix

**Current behavior**: Refreshing auras dispel other paladin's buff's like (G)BoM/(G)BoW, and also seals! SoC also dispels other paladins auras/blessings.
....

**Expected behavior**: Seals, judgements, and blessings should be 'per paladin'. Aura's should only dispel the same aura of a lower rank. Blessings of the same type cannot stack (Gbom + bom for example).
...

**Steps to reproduce the problem**: Take two paladins. Stick em in a group. Buffs will disappear left and right and you enter/exit each other's aura range. Example of SoC dispelling aura http://imgur.com/a/GkUzS (top: PalyMD has devo aura on, it's applied to me. bottom: I cast SoC, removing the devo aura from me)

**Comment by stanislav01** [comment]
Bug is mostly in buff if u want to bug ur server or crash someones character do this
Take ur paladin buff another paladin with BOM/BOK/BOW then rebuff urself with GBOM/GBOK/GBOW while ur in a group with him and what happens ?

the other paladin 2nd one will no longer be able to cast auras / buff will start to disappear cause gbom overrides bom from other paladins / after that u will notice a character freeze and u will need to relog
after the relog ur server will be rolled back to the time u casted GBOm on the other paladin

**Comment by Baynar** [comment]
Bug is mostly in buff if u want to bug ur server or crash someones character do this
Take ur paladin buff another paladin with BOM/BOK/BOW then rebuff urself with GBOM/GBOK/GBOW while ur in a group with him and what happens ?

the other paladin 2nd one will no longer be able to cast auras / buff will start to disappear cause gbom overrides bom from other paladins / after that u will notice a character freeze and u will need to relog
after the relog ur server will be rolled back to the time u casted GBOm on the other paladin

**Comment by Baynar** [comment]
Please look this up this is a major bug and will cause lots of problems

**Comment by LordUsagi** [comment]
I don't understand this one too much, can you simplify for me please?

**Comment by dikkedeur** [comment]
The bug is that when in a group with 2 paladins, the buffs overwrite eachother, instead of getting the 2 buffs it replaced it..

Take two paladins. Stick em in a group. Buffs will disappear left and right and you enter/exit each other's aura range. Example of SoC dispelling aura http://imgur.com/a/GkUzS (top: PalyMD has devo aura on, it's applied to me. bottom: I cast SoC, removing the devo aura from me)

**Comment by LordUsagi** [comment]
I'll probably need someone to come on my server and show me this one. Feel free to jump in IRC or Teamspeak to see if I'm around

**Comment by Baynar** [comment]
TEST 1: 2 paladins in group use 2 different aura's
cast on one of the paladins any seal and it will replace the other paladins aura, but after the seal is over the aura will return
![image](https://cloud.githubusercontent.com/assets/16941621/15709775/34383e2c-280f-11e6-9098-7e50ffd49034.png)
![image](https://cloud.githubusercontent.com/assets/16941621/15709781/3c6696a2-280f-11e6-99cd-5950fca9d50b.png)

**Comment by Baynar** [comment]
TEST 2: 2 paladins in group or without group
Use BOM rank 2 THEN use BOM rank 1
BOM rank 1 will not override rank 2, but it will still cast itself and cost mana
------> should give error target has a higher rank of that buff

**Comment by Baynar** [comment]
TEST 3: 2 paladins
I buff myself with BOM then another paladin buffs me with BOK and BOK overrides BOM
And many more all around auras, buffs, seals

**Comment by LordUsagi** [comment]
Ah, I missed you in IRC, by 15 minutes. Timezones are going to be hard to adjust to.

**Number 2** is probably related to a separate issue, do all auras misbehave like that?
**Number 3** Why wouldn't someone casting blessing of kings on someone with blessing of might not overwrite it? That's why you had to assign who was getting what buff and who it was casted by.

**Comment by Baynar** [comment]
@LordUsagi I am here if you wanna test these and see what the problems really are check IRC
