### ISSUE TITLE
hash_map deprecated error when trying to compile oregoncore

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1346]
**Revision**:

**Operating system**:
Windows 7 Ultimate 64x

**Current behavior**: 
When trying to compile the core the compiler gives the following errors: 

error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

Error   C1189   #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file D:\MJOC Server\dep\mysqllite\libmysql\get_password.c) libmysql    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h

**Expected behavior**: 
The compiler should not produce any errors and should build successfully.

**Steps to reproduce the problem**:
Follow the guide in your documentation, download both 32x and 64x openSSL and download mariaDB, also use Visual Studio Community 2015 with Update 2 instead of 1.

**Comment by Zaffy** [comment]
I successfully compiled OC with 2015 in near past perhaps I did fix this but didnt commit....
