### ISSUE TITLE
[Compile Error] snprintf conflict

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1347]
**Revision**:
3384 (9b28678)

**Operating system**:
Windows 7 Ultimate 64x
**Current behavior**: 
The following compile error appears when trying to build the new project:
`#error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file D:\MJOC Server\dep\mysqllite\libmysql\errmsg.c)  libmysql    C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h    1927`

**Expected behavior**: 
A compilation that ends with a successful build without any errors.
**Steps to reproduce the problem**:
Try to build the latest revision in Visual Studio 2015 with Update 2.

**Comment by Desteny** [comment]
Disable the Cmake option "USE_MYSQL_SOURCES" then it will compile.
But you must have installed (or copyed) the mysql .dll files

**Comment by Zaffy** [comment]
Yeah bundled mysql is not supported with VS 2015. Install mysql/mariadb headers/libraries and set cmake variables MYSQL_INCLUDE_DIR and MYSQL_LIBRARY.

For example, mine are following:

```
MYSQL_INCLUDE_DIR = C:/Program Files (x86)/MariaDB 10.1/include/mysql
MYSQL_LIBRARY = C:\Program Files (x86)\MariaDB 10.1\lib\libmysql.dll
```

You get the thing... bundled mysql will surely be updated but I can't promise you a deadline. The above method will work for you. Good luck.
