### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by CrawDance** [OregonCore/OregonCore#1348]
Hey There.
a few days ago i compiled a 243 server based on oregoncore.
but i found 2 issues.
first one , when i hit a creature (boss/mob) its HP jumps to 100 , but its not really 100.(video in the link below)
2nd , for example I've an Item which gives me a buff or aura , ( example Nax's staff ) , once I relog , unequiping the item doesn't remove the buff/aura.(video in the link below)

100 hp issue :
https://www.youtube.com/watch?v=BBbheidya5k&feature=youtu.be

buff issue : 
https://youtu.be/hLOJNKGs2ZE

Would be awesome if you guys help me on this way.

p.s : Not gonna change the whole source with a fixed one since ive installed a lot of custom scripts on it.
so please direct me what to change and so.

Sincerely.

**Comment by ghost** [comment]
100 issue is in worldserver conf. search for percentage and disable it

second one remove all aura on logout

**Comment by CrawDance** [comment]
Worldserver.conf  HealthInPercents part was on 1 - blizzlike ( percents )
How ever , it some times shows the NPC health bar in percents and some times in "values"
When it shows the value HP jumps to 100 , When it shows with % hp jumps to 1%.

About the aura , I didn't get you , Sorry ?

**Comment by dikkedeur** [comment]
for aura's type .unaura all
that will remove all aura's

**Comment by CrawDance** [comment]
What about regular players ? :D

**Comment by Phentora** [comment]
About the first issue. Have you tried this with GM off ?

**Comment by CrawDance** [comment]
Not only with GM off , But also with a non gm toon.

**Comment by Zaffy** [comment]
I'm gonna check this out and try to reproduce this, but...
- you should never spawn bosses or scripted npcs outside of instance
- scripts may affect your issue
- using gm on/off with healthinpercent set to 1 causes issues and you usually need to teleport away/back to get creatures reloaded at client since client remembers old values

**Comment by Zaffy** [comment]
The first issue seems to be what I told you.
The second issue is correct and reproducible using relog.

**Comment by CrawDance** [comment]
Ok so , the first issue is now solved, Credit goes to  Blumfield <3
But i didnt get it , 2nd issue aint an issue ? :|

**Comment by Zaffy** [comment]
The second issue is just a visual one. Stats don't stay. But I know how to fix it now.

**Comment by CrawDance** [comment]
How ? :))

**Comment by CrawDance** [comment]
P.s : i just tested , Stats stay as well.

**Comment by Zaffy** [comment]
I will push commit that fixes this but a little of details:
- auras contain information about item that casted them and when the item is unequipped all its auras are gone
- but this item caster info is not stored in db
- after relog there's no information about the item caster and thus the buff doesnt disappear. (all mods ans stats do though)

**Comment by Zaffy** [comment]
They don't. At least not on clean latest core.

**Comment by CrawDance** [comment]
Thanks , I'll work on it!
