### ISSUE TITLE
[quest/item bug]

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1352]
**Revision**: latest

**Operating system**: Unix

**Current behavior**: Attempted to open chest at top of Tiragarde Keep in Durotar with Benedict's Key. System message 'Fizzled' and key removed and quest item not added. Also locks you in loot animation and prevents you looting until relog.
....

**Expected behavior**:  should open the box when you have the key.
...

**Steps to reproduce the problem**: Relogged and killed Benedict again and looted key. Exact same thing happened second time.

**Comment by Sdyess** [comment]
Spell::EffectOpenLock() in Spell.cpp

Fizzle cast result shouldn't really be used here anyway. Someone just needs to set a breakpoint around this method and read the data and see where it's reading it incorrectly. I'll try to find time this week for it.
