### ISSUE TITLE
[Database] Core doesn't start - creature_template structure is wrong

### ISSUE THREAD

**Issue by Izidor** [OregonCore/OregonCore#1356]
I've taken the SQL for the full structure in /sql folder, then i've apply full database of january and apply all SQL update in sql/update/world folder, but the loading still stuck on creature_template.

You need to add this query into you're SQL folder : 

`ALTER TABLE`creature_template`DROP COLUMN`faction_H`;`

**Comment by Zaffy** [comment]
Sorry, it's already there in 2016_01_19_factions.sql. Either you have outdated core or db.
