### ISSUE TITLE
Locale Spanish?

### ISSUE THREAD

**Issue by Aminxhm** [OregonCore/OregonCore#1368]
**Revision**:
55d9bdc
**Operating system**:
Windows
**Current behavior**: 
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:
Locale Spanish?

**Comment by dikkedeur** [comment]
is that a bug??
you must either find it yourself or translate it, its not something that OC is making.

**Comment by Zaffy** [comment]
Unobvious report, please report bugs clearly.
