### ISSUE TITLE
[Instance] Zul'Farrak pyramid event.

### ISSUE THREAD

**Issue by Ackzel** [OregonCore/OregonCore#1378]
**Revision**:
Lastest
**Operating system**:
Windows 7
**Current behavior**: 

The prisoners can be attacked and may target player when using AoE spells, tested Blizzard, Cone of cold, freeze and flamestrike.

**Expected behavior**: 

They should not be hittable by players.

**Steps to reproduce the problem**:

Cast AoE's around them and it will happen.

**Comment by AbraKabastard** [comment]
Resolved
