### ISSUE TITLE
Creature crossover in group movement

### ISSUE THREAD

**Issue by miraco** [OregonCore/OregonCore#1381]
**Revision**: 
8d922d2

**Operating system**:
Windows 10

**Current behavior**: 
When using creature_formation and the leader GUID have an waypoint, creatures shouldnt crossover at the end of the waypoint.
i tired using sql datas from trinitycore with point_1/point_2 but it still didnt worked.

**Expected behavior**: 
We should be able to say, that they dont crossover

**Steps to reproduce the problem**:

**Comment by LordUsagi** [comment]
Do they cross over in TC2? Because we use the exact same code as far as I know for our formations.

**Comment by miraco** [comment]
No they ddon't. 
I know it's the same code, that's why I'm so confused...
I will do some more tests when I am home.

**Comment by LordUsagi** [comment]
Really odd!

**Comment by Meltie2013** [comment]
Hey guys (@LordUsagi, @miraco), I was going through your issues and might be able to shine some light on your issue.
After viewing some code, it appears your code might have some issues, in why you are get this current behavior. Back in 2012, I remember TC updating their Movement Generators, this might be related.

I mark the current  area on your issue. Seems you are missing some code, and want to help out.
https://github.com/OregonCore/OregonCore/blob/master/src/game/HomeMovementGenerator.cpp#L44-L61

```
float x, y, z;
Movement::MoveSplineInit init(owner);

owner.GetHomePosition(x, y, z, ori);

init.SetFacing(ori);
init.MoveTo(x, y, z, true);
init.SetWalk(false);
init.Launch();

arrived = false;
owner.ClearUnitState(UNIT_STATE_ALL_STATE & ~UNIT_STATE_EVADE);
```

You should be able to see where they fixed this issue on this commit: https://github.com/TrinityCore/TrinityCore/commit/97c3e2e6c105e3dd563ba1064e86f5503d3f22f6

**Comment by LordUsagi** [comment]
Hey @Sylica2013,
I appreciate the response, and the research you did!
I think that the code changes by TC are just cleanups. I don't see how exactly it would affect our issue.

**Comment by Meltie2013** [comment]
Hmm. Well as mentioned above, that might be an issue on Reset Position for waypoints.
I have a likely hunch that its this line of code.

```
owner.GetHomePosition(x, y, z, ori);
```

Cause there is no check for reset position, if not crossing over with a waypoint.

Try this and see if it works.

```
if (owner->GetMotionMaster()->empty() 
    || !owner->GetMotionMaster()->top()->GetResetPosition(owner, x, y, z))
{
    owner.GetHomePosition(x, y, z, ori);
    init.SetFacing(ori);
}
init.MoveTo(x, y, z);
```

Just have a feeling that might be it. I'll do some testing on it.

**Comment by miraco** [comment]
I will have some free time tomorrow then I will test it a bit more

**Comment by LordUsagi** [comment]
Tough that we can't use

```
!owner->GetMotionMaster()->top()->GetResetPosition(owner, x, y, z))
```

in our core, but with just 

```
owner->GetMotionMaster()->empty() 
```

it doesn't seem to solve it, atleast in home movement generator. But this is a waypoint isuse isnt it?
Edit: or follow movement? Because they're following right?

**Comment by Meltie2013** [comment]
Either way, best of luck to you guys. I'd do some more research, cause GetMotionMaster() & GetResetPosition() are important functions. If I find a way to completely fix it, I'll send you my PR your way.

**Comment by LordUsagi** [comment]
Sounds great. We definitely appreciate all the help we can get.

**Comment by miraco** [comment]
Okay, i tested it out much more, and its working correctly! Can be closed.

**Comment by LordUsagi** [comment]
What do you mean? With the code change or without?

**Comment by miraco** [comment]
Without :)
