### ISSUE TITLE
[Quest] Rescue the Survivors

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1387]
**Revision**: latest

**Operating system**: unix

**Current behavior**: You need to use spell gift of the naaru on one of the survivors.
problem is that you cast it always on yourself, and not on selected npc so you cant get quest credit
....

**Expected behavior**: gift of the naaru should be cast on selected npc or player, and if no player then on caster.. now its only caster as always
...

**Steps to reproduce the problem**: cast gift of naaru.. it always casts on the caster, not on the selected char.. take quest, use spell..

**Comment by LordUsagi** [comment]
#1294
#1265

**Comment by dikkedeur** [comment]
looks indeed as the same, the nice part is when you have the quest as gm and you do .cast<spellid> then it works, you get quest credit.
but not when you use the spell itself.
