### ISSUE TITLE
[Spell] Charge is ignoring distance when calculated for elevation

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1388]
**Revision**: Latest

**Operating system**: Unix

**Current behavior**:  during leveling in Shadowglen, we went for Webwood Spiders (npc=1986) into a cavern to the north. Cavern has some elevations, like stairs you cannot get on unless you go around. But if a warrior targets a spider, that is ON such elevation and with direct visual distance within "Charge" limits (8-25 yards), then using "Charge" ability will send this warrior all the way around the cavern by spiral towards his target, regardless of actual distance he will run.

....

**Expected behavior**:  "Charge" should not be executed unless full run distance to the target is lesser or equal to 25 yards. Currently success ability use is calculated by direct visual distance.
...

**Steps to reproduce the problem**: target an enemy on elevation and use "Charge" (spell=100). Didn't test it on lower-placed enemies, but suppose it'll also work.

**Comment by Zaffy** [comment]
I don't think this is a bug. On retail servers this works like this, too.
