### ISSUE TITLE
[Spell] Invisibility and Stealth Detection doesn't add icon over creatures head.

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1391]
http://www.wowhead.com/spell=18950/invisibility-and-stealth-detection

**Revision**:
c0c524c7727012fbde2c2f138bc6664cb1613d1d

**Current behavior**: 
When applied to a creature's addon template, the spell does not appear to function at all. I can get more-or-less ontop of a mob of equal level and not be detected with stealth, even if they have this aura. Additionally the "eye" icon above them is missing when stealthed..

**Expected behavior**: 
Aura should increase stealth detection, and add an eye aura over the creature that is only visible when a player is stealthed.

**Steps to reproduce the problem**:
I believe entry 17280 has the aura in its creature_addon_template (Shatter Hand warhound in Ramparts). Use stealth by it.

**Comment by nairyo** [comment]
```
void Aura::HandleModStealthDetect(bool apply, bool Real)
Aura::HandleModInvisibilityDetect(bool apply, bool Real)
WorldObject::CanDetectInvisibilityOf(WorldObject const* obj)
WorldObject::CanDetectStealthOf(WorldObject const* obj, bool checkAlert)
```

Somewhere along these lines, I'll check when I can

**Comment by r00ty-tc** [comment]
It's specifically here https://github.com/OregonCore/OregonCore/blob/master/src/game/Object.cpp#L1772

``` C++
        if (unit && unit->HasAuraTypeWithMiscvalue(SPELL_AURA_DETECT_STEALTH, i))
            return true;
```

The code is present and works. However the icon doesn't appear. You can do it on any creature. Stealth up, stand quite close (make sure they're the same level or close) but not enough to get aggro. Then add aura 18950 to the creature and you'll gain aggro (you may need to move to update).

The blue circle icon was definitely there in 2.4.3. However, I can't see why it doesn't appear here. TC on 3.3.5 shows it fine for this aura and I can't see what would be different between the two here.

EDIT: My only thinking here is that the auras for 18950 aren't being applied correctly. I see 1 aura and 2 effects (invisible and stealth detection on 3.3.5). On here I see 2 listed. Maybe it's a problem there.

**Comment by nairyo** [comment]
@r00ty-tc wut ? can you re-explain your edit :) ?

**Comment by PadreWoW** [comment]
Should be like this:
![stealth_imunity](https://cloud.githubusercontent.com/assets/6802530/15281912/21e06bd8-1b48-11e6-910f-56f6d52e31dc.jpg)

**Comment by nairyo** [comment]
@PadreWoW what's this aura id (visual) ?

**Comment by ghost** [comment]
18950 (Or that least that is the aura always used on TC and Mangos.)

**Comment by r00ty-tc** [comment]
@nairyo 

What I meant was that when I tested on TC/3.3.5 it lists the auras differently and seems to work Looking at the code I can't see anything significant. So I can only think that the presence of the aura in unit update (assuming that is sent) is the problem, or perhaps part of the problem.

Although Auras seem to be handled somewhat differently, not sure if it's a difference with TC itself, or the aura handling between 2.4.3 and 3.3.5.

@Saben65 I tried a cursory .lookup spell detect and tried them all. None added the graphic effect for me.

**Comment by r00ty-tc** [comment]
So my investigation before/after work resulted in the following:
- Auras seem to be handled quite differently in 2.4.3 vs 3.3.5.
- I've not checked stock cmangos/mangos actually running. But I did test a server based on cmangos and it works there (eye above appears). I sniffed the data and... Here it gets weird. I found a snippet with the aura ID attached to the creature(s) that have the aura and the eye.. But it makes no sense AT ALL.

```
[0] OBJECT_FIELD_TYPE: 131328/1.840297E-40
[0] OBJECT_FIELD_ENTRY: 18950/2.655461E-41
[0] OBJECT_FIELD_SCALE_X: 31/4.344025E-44
```
- I cannot find any code specifically in any of the repos dealing with this issue. So either they just do auras differently (more correct) or there's more to this than meets the eye.

Beyond that, my expertise doesn't lie so much in protocol reversing so, not much more I can add.

**Comment by ghost** [comment]
I was scouring the different cores trying to come up with a commit or issue that discussed this as well. I couldn't find anything either.

**Comment by LordUsagi** [comment]
I was under the impression this was working in our core a while ago.

**Comment by LordUsagi** [comment]
Other icons such as Tags and molten armor works

**Comment by r00ty-tc** [comment]
That's the spell effect from the actual spell though. You can see the difference. .cast 30482 and you'll see the anim. .aura 30482 and you gain the buff without the anim.

For the stealth detection there is no spell effect and the eye graphic appears all the time, only to players in stealth.

**Comment by miraco** [comment]
Maybe its cause in TC2 the Creature also casts this spell via SmartAI?
`REPLACE INTO`smart_scripts`VALUES ('17280', '0', '0', '0', '25', '0', '100', '1', '0', '0', '0', '0', '11', '18950', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Shattered Hand Warhound - On Respawn - Cast \'Invisibility and Stealth Detection\'');`

This ist from smart_scripts in TC2.

**Comment by Kall-DestinyAwaits** [comment]
In Player.h  
PLAYER_FIELD_BYTE2_STEALTH           = 0x20,
change to
PLAYER_FIELD_BYTE2_STEALTH           = 0x2000,

and its working :)
