### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1392]
**Revision**:
Latest.... and also the revision is bugged too showing revision 0 and hash unknown
**Operating system**:
Windows 10
**Current behavior**: 
....When you attack a monster with a normal attack (right-click) while your normal attack is on cooldown u enter combat before hitting the monster

**Expected behavior**: 
...you should enter combat on hitting

**Steps to reproduce the problem**:
get a slow weapon and attack something to get your normal attack on CD then attack a monster while your normal attack is on cooldown and you will see that you will enter combat and get hitted by the monster before even hitting it

**Comment by LordUsagi** [comment]
Got any ideas on a slow weapon?

**Comment by Baynar** [comment]
Any weapon with 3+ speed
http://www.wowhead.com/item=32348/soul-cleaver

gif how i reproduce it
also tested on other mobs its the same
http://imgur.com/ls5JS2P

**Comment by LordUsagi** [comment]
Can absolutely confirm. This bug also exists in TC.
