### ISSUE TITLE
VS 2015 Mysql Sources Compile Error

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1394]
**Revision**:
3447
**Operating system**:
Windows 10
**Current behavior**: 
....Getting error when compiling with VS 2015
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file E:\CoreGit\OregonCore\dep\mysqllite\dbug\dbug.c)

On 2012 only cause its c++11 i think
2>  CinematicMgr.cpp
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(31): error C2059: syntax error : '{'
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(31): error C2143: syntax error : missing ';' before '{'
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(31): error C2143: syntax error : missing ';' before '}'
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(57): error C2601: 'pos' : local function definitions are illegal
2>          E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(56): this line contains a '{' which has not yet been matched
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(57): error C2143: syntax error : missing ';' before '}'
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(58): error C2065: 'pos' : undeclared identifier
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(58): error C2228: left of '.IsPositionValid' must have class/struct/union
2>          type is ''unknown-type''
2>E:\CoreGit\OregonCore\src\game\CinematicMgr.cpp(61): fatal error C1903: unable to recover from previous error(s); stopping compilation
2>
2>Build FAILED.

**Expected behavior**: 
...no error

**Steps to reproduce the problem**:
compile with vs 2015 and 2012

**Comment by LordUsagi** [comment]
For 2015, what happens if you compile using your own mysql sources? It' an option in cmake, just untick it!

**Comment by Baynar** [comment]
No errors without it
========== Build: 17 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Update:
========== Build: 23 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
with tools but no mysql sources

**Comment by LordUsagi** [comment]
Beautiful.

**Comment by LordUsagi** [comment]
We no longer support Visual Studio 2012. It lacks C++11 support. I'm currently using 2013 to compile fine. If you're using VS 2015, please see #1347 in regards to the MYSQL sources situation.
