### ISSUE TITLE
Problem with Cyrillic in Console

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1395]
**Revision**:
3449+ (last)
**Operating system**:
Win Server 2008R2
**Current behavior**: 
All Cyrillic text become lines in OC Console

**Expected behavior**: 
...

**Steps to reproduce the problem**:

![untitled](https://cloud.githubusercontent.com/assets/6802530/15429108/ca6f14ea-1ea7-11e6-9f14-4514217339b7.png)

**Comment by Zaffy** [comment]
Is this only on OC? This could be font issue - missing chars

**Comment by PadreWoW** [comment]
Sorry - problem was in my OS

Thanks
