### ISSUE TITLE
Warnings in CMAKE v3.5.2 (CMP0043 and CMP0054)

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1396]
**Revision**:
last
**Operating system**:
WIn Serv 2008 R2
**Current behavior**: 
There is a problem (warnings) in CMAKE v3.5.2
Warnings with CMP0043 and CMP0054

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
This problem can be solved by this:

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.1")
  cmake_policy(SET CMP0054 NEW)
endif()

if(POLICY CMP0043)
   cmake_policy(SET CMP0043 OLD)
endif()

**Comment by Regolan** [comment]
Rev.: 3451 (3f636a8)
Op. System: Win10 64bit

The CMake still has an error...

![oregoncore_cmake_error](https://cloud.githubusercontent.com/assets/2421503/15477616/cf1a3270-2115-11e6-9af0-c060d8a4814c.png)

**Comment by PadreWoW** [comment]
Look at paths :) and add these fixes to the appropriate files

**Comment by LordUsagi** [comment]
@Zaffy :)

**Comment by zgn1988** [comment]
Fixed

https://github.com/OregonCore/OregonCore/commit/59ce2a634b887142fe1e2fe16382f4cefa86bf12
