### ISSUE TITLE
Corpses don't become bones after resurrection

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1398]
**Revision**:
last
**Operating system**:
Win Serv 2008 R2
**Current behavior**: 
Corpses don't become bones after resurrection
- 
  Resurrection can not occur immediately - only after 2-3 clicks

**Expected behavior**: 
...

**Steps to reproduce the problem**:

Take non gm char and kill him, then try to resurrect near the corpse.
![untitled](https://cloud.githubusercontent.com/assets/6802530/15540363/9226d5a0-228f-11e6-8e65-47dec3417bca.png)

**Comment by PadreWoW** [comment]
p.s you can see bones only after logout !

**Comment by Baynar** [comment]
Can confirm.
