### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1399]
**Revision**:
3470
**Operating system**:
Windows 10
**Current behavior**: 
....I made a clean database for a test server and i get 
Error in creature_template, probably sql file form
at was updated (There should be 72 fields in sql).

**Expected behavior**: 
...no error

**Steps to reproduce the problem**:
get the core rev 3470 and create a clean database and u will get the error

**Comment by LordUsagi** [comment]
You must be missing an update. Can you show us the structure of your table

**Comment by Baynar** [comment]
http://pastebin.com/rAz88d9z

I hope this is what u meant
Database is clean auto-update is on but updates are missing

**Comment by LordUsagi** [comment]
Wonder if auto update didn't run because your structure is wrong.
For example, faction_A and faction_H was replaced to just faction etc.

What does your versions table say?

**Comment by Baynar** [comment]
There is none

i did a clean install on database a few days ago and had no problems but idk what is happening
EDIT: i see that many updates are not downloaded from git for some reason will re-pull soruce and check if that helps

**Comment by LordUsagi** [comment]
Sounds good. I am **not** 100% but I think that the way versions is setup currently is that you may have to **create it yourself**.. although you shouldn't.

If you're a bit unsure, you should check out our wiki regarding setting up the databases and definitely don't forget the link below:
**https://github.com/OregonCore/OregonCore/releases**

Edit: If my first point is correct, feel free to let me know and I'll **fix** it.

**Comment by Baynar** [comment]
Ok i pulled a new source with all files then compiled the core and droped the database and did everything all over i get no more errors and everything is updated but
OregonCore.exe stops loading on ReservedNames and doesn't load the core

EDIT: i also still don't have a versions table in any of the databases
EDIT: here is the server log http://pastebin.com/qmrV8nLc
just stoppes and nothing happens
EDIT: my other cores are running ok even with the new updates in the database but on older revision
EDIT: ok i disabled console and core loaded but still no versions folder

It might be a good idea to put in the docs FAQ: that u need to check if u have all updates in updates folder if getting some sql error and disable console if core loading hungs up

**Comment by LordUsagi** [comment]
its not a verions folder, its a versions _table_ located in your **world** database

Edit: and I am an **idiot**. It's called "**updates**"

**Comment by LordUsagi** [comment]
Linked to #1389 now

**Comment by Baynar** [comment]
Yes i have updates lol XD but still idk why its hanging up on ReservedNames

### this can be closed but better update docs so people know what to do if they encounter this problem

otherwise they will have to sumbit buggs and post on forum when they can check docs and see if its pointed out there

**Comment by LordUsagi** [comment]
I don't understand **what** exactly needs to be added to docs? There's no way your updates folder wouldn't pull all the necessary updates unless you were doing something wrong.

**Comment by Baynar** [comment]
Well this can encounter if your doing stuff with alot of cores and have custom update folders

Also the most common thing people get stuck on are DB errors and core freezing
Maybe make a section of commonly encountered problems or something

EDIT: i meantioned adding something to docs cause oregon docs are empty.........
i had to use trinitycore docs in order to learn common things in the database or functions in the code

**Comment by Baynar** [comment]
Troubleshooting
Error in Example_Table, probably sql file form at was updated (There should be X fields in sql).
Go in oregoncore/sql/updates and check if you have all the nessecery updates

Core froze on loading
Check for errors in XXXXXX or disable Console.Enabled = 0

these 2 lines can save many people the trouble of searching for a solution themselves or wait for a simple response

**Comment by kotishe** [comment]
I am write about make custom changes add to revision nomber + like 3434+ and dont may update int field in db, maybe this also broke autoupdate?
