### ISSUE TITLE
Cinematics

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1400]
**Revision**:
3472
**Operating system**:
Windows 10
**Current behavior**: 
....Even if you disable cinematics they will still run on character creation
while that is present as it is running if you die or some event accures you get your UI and fly arond with the cinematic

**Expected behavior**: 
...You should be able to disable cinematics

**Steps to reproduce the problem**:
Disable Cinematics from config and create a new character

**Comment by PadreWoW** [comment]
+1 confirmed

**Comment by LordUsagi** [comment]
This new with the latest cinematic changes or an old bug?

**Comment by Baynar** [comment]
New

**Comment by LordUsagi** [comment]
This seems invalid. What are your config values for 

```
SkipCinematics = 0
```

**Comment by LordUsagi** [comment]
Invalid. SkipCinematics should be 2 to skip all cinematics. 1 skips racial cinematics on second creation of race.
