### ISSUE TITLE
[Spell] Stealth and Pick pocket

### ISSUE THREAD

**Issue by dikkedeur** [OregonCore/OregonCore#1401]
**Revision**: Latest

**Operating system**: unix

**Current behavior**: When you are in stealth and are form behind, npc's often still sees you from a distance and agro you, while it should not be the case as far as i know.
This makes Pick pocket also a pain in the well known place, since you need to be stealthed to pick pocket humanoids..
This happens with npcs that are the same or even lower level then you ( i know when a npc is 10 levesl higher you will always be detected as far as my memory is correct )
....

**Expected behavior**: While in stealth, npcs that you sneak upon from behind should not detect you.. when you are same level or when you are even higher level then the npc.
...

**Steps to reproduce the problem**: Make rogue, learn stealth and pick pocket and sneak a humanoid for example, he WILL see you and agro you.

**Comment by LordUsagi** [comment]
I can't reproduce this one at all.
