### ISSUE TITLE
Problem with Hunter Pet in Arena

### ISSUE THREAD

**Issue by Kaloy007** [OregonCore/OregonCore#1402]
**Revision**:
lattest
**Operating system**:
windows server 2008
**Current behavior**: 
When a hunter mount up in 1v1,2v2,5v5 Arena his pet should be hidden/dismissed/disappear. Also pet Follow is not activated when you entered the arena.
**Expected behavior**: 
When player is mounted his pet should be invisible for everyone. And Pet Follow should be activated always until player cancel it.
**Steps to reproduce the problem**:
I dont know

**Comment by LordUsagi** [comment]
Any evidence on this one? I can't find anything.
