### ISSUE TITLE
[crash] 80000003 BREAKPOINT

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1405]
**Revision**:
lastest
**Operating system**:
Windows Server 2008 R2 Server 4.0, Enterprise Edition Service Pack 1
**Current behavior**: 
crash

**Expected behavior**: 
no crash

**Steps to reproduce the problem**:
possible related with grid system ?

 crashlog :https://gist.github.com/zhy9934/98ad15c900ef0669e898e738497eb401
                  https://gist.github.com/zhy9934/a7eb837d824eea0100f494c8310e22b8
                  https://gist.github.com/zhy9934/b7852abdc3389db8829b5ce689b737e2

**Comment by Desteny** [comment]
crash is in "mysql_ssl_set" F:\WOW243-304debug\libmysql.dll is no grid problem.

maybe a mysql server problem or a problem with your mysql lib

**Comment by Zaffy** [comment]
@Desteny Actually it's not a crash but abnormal termination - see the abort() call. Mysql for some reason sets a signal handler for this SIGABRT signal and hard-stops the program the same way as a debugger would on a breakpoint.
