### ISSUE TITLE
Become a ghost when logout in the combat

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1406]
**Revision**:
Latest
**Operating system**:
win7
**Current behavior**: 
when i logout in the combat , then i login next ,i can become a ghost.

**Expected behavior**: 
should alive

**Steps to reproduce the problem**:
in LogoutPlayer() of WorldSession.cpp, the line 346:   else if (!_player->getAttackers().empty())   to 
else if (!_player->getAttackers().empty()&& _player->InBattleground())

the problem is resolved but I don't know whether this change can cause crash?

**Comment by PadreWoW** [comment]
you SHOULD be a ghost when logout in combat

if you logout in combat you die (offlike!)

**Comment by zhy9934** [comment]
the level of my character is 70 ,and the level of mob is 10.  In this combat, I should not die when I logout,
but I become a ghost when i login next time.

**Comment by PadreWoW** [comment]
Create character on official server and check - you'll be surprised :)

**Comment by dikkedeur** [comment]
trust me, when in combat and you logout or close your client, then you are just fucked.. you will die..
this is blizzlike and is always been the case, otherwise you can just kill client when you are almost dead to loos agro and login back..

so not a bug!

**Comment by zhy9934** [comment]
OK, I know.  Thanks
