### ISSUE TITLE
Error smsg on spell overrite missing

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1407]
**Revision**:
3491
**Operating system**:
Windows 10
**Current behavior**: 
....When u cast low rank buff on a target with the same buff but, with higher rank you cast ur spell but do not overrite

**Expected behavior**: 
...Should give smsg Player already has a higher rank of that spell

**Steps to reproduce the problem**:
cast bom rank 8 on urself then another player casts rank 7 or below

**Comment by LordUsagi** [comment]
Confirmed. Can reproduce with BoM and Power Word: Fortitude.

**Comment by Zaffy** [comment]
I got this worked but before I push a fix for this I need to know:
- if i cast a rank 2 on unit and then rank 1 it will pop up error message -- is it correct? - so there's no "another" player involved?
- also - what about GBoM and similar spells? Should it just skip the players that have higher ranks already on them or?

**Comment by LordUsagi** [comment]
If I cast Rank 3 Power Word: Fortitude, and someone else tries to cast rank 1 on me. It will fail and say, there's a more powerful spell already and won't charge me mana or a cooldown.

I believe if the player has rank 3 power word fortitude from ANOTHER caster, and tries to override it with his own Power Word: Fortitude rank 1, it will work fine.
