### ISSUE TITLE
Mage's FROSTBITE can hit allies

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1408]
**Revision**:
last
**Operating system**:
WinServ2008R2
**Current behavior**: 
When the opponent receives damage from frostbite and ally is near, ally takes damage from frostbite and begins to beat player

**Expected behavior**: 
Frostbite should not hit allies

**Steps to reproduce the problem**:

**Comment by LordUsagi** [comment]
damage from frostbite?

**Comment by PadreWoW** [comment]
Frostbite hits every npc around you - even allies and they begin to beat player (guards, escort npcs etc) - you can check it by escorting The Defias Traitor in Westfall with Mage

**Comment by LordUsagi** [comment]
Yeah but those mages have a frost armour on them which applies chilled. I don't think it's related to Frostbite but maybe Call for help. I'm looking into this tonight.

Edit: definitely frostbite! lol nice catch.. not sure what's going on here

**Comment by PadreWoW** [comment]
Not fixed

AOE spells can hit allies and they start to attack player instead of enemies
