### ISSUE TITLE
The judgment of joining Instance Error (when instance is progress)

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1409]
**Revision**:
lastest
**Operating system**:
win7
**Current behavior**: 
the instance is inprogress, when we want to join in the instance , we can be teleported to homebind or error map.

**Expected behavior**: 
In this situation, we should  stay the gate of instance and give a tip . should not teleport to homebind.

**Steps to reproduce the problem**:
In player.cpp ,the fuction< teleport to() > ,the CanEntry() called the Map::CanEntry(), that always return true。however，this should call Instance::CanEntry().

**Comment by LordUsagi** [comment]
I don't understand

**Comment by LordUsagi** [comment]
What error should it return? In which situation should it return an error and which should it return you to home bind? Do you have any screenshots from retail or somewhere else where this feature is working?

**Comment by zhy9934** [comment]
sorry!
If my grouper is in instance, then they are combating with the Boss,  now, i want to enter the instance, i can be teleport to homebind.

however, the Expected behavior is : only warn "don't entry the instance"   not teleport

understand？my english is poor ,sorry :)

**Comment by LordUsagi** [comment]
Yes I understand. Can you provide blizzlike evidence?

**Comment by LordUsagi** [comment]
I don't think this existed in TBC.
