### ISSUE TITLE
Bug with lockboxes

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1410]
**Revision**:
Last
**Operating system**:
Winserv2008R2
**Current behavior**: 
Lockboxes are not marked as LOCKED
When you try to open it, you see "Item is locked" on screen, but then you can not open any loot from any npc until logout

**Expected behavior**: 
Lockboxes should be marked as locked
![untitled](https://cloud.githubusercontent.com/assets/6802530/15798439/7754c07a-2a41-11e6-8965-f5202b1e61e3.png)

**Steps to reproduce the problem**:
Try to open any lockbox in your inventory and then try to loot any npc

**Comment by LordUsagi** [comment]
Confirmed. This is odd because if you  `.lookup item iron lockbox` it shows "Locked." but it's not until it gets into your inventory that it becomes glitched.

**Comment by dikkedeur** [comment]
this can maybe also be due the change of item being in a bag.. not sure.. that it changes something

**Comment by LordUsagi** [comment]
That's what I'm thinking.
