### ISSUE TITLE
Auto attacks can hit even allies and NON_ATTACKABLE mobs

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1421]
**Revision**:
last
**Operating system**:
winserv2008R2
**Current behavior**: 
If mob can change faction, you can hit him even his faction changed to ally or mob changed his flag to NON_ATTACKABLE

**Expected behavior**: 
Auto attack should stop when npc changes his faction to ally, or changes his flag to NON_ATTACKABLE or there is command "CombatStop" in code

**Steps to reproduce the problem**:
Try to complete last quest in "The Missing Diplomat" chain, (defeat Private Hendel) by auto-attack (warrior for example) and when npc will change his faction, you will continue hit him by auto attack

**Comment by LordUsagi** [comment]
When this was originally submitted, you had included "What Book? I don't see any book!", why was that removed?

**Comment by PadreWoW** [comment]
there is one method to evade this bug - Done = false; Done = true;
without this check all your commands "NON_ATTACKABLE", "CombatStop", "setFaction" are useless

**Comment by LordUsagi** [comment]
Whats the quest ID for the quest where you attack Private Hendel?

**Comment by PadreWoW** [comment]
1324

**Comment by LordUsagi** [comment]
Thanks. Looks like Private Hendels script doesn't call for NON_ATTACKABLE flag. He just switches factions.

**Comment by LordUsagi** [comment]
I can't talk to Private Hendrel even with that quest.

**Comment by PadreWoW** [comment]
You should complete previous quest before

NON_ATTACKABLE was my idea to fix this problem

**Comment by LordUsagi** [comment]
But according to your issue report, it wouldn't solve the problem.

"If mob can change faction, you can hit him even his faction changed to ally or mob changed his flag to NON_ATTACKABLE"

**Comment by PadreWoW** [comment]
yep

**Comment by LordUsagi** [comment]
which is wrong, because it works perfectly fine in **What Book? I Don't see any book!**

I think that evade needs to be called for creature instead of just switching faction.
