### ISSUE TITLE
Spell Class Bug For paladin

### ISSUE THREAD

**Issue by ljwlaji** [OregonCore/OregonCore#1427]
**Revision**:
newest
**Operating system**:
win
**Current behavior**: 
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:
if 2 paladin in a same team the paladinB's buff will disapear when paladinA use a spell

**Comment by LordUsagi** [comment]
This is fixed long ago.

**Comment by LordUsagi** [comment]
See aa4982c8720a1ac41fd7097b305f98cc6c63d8d4 and 9a4422d6a63d3fd901eba2a1b01f63eabf3c84ac

**Comment by Baynar** [comment]
I am on the latest core and its working correctly

**Comment by Baynar** [comment]
Just tested it with my friend everything works.
Are you sure you have all updates ?

**Comment by ljwlaji** [comment]
thank you
