### ISSUE TITLE
Grounding totem

### ISSUE THREAD

**Issue by WaCzup** [OregonCore/OregonCore#1428]
**Revision**:3210+

**Operating system**: win

**Current behavior**: 
E.g. mage start casting spell, then enemy cast GT and mage will cast **1fireball to GT and 1fireball to shaman** at the same time

**Expected behavior**: 
Mage start casting spell, GT casted and mage **will cast 1bolt to GT**

**Steps to reproduce the problem**:

Enemy start casting some spell (e.g. fireball), then shaman cast GT and enemy will end casting.

![gt](https://cloud.githubusercontent.com/assets/19874742/15985637/96aaa1c0-2ff4-11e6-892c-a9e54baffb22.jpg)

**Comment by Baynar** [comment]
Can confirm

**Comment by LordUsagi** [comment]
#924

**Comment by LordUsagi** [comment]
No, we think expected behaviour should be 
```
Mage start casting spell, GT casted and mage will cast 1bolt to **SHAMAN**
```
