### ISSUE TITLE
LOOT BUG

### ISSUE THREAD

**Issue by ljwlaji** [OregonCore/OregonCore#1429]
**Revision**:
unknow yet...
**Operating system**:

**Current behavior**: 
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:
in a raid group , leader pickup the monster's body ,then cancel ,and pick it again,
the loot will disapear. don't know why....

**Comment by LordUsagi** [comment]
The last issue reported by you had been resolved. Please provide your revision number and relevent information otherwise this issue will be closed.
