### ISSUE TITLE
Vmaps Crash With Old Revision

### ISSUE THREAD

**Issue by aeashy** [OregonCore/OregonCore#1430]
**Revision**:
[d636419]
**Operating system**:
server 2008 r2
**Current behavior**: 
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:
The Crash is Too big To update.
So I Update it on forums.
See https://forums.oregon-core.net/viewtopic.php?pid=2743#p2743
I will Delete it By Myself Later. 
If anyone fixd it , Plz. Give The issus Number. That Will be very Helpful To me ^^

**Comment by LordUsagi** [comment]
I don't think these are specifically related to VMAPS. Two of them atleast look like they're related to Prince Malchezar. Although, we've had a plethora of crash fixes come up on our commit list recently as well as updating maps, vmaps and mmaps too.
