### ISSUE TITLE
@LordUsagi

### ISSUE THREAD

**Issue by Schaka** [OregonCore/OregonCore#1431]
@LordUsagi use rebase, when you pull changes from remote (git pull --rebase).
That way, you don't create a merge commit between your local and the remote respository everytime you make changes while someone else has also made changes.

It keeps the commit history much cleaner and easier to pay attention to!

**Comment by Lumber-Jack-2** [comment]
if you use git extentions, you can also set (git rebase) automatically if you push commits :)

**Comment by LordUsagi** [comment]
I actually use githubs new UI but I do have extensions installed. I'll try
it out. Thanks.
