### ISSUE TITLE
Flare

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1434]
**Revision**:
3520
**Operating system**:
Windows 10
**Current behavior**: 
....When a hunter casts Flare on MAX RANGE the AOE spell effect is instantly applied on the ground

**Expected behavior**: 
...AOE effect should be apllied when the animation gets there

**Steps to reproduce the problem**:
Use flare on a stealted enemy or player

Correct me if i am wrong i just remember this spell working like this.

**Comment by Zaffy** [comment]
I'm not sure but i would go with instant effect but perhaps @desteny or @lordusagi can help here.

**Comment by robinsch** [comment]
Flare should be applied instantly. You can check Cherez Hunter Druid Video for it, there are multiple scenes where Flare is applied instantly on larger range.

**Comment by LordUsagi** [comment]
Invalid. Thanks @Zaffy & @robinsch
