### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by WaCzup** [OregonCore/OregonCore#1435]
**Revision**: 3210+

**Operating system**: win

**Current behavior**: 
Concesration (ID: 27173 and lowers rank) don't give periodic damage

**Expected behavior**: 
Consecration (ID: 27173 and lowers ranks) should give periodic damage when someone stay in the aoe

**Steps to reproduce the problem**:
Cast consecration (ID: 27173 and lowers ranks) under enemy 
![wowscrnshot_061816_210734](https://cloud.githubusercontent.com/assets/19874742/16173158/c06781aa-3598-11e6-992a-bdc91de3b895.jpg)

**Comment by Zaffy** [comment]
Quite old revision try to update core and then come back.

**Comment by WaCzup** [comment]
I don't have time now for compile to newest rev, so if someone can confirm please.. it would take like 1-2days for me ^^

**Comment by LordUsagi** [comment]
It works
