### ISSUE TITLE
Mana Tap (28734) should not hit mobs if they have no mana

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1438]
**Revision**:
last
**Operating system**:
winserv2008r2
**Current behavior**: 
You can hit any mob with Mana Tap and take Arcane energy (stack 3 times)

**Expected behavior**: 
Mana Tap (28734) should not hit mobs if they have no mana

**Steps to reproduce the problem**:

**Comment by AbraKabastard** [comment]
It's because ALL mobs by default have power type = mana

**Comment by PadreWoW** [comment]
Fix:

Fix Mana tap

in Spell.cpp

**AFTER:**

bool Spell::CheckTargetCreatureType(Unit* target) const
{
    uint32 spellCreatureTargetMask = m_spellInfo->TargetCreatureType;
	
	**INSERT THIS:**
	
	if (m_spellInfo->Id == 28734)
	if (target->GetPower(POWER_MANA) <= 0)
			return false;
