### ISSUE TITLE
Shaman Totem Instant Effects

### ISSUE THREAD

**Issue by Kaloy007** [OregonCore/OregonCore#1440]
**Revision**:
Rev: 3545+ Hash: 10d59f7+
**Operating system**:
Windows Server
**Current behavior**: 
If any totem is putted on the ground its effect is instant, so yeah, you can pretty much abuse their effects a lot, like spamming magma totem for instant damage and/or getting rogues out of stealth pretty easy, you can also spam the poison cleanse totem to remove your poisons.
**Expected behavior**: 
For example magma totem effect should come 2 seconds after the spawn,for poison cleanse totem 5 seconds.

**Comment by Baynar** [comment]
Can confirm

**Comment by LordUsagi** [comment]
What? There are totems that should be instant pulse..

**Comment by LordUsagi** [comment]
Please see #817

**Comment by Kaloy007** [comment]
Not sure about other totems but im 100% sure magma totem effect should come after 2 seconds.

**Comment by LordUsagi** [comment]
I haven't been able to find any mention of it. Any luck?

**Comment by Kaloy007** [comment]
Found it this update bugs the totem https://bitbucket.org/oregon/oregoncore/src/daad03585c3ed54209dcd01d475846fc85b0297a/sql/updates/world/2567_totems.sql?at=default&fileviewer=file-view-default
Tested Magma Totem with passive spell only and its working okey.
Fix for it.
-- Magma Totem
-- Rank 1
UPDATE creature_template SET spell2 = 0 WHERE entry = 5929;
-- Rank 2
UPDATE creature_template SET spell2 = 0 WHERE entry = 7464;
-- Rank 3
UPDATE creature_template SET spell2 = 0 WHERE entry = 7465;
-- Rank 4
UPDATE creature_template SET spell2 = 0 WHERE entry = 7466;
-- Rank 5
UPDATE creature_template SET spell2 = 0 WHERE entry = 15484;

**Comment by LordUsagi** [comment]
Right. It doesn't because you still haven't proven it shouldn't be instant.

**Comment by Kaloy007** [comment]
Yep, someone other needs to prove it. I just tested the totem in some tbc servers online from more than 5 years and the effect comes after 2 sec.

**Comment by zurr** [comment]
yep hard to find videos of 2.4.3 patch with totems clearly visible
a lot of videos 2007 2008 are terrible quality

**Comment by zurr** [comment]
some wotlk vdeos
https://www.youtube.com/watch?v=4Zl6UkenGng 0.45
https://www.youtube.com/watch?v=L8UUOQim90E 0.51
https://www.youtube.com/watch?v=xOAVlW9Qwns 1.23

**Comment by Kaloy007** [comment]
In these videos the effect is not at spawn. :P
