### ISSUE TITLE
Agressive Pets

### ISSUE THREAD

**Issue by Kaloy007** [OregonCore/OregonCore#1441]
**Revision**:
Rev: 3545+ Hash: 10d59f7+
**Operating system**:
Windows Server
**Current behavior**: 
When your pet is setted to Aggressive and some player move around him the Pet attacks him in non pvp zones, the pic below is made in shattrath.
![bug](https://cloud.githubusercontent.com/assets/19621905/16207960/2b88fdae-3730-11e6-962b-906326e1741b.JPG)

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by Baynar** [comment]
Can confirm if the player is the opposite faction your pet will attack him tested with hunter pets/ warlock pets / priest shadowfiend(after the duel end if shadowfiend is still active it will attack the other player) /
Shaman Searing Totem

Tested in cities / sanctuary / non pvp zones

**Comment by Baynar** [comment]
Tried a small fix in PetAI.cpp on line 308 in void PetAI::AttackStart(Unit\* target)
Added this ->
http://pastebin.com/7vzNq6Dp

now pets will not attack other faction players or pet and totems summoned by them

but totems will attack pets and players

**Comment by LordUsagi** [comment]
Resolved in 9b4284b3c338165dfee40d3d800bc84a58d90786
