### ISSUE TITLE
Errors with "The Eye" map files

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1442]
**Revision**:
last
**Operating system**:
winserv2008r2
**Current behavior**: 
Errors with "The Eye" map files

**Expected behavior**: 
...

**Steps to reproduce the problem**:
Teleport to "The Eye" instance
![2](https://cloud.githubusercontent.com/assets/6802530/16227938/7eb665ca-37bc-11e6-8371-5b70b7ef7594.png)

**Comment by Zaffy** [comment]
It's not just the eye. But don't worry those grids do not exists but for some reason OC attempt to load them. @LordUsagi knows grid system far better than me so I let this to him.

**Comment by Baynar** [comment]
This is not only for The Eye i have these errors on every 3rd dungeon or instance

**Comment by Desteny** [comment]
This problem was existing already in 2010, and was newer solved.
Its like zaffy sayed, it never had a negative effect.

Maybe its wrong to show this error for this type of map file, but how it can be dedected? dont ask me maybe someone has an idea...
