### ISSUE TITLE
Inconsistent Loot

### ISSUE THREAD

**Issue by Zaffy** [OregonCore/OregonCore#1443]
**Revision**: abefe71
**Operating system**: linux

**Steps to reproduce the problem**:
1. .go xyz 2253 1331 35 0
2. summon another player to assist you (or open second window)
3. make those characters to be in the same group
4. kill a farmer
5. **open loot window with both players**
6. Sometimes when you reverse order of players they will see the other part of loot and vice versa

**Current behavior**: 
Loot is not consistent between player. One player sees one part of loot and the second another part of the loot. If there's a item that is about to be rolled for, it will appear in both windows. Also, sometimes when first looter stops looting and second one starts to loot it sess the loot he didn't see before.

[screenshot 1](http://i.imgur.com/ZALZJOX.png?1)
[screenshot 2](http://i.imgur.com/omNpoRL.png?1)

**Expected behavior**: 
Both players should see all loot (except for quests items...)

---

Also I noticed sparkling at round-robin loot even when you couldn't loot that creature. Then when the other player did loot it, sparkling stopped.

**Comment by LordUsagi** [comment]
That's so bizarre!
