### ISSUE TITLE
Shaman Greater Totems

### ISSUE THREAD

**Issue by Baynar** [OregonCore/OregonCore#1445]
**Revision**:
3545
**Operating system**:
Windows 10
**Current behavior**: 
....When you use Earth Elemental totem or Fire Elemental totem they are summoned but they just stay and follow you without helping

**Expected behavior**: 
...Totem should attack when you attack or get attacked

**Steps to reproduce the problem**:

**Comment by LordUsagi** [comment]
Why close this? People are opening a lot of issue reports only to close
them later without explanation

**Comment by Baynar** [comment]
The reason was because the zone was a Sanctuary or something like that it was not from the core as i remember
