### ISSUE TITLE
why gossip_menu_option is only 57 record

### ISSUE THREAD

**Issue by a584627323** [OregonCore/OregonCore#1449]
**Revision**:
last
**Operating system**:
windows server 2008r2
**Current behavior**: 
....
gossip_menu_option is for 57 record

**Expected behavior**: 
...
i want to menu option is Convert to another language,but gossip_menu_option is only 57 record ,thk
**Steps to reproduce the problem**:

**Comment by Zaffy** [comment]
Not sure, either most of gossips are handled by C++ scripts or some records are missing.
