### ISSUE TITLE
Bug with custom script for reload DB.

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1452]
**Revision**:
Last

**Operating system**:
Windows 2012 R2

**Current behavior**: 
When I type .reload item_template the server console just crash without erros on the error-log. This happen only with item_template. No problem with the other template tables. 

Also I test it on Rev from Bitbucket (very old rev) and it work perfectly. Now I am 99% sure, that the problem is from the core.

**Expected behavior**: 
Should to reload the item_templates without crash or something.

**The script**
http://pastebin.com/xDrf2gPs

**Comment by WaCzup** [comment]
You are not supposed to have this command, soo what we are talking here about?

++ In older revs, i got errors from Item.dbc, where it loaded items like at start and then stopped on i guess 30? error.. even thought i got right Item.dbc..
It worked on linux for me, i guess windows isn't strong enough to process this script.

E:// i guess lock. ? [: :-1:

**Comment by kepo123** [comment]
Wtf are you talking about? It's a for the database tables, not .dbc !

**Comment by Baynar** [comment]
If you use .reload item_template server will freeze not crash and that is because of the database errors given... i had this command but removed it

but on the other hand .reload creature_template works fine

also when item_template is reloaded or loaded it takes values from item.dbc and it gives errors for custom items and so on... maybe if console mode is disabled it will work

**Comment by WaCzup** [comment]
Ye, it will reload item_template.. but with that you need to reload Item.dbc too and that was the problem when i tried that on windows..

It works same as when you starting server -> LOADING ITEMS and it will load Item.dbc too [:

**Comment by kepo123** [comment]
http://prntscr.com/blo2lj :)

**Comment by kepo123** [comment]
Windows log.

```
**Problem signature:**
  Problem Event Name:   APPCRASH
  Application Name: oregon-core.exe
  Application Version:  0.0.0.0
  Application Timestamp:    576fa639
  Fault Module Name:    oregon-core.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   576fa639
  Exception Code:   c0000005
  Exception Offset: 000a76db
  OS Version:   6.3.9600.2.0.0.272.7
  Locale ID:    1026
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: 1318
  Additional Information 4: 13181ae637ac2592fac0ca2dd662cdcc

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262


```

**Comment by celroot** [comment]
If i am not wrong this " sObjectMgr.LoadItemPrototypes();" is not supported in new revision, i think now the new way to load is " LoadItemTemplates();" but you should to search more and see what is wrong in your patch

**Comment by Baynar** [comment]
Even with LoadItemTemplates(); its the same i have already tried to do this but when i use the command it doesn't reload item.dbc and i get spammed with errors and core freezes

**Comment by celroot** [comment]
Yeah you right. I got the same error. Anyway i don't have all tools to test the core, like dbc editor, etc.
