### ISSUE TITLE
Bug Event

### ISSUE THREAD

**Issue by shkrest** [OregonCore/OregonCore#1454]
# OregonCore Crash Report

Linux (3.16.0-4-amd64) #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64
Date: 26-Jun-16_21:00:01
Version: OregonCore Rev: 3543+ Hash: b286fdf+ (Unix,little-endian)
Build Type: Debug
Compiler: GNU (or compatible)
ACE version: 6.2.8

Memory: 3812225024 / 8084467712 (47.1549% used)
SWAP:   0 / 16554913792 (0% used)

Coredump file MAY be available.
Caught deadly signal: SIGSEGV
Fault at 0x0 referenced from: 0xf2fc6a:
# BackTrace Thread LWP 2916
#0 0xf2fc6a in GameEventMgr::RunSmartAIScripts(unsigned short, bool) +0x92

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/game/GameEventMgr.cpp:1475
Source file is newer than the executable!
1474:             if (iter->second->IsInWorld())
1475:                 iter->second->AI()->sOnGameEvent(activate, event_id);
1476:     }
#1 0xf2d2e3 in GameEventMgr::UnApplyEvent(unsigned short) +0x77

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/game/GameEventMgr.cpp:934
Source file is newer than the executable!
933:     // un-spawn positive event tagged objects
934:     GameEventUnspawn(event_id);
935:     // spawn negative event tagget objects
#2 0xf2a42f in GameEventMgr::StopEvent(unsigned short, bool) +0x63

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/game/GameEventMgr.cpp:142
Source file is newer than the executable!
141:
142:     if (overwrite && !serverwide_evt)
143:     {
#3 0xf2d1ae in GameEventMgr::Update() +0x3a2

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/game/GameEventMgr.cpp:922
Source file is newer than the executable!
921:             nextEventDelay = 0;
922:     for (std::set<uint16>::iterator itr = deactivate.begin(); itr != deactivate.end(); ++itr)
923:         StopEvent(*itr);
#4 0xe08515 in World::Update(unsigned int) +0x661

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/game/World.cpp:1972
Source file is newer than the executable!
1971:         m_timers[WUPDATE_EVENTS].Reset();                   // to give time for Update() to be processed
1972:         uint32 nextGameEvent = sGameEventMgr.Update();
1973:         m_timers[WUPDATE_EVENTS].SetInterval(nextGameEvent);
#5 0xb523c5 in WorldRunnable::run() +0x79

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/WorldRunnable.cpp:53
Source file is newer than the executable!
52:         sWorld.Update(diff);
53:         realPrevTime = realCurrTime;
54:
#6 0xb4e058 in Master::Run() +0x3f6

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Master.cpp:236
Source file is newer than the executable!
235:     // Stop freeze protection before shutdown tasks
236:     if (freeze_thread)
237:     {
#7 0xb4d92f in main +0x2be

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Main.cpp:164
Source file is newer than the executable!
163:     // todo - Why do we need this 'Master'? Can't all of this be in the Main as for Realmd?
164:     int exitcode = sMaster.Run();
165:     if (exitcode == 2)
#8 0x7fc907210b45 in __libc_start_main +0xf5

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
#9 0xb436cf in _start

  from ./oregon-core
    at ??:0
# BackTrace Thread LWP 9124
#0 0x7fc9072d0ae3 in __select +0x33

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
#1 0x7fc908731b64 in _nc_timed_wait +0x194

  from /lib/x86_64-linux-gnu/libtinfo.so.5
    at /lib/x86_64-linux-gnu/libtinfo.so.5:0
#2 0x7fc9089518f8 in _nc_wgetch +0x3a8

  from /lib/x86_64-linux-gnu/libncurses.so.5
    at /lib/x86_64-linux-gnu/libncurses.so.5:0
#3 0x7fc9089523d5 in wgetch +0x35

  from /lib/x86_64-linux-gnu/libncurses.so.5
    at /lib/x86_64-linux-gnu/libncurses.so.5:0
#4 0xb48a99 in Console::GetChar() +0x1b

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Console.cpp:220
Source file is newer than the executable!
219: {
220:     int ch = getch();
221:     if (ch == KEY_MOUSE)
#5 0xb49859 in Console::RunCommandLoop() +0x419

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Console.cpp:511
Source file is newer than the executable!
510:
511:         int ch = GetChar();
512:         if (ch >= 0x20 && ch < 0x7F)
#6 0xb491d6 in Console::MainLoop() +0x6a6

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Console.cpp:383
Source file is newer than the executable!
382:                 RunCommandLoop();
383:                 break;
384:             case 1: /\* Real-time logs */
#7 0xb48b2d in Console::CliRunnable::run() +0x41

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/oregoncore/Console.cpp:241
Source file is newer than the executable!
240:     sConsole.MainLoop();
241: }
242:
#8 0x100e9e1 in ACE_Based::Thread::ThreadTask(void*) +0x69

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Threading.cpp:190
Source file is newer than the executable!
189:     #if PLATFORM == PLATFORM_UNIX
190:     UnixDebugger::RemoveThread(currentId());
191:     #endif
#9 0x7fc909a2b376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#10 0x7fc9075a20a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#11 0x7fc9072d787d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 9122
#0 0x7fc9075a608f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fc9099f5a0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fc9099dcdc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xff3523 in SqlDelayThread::run() +0x47

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Database/SqlDelayThread.cpp:37
Source file is newer than the executable!
36:         // empty the queue before exiting
37:         s = dynamic_cast<SqlAsyncTask*> (m_sqlQueue.dequeue());
38:         if (s)
#4 0x100e9e1 in ACE_Based::Thread::ThreadTask(void*) +0x69

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Threading.cpp:190
Source file is newer than the executable!
189:     #if PLATFORM == PLATFORM_UNIX
190:     UnixDebugger::RemoveThread(currentId());
191:     #endif
#5 0x7fc909a2b376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fc9075a20a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fc9072d787d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 9121
#0 0x7fc9075a608f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fc9099f5a0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fc9099dcdc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xff3523 in SqlDelayThread::run() +0x47

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Database/SqlDelayThread.cpp:37
Source file is newer than the executable!
36:         // empty the queue before exiting
37:         s = dynamic_cast<SqlAsyncTask*> (m_sqlQueue.dequeue());
38:         if (s)
#4 0x100e9e1 in ACE_Based::Thread::ThreadTask(void*) +0x69

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Threading.cpp:190
Source file is newer than the executable!
189:     #if PLATFORM == PLATFORM_UNIX
190:     UnixDebugger::RemoveThread(currentId());
191:     #endif
#5 0x7fc909a2b376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fc9075a20a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fc9072d787d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 9120
#0 0x7fc9075a608f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fc9099f5a0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fc9099dcdc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xff3523 in SqlDelayThread::run() +0x47

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Database/SqlDelayThread.cpp:37
Source file is newer than the executable!
36:         // empty the queue before exiting
37:         s = dynamic_cast<SqlAsyncTask*> (m_sqlQueue.dequeue());
38:         if (s)
#4 0x100e9e1 in ACE_Based::Thread::ThreadTask(void*) +0x69

  from ./oregon-core
    at /home/stre/wow/scapegaming/src/shared/Threading.cpp:190
Source file is newer than the executable!
189:     #if PLATFORM == PLATFORM_UNIX
190:     UnixDebugger::RemoveThread(currentId());
191:     #endif
#5 0x7fc909a2b376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fc9075a20a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fc9072d787d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

**Comment by shkrest** [comment]
Server just works, it does not have players. I understand the event starts Gurubashi Arena Booty Run. After graduation, when miropriyatie deletes, its components. Beings objects. The server shuts down. And the issue report that I cited above.

**Comment by Baynar** [comment]
i think this might be related to https://forums.oregon-core.net/viewtopic.php?id=533

Maybe when the event ends and the Gobjects are being deleted it crashes
Since core crashes with no players online

**Comment by Zaffy** [comment]
Fixed in 38cac0a
