### ISSUE TITLE
Two strange bugs.

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1456]
**Revision**:
Last and rev 3431
**Operating system**:
Windows R2 2012

**Bug**
Well... This is very strange bug. I am using two servers with rev 3431 and the last rev.

We will call them Server1 with Rev 3431 and Server2 with the last rev.

First, take bows on your ActionSpellBar and then use them when click 1,2,3 and etc. Server2(last rev) have this bug - https://youtu.be/8gZpHMAmAP0 , but Server1(rev 3431) doesn't have this bug.

This is with all portals. No need to do something for the bug. https://youtu.be/IZzwmxoxvjA , Server2(last rev)  have this bug, but Server 1(rev 3431)  no.

I need fast fix. Please! :)

**Comment by kepo123** [comment]
Bump

**Comment by Zaffy** [comment]
Can't reproduce noither of the bugs. Do you have some custom changes? Or perhaps you could give me detailed steps to reproduce?

**Comment by kepo123** [comment]
Yes, they are a lot. But before to update our core to last rev, with rev 3431 we didn't have these bugs.

**Comment by Zaffy** [comment]
Ok. Once you give me the steps to reproduce, i can take a look at it.

**Comment by kepo123** [comment]
Well, for the bows just take custom or blizzard bows on the spell bar and just use them with 1,2,3 and etc. :) 

For the portal bug .. i have no idea.

**Comment by Zaffy** [comment]
- I tried the boes like that and it didn't work.
- for the portals i guess it was just a lag - disconnect without actually disconnecting

**Comment by kepo123** [comment]
Lag? So all 6 GM's have a lag?

**Comment by kepo123** [comment]
The portals still doesn't work.

**Comment by LordUsagi** [comment]
Compile a clean version of the core with freshly extracted maps and tell us
if it happens.

**Comment by Baynar** [comment]
Portals are working fine for me.
and i think its cause he uses old maps

**Comment by kepo123** [comment]
@Baynar 

Nop. The maps are new... and same thing.

**Comment by kepo123** [comment]
Well... Theres no fix?

**Comment by Zaffy** [comment]
No since we cannot reproduce this bug.

**Comment by kepo123** [comment]
The bug coming from this spell - http://www.wowhead.com/spell=44972/legendary-bow-haste

Example: 4 bows with this proc (equip) and when you change them fast it will start to stack the haste. 

Fixed! :) I'm not sure, maybe Blizzard are guilty or it's from the core, but the one fix is to not use this spells on items! Sorry for the bad eng.

**Comment by kepo123** [comment]
Still waiting for fix! https://www.youtube.com/watch?v=IZzwmxoxvjA&feature=youtu.be

**Comment by LordUsagi** [comment]
Nothing broken.
