### ISSUE TITLE
Share quest is not working

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1457]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
When you try to share quest with someone - nothing happens

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches

**Comment by LordUsagi** [comment]
Which revision is this on? Last or Latest doesn't count.

**Comment by PadreWoW** [comment]
Latest commit 5d11c32

**Comment by Phentora** [comment]
Issue still occurs in OregonCore Rev: 3869 Hash: ffc80075

The shared quest appears to the other player, but after it is accepted, the quest isn't actually taken.

**Comment by PadreWoW** [comment]
Fix:

`
In QuestHandler.cpp
change strings:
 
 // no or incorrect quest giver
    if (!pObject || (pObject->GetTypeId() != TYPEID_PLAYER && !pObject->hasQuest(quest)) || 
		(pObject->GetTypeId() == TYPEID_PLAYER && pObject != _player && pObject->ToPlayer()->GetSession()->GetSecurity() < SEC_GAMEMASTER && !pObject->ToPlayer()->CanShareQuest(quest)))
		

		
		
and this strings:
		
if (pPlayer->GetDivider() != 0)
                {
                    _player->SendPushToPartyResponse(pPlayer, QUEST_PARTY_MSG_BUSY);
                    continue;
                }

				pPlayer->PlayerTalkClass->SendQuestGiverQuestDetails(pQuest, pPlayer->GetGUID(), true);
                pPlayer->SetDivider(_player->GetGUID());
`
