### ISSUE TITLE
Unable to Unlearn Weaponsmithing

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1459]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
Unable to Unlearn Weaposmithing
When you unlearn it and relog - Weaposmithing in your spellbook again

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by Zaffy** [comment]
Did  you un/learned it the regular way or with GM commands?

**Comment by PadreWoW** [comment]
regular
with npc in Ironforge
relog and weaponsmithing is in my spellbook again - even after .save command

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches
