### ISSUE TITLE
Mob's pets can not clear aggro list

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1460]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
Mob's pets can not clear aggro list
They pursue player through all maps
the problem was detected in Zangarmarsh with Tamed Sporebat
![untitled](https://cloud.githubusercontent.com/assets/6802530/16806476/4f38620e-491d-11e6-8336-1ade7c66dc20.png)

**Expected behavior**: 
Pets should clear aggro list same as their masters

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches

**Comment by PadreWoW** [comment]
I have a fix - PLEASE TEST IT!

In PetAI.cpp
after
// Must also check if victim is alive
    if (inCombat && (!me->GetVictim() || (me->ToPet() && me->ToPet()->GetModeFlags() & PET_MODE_DISABLE_ACTIONS)))
        _stopAttack();

add this:
if (!owner->IsInCombat())
    {
        _stopAttack();
        me->DeleteThreatList();
        me->CombatStop();
        return;
    }

**Comment by PadreWoW** [comment]
Can anyone answer me?
Or all dead?

**Comment by DkVagabonden** [comment]
Hello Padre,

Going to test this now!

**Comment by Phatcat** [comment]
~~Yeah, you may want to hold off on that, because....~~

~~https://github.com/OregonCore/OregonCore/blob/master/src/game/CreatureAISelector.cpp#L53~~

~~Creature's pets don't even use PetAI. Only player's pets and controllable guardians.~~

**Comment by Phatcat** [comment]
https://github.com/OregonCore/OregonCore/blob/master/src/game/CreatureAISelector.cpp#L38

Okay... Are guardians not considered pets in Oregon?

**Comment by Phatcat** [comment]
Sorry, ignore my comments altogether; they don't have anything to do with this issue or the proposed fix, they only have to do with the AISelector.

**Comment by ljwlaji** [comment]
i think this should be write in unit.cpp while the Creature is out of combat then check if they have any pet(s). and pet(s)->combatstop();

edit: DO NOT check when master is a player

em....should be like this;

---

void Unit::CombatStop(bool includingCast)
{
    if (includingCast && IsNonMeleeSpellCast(false))
        InterruptNonMeleeSpells(false);

```
AttackStop();
RemoveAllAttackers();
m_HostileRefManager.deleteReferences();
if (GetTypeId() == TYPEID_PLAYER)
    ToPlayer()->SendAttackSwingCancelAttack();     // melee and ranged forced attack cancel
else if (Unit*pet = this->GetCharm())
{
        pet->CombatStop();
}
ClearInCombat();
```

}

---

not test yet = =

**Comment by Phatcat** [comment]
> i think this should be write in unit.cpp while the Creature is out of combat then check if they have any pet(s). and pet(s)->combatstop();

I'd agree that this seems like the more proper fix.

**Comment by ljwlaji** [comment]
bool CreatureAI::_EnterEvadeMode()
{
    if (!me->IsAlive())
        return false;

```
// sometimes bosses stuck in combat?
me->DeleteThreatList();
me->CombatStop(true);
me->SetLootRecipient(NULL);
me->SetPlayerDamaged(false);
me->SetLastDamagedTime(0);
+if (Creature*creature = me->GetGuardianPet())
    +creature->AI()->_EnterEvadeMode();
if (me->IsInEvadeMode())
    return false;

me->RemoveAllAuras();
me->LoadCreaturesAddon();
// @todo Determine if required
//me->SetReactState(REACT_AGGRESSIVE);

return true;
```

}

OK seems like worked

**Comment by PadreWoW** [comment]
tested?

**Comment by ljwlaji** [comment]
sure tested

**Comment by PadreWoW** [comment]
Why do you think that your fix better?
My fix checks if pet's owner is not in combat - I think this is better than simple "EnterEvadeMode" without owner check
You don't think so?

**Comment by ljwlaji** [comment]
@PadreWoW 
That's NOT I said  lol  I just repo the fix..

**Comment by PadreWoW** [comment]
I'm trying to engage in a constructive discussion
I want to understand what's better

**Comment by Phatcat** [comment]
I'll try to answer this to my best knowledge;

the reason it is better to do this in the owner's evade call is that it's very cumbersome to do something that specific directly in the generic AI (petAI). All active pets will have to do those checks, even though they are only relevant in a very small fraction of any time (which in my opinion is exactly when the owner itself is evading), and only with creature pets (as players pets don't go into evade - by doing it with the unit owner player's pets will never do those checks)

> My fix checks if pet's owner is not in combat 

When a mob enters 'evade mode' he usually be default leaves combat; ie by default the owner cannot both be in combat while also evading. sorta.

**Comment by Phatcat** [comment]
Also by doing it in the owners evade call rather than the AI is that nomatter what AI the pet is using (if it would ever use anything else than petAI); otherwise you'd have to add the functionality to any AI that a summon with a owner can be assigned.
