### ISSUE TITLE
No damage from bonefire, campfire and other fires

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1464]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
No damage from bonefire, campfire and other fires - just 1 sec combat

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches

**Comment by Eronox** [comment]
Confirmed

**Comment by PiskelDEV** [comment]
Confirm.

**Comment by LordUsagi** [comment]
You get some fire effect, like spell is trying to cast on you but no damage!

**Comment by AbraKabastard** [comment]
Well, this one sucks. Any ideas?
