### ISSUE TITLE
Creature name become grey when you attack

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1466]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
Creature name become grey when you attack but become red/yellow when creature dies
Tested on clear core without any third-party patches
![untitled](https://cloud.githubusercontent.com/assets/6802530/16805515/400e6782-4919-11e6-968e-2bab9fd5a286.png)

**Expected behavior**: 
Name should be red/yellow if you were first who attack creature and become grey if not

**Steps to reproduce the problem**:

**Comment by DanielBallaSZTE** [comment]
Yeah, can confirm too, but it's only visual.
You don't lose loot etc..

**Comment by Baynar** [comment]
Can confirm this is here from a long time probably wrong visual package is send ?

**Comment by PiskelDEV** [comment]
Can confirm this bug.

**Comment by PadreWoW** [comment]
+Dead mobs are NOT grey!

I think problem somewhere in UNIT_DYNFLAG_OTHER_TAGGER

**Comment by PadreWoW** [comment]
Problem is 100% here:

// hide lootable animation for unallowed players
                else if (index == UNIT_DYNAMIC_FLAGS && GetTypeId() == TYPEID_UNIT)
{
  -=PROBLEM IS HERE=-
}
// hide RAF menu to non-RAF linked friends

Can anyone help?
I can not fix it (spent on it 3 days - no result)

**Comment by PadreWoW** [comment]
I have one idea but not 100% correct

if (!target->isAllowedToLoot(ToCreature()))
{
    *data << (m_uint32Values[index] & ~UNIT_DYNFLAG_LOOTABLE);
    *data << (m_uint32Values[index] & UNIT_DYNFLAG_OTHER_TAGGER);
}
else
{
    *data << (m_uint32Values[index] & UNIT_DYNFLAG_LOOTABLE);
    *data << (m_uint32Values[index] & ~UNIT_DYNFLAG_OTHER_TAGGER);
}

The problem is 132 error when trying to logon near dead npc
Can anyone help?

**Comment by robinsch** [comment]
You don't need to add other tagger this should be handled at creature engage. Remove UNIT_DYNFLAG_OTHER_TAGGER for tagger.

**Comment by PadreWoW** [comment]
without this flag all works wrong as i said - "Creature name become grey when you attack"

with my patch all works as it should but i have 132 error on login near the dead npc

**Comment by robinsch** [comment]
That's not what I've ment, check what I wrote.

**Comment by PadreWoW** [comment]
Place a code here
I don't understand you

**Comment by robinsch** [comment]
I have no code to post, the code is correct thats currently in place where you try to fix it. Did you debug it if this code is reached? Maybe isAllowedToLoot returns wrong value.

**Comment by PadreWoW** [comment]
Wrong value?
Do you know what value is right?

**Comment by robinsch** [comment]
What are you talking about? Debug it and find the cause, I'm not gonna do it for you.

**Comment by PadreWoW** [comment]
lol - good idea - try to find value when you don't know right or wrong this value is

**Comment by robinsch** [comment]
As I said, isAllowedToLoot, it should return true for your case if you are the tagger.

**Comment by PadreWoW** [comment]
There is NO flag adding for tagger

**Comment by PadreWoW** [comment]
bool Player::isAllowedToLoot(const Creature\* creature)
{
    if (!creature->isDead() && !creature->IsDamageEnoughForLootingAndReward())
        return false;

```
const Loot* loot = &creature->loot;
if (loot->isLooted()) // nothing to loot or everything looted.
    return false;

if (loot->loot_type == LOOT_SKINNING)
    return creature->GetSkinner() == GetGUID();

Group* thisGroup = GetGroup();
if (!thisGroup)
    return this == creature->GetLootRecipient();
else if (thisGroup != creature->GetLootRecipientGroup())
    return false;

switch (thisGroup->GetLootMethod())
{
    case MASTER_LOOT:
    case FREE_FOR_ALL:
        return true;
    case ROUND_ROBIN:
        // may only loot if the player is the loot roundrobin player
        // or if there are free/quest/conditional item for the player
      if (!loot->roundRobinPlayer || loot->roundRobinPlayer == GetGUID())
            return true;

        return loot->hasItemFor(this);
    case GROUP_LOOT:
    case NEED_BEFORE_GREED:
        // may only loot if the player is the loot roundrobin player
        // or item over threshold (so roll(s) can be launched)
        // or if there are free/quest/conditional item for the player
        if (!loot->roundRobinPlayer || loot->roundRobinPlayer == GetGUID())
            return true;

        if (loot->hasOverThresholdItem())
            return true;

        return loot->hasItemFor(this);
}

return false;
```

}

**Comment by PadreWoW** [comment]
Any ideas?

**Comment by ljwlaji** [comment]
The Class Creature has a function named SetLootRecipient();
there must someplace using wrong bool somewhere
when i update the "issue Core\Loot Fix some issues with loot" the bug comes.

**Comment by ljwlaji** [comment]
try to fix this now...debuging..

**Comment by xianXian777** [comment]
Player.ccp line 3361. Read it.

**Comment by zhy9934** [comment]
@ljwlaji do you fix this ?

**Comment by PadreWoW** [comment]
I would also like to know :)

**Comment by zamalaev** [comment]
`You don't need to add other tagger this should be handled at creature engage. Remove UNIT_DYNFLAG_OTHER_TAGGER for tagger.`

Yes)) Good robinsch

**Comment by zamalaev** [comment]
Need test
```
bool Player::isAllowedToLoot(const Creature* creature)
{
-if (!creature->isDead() && !creature->IsDamageEnoughForLootingAndReward())
+if (!creature->isDead() || !creature->IsDamageEnoughForLootingAndReward() || !creature->HasFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_OTHER_TAGGER))
return false;
```

**Comment by ljwlaji** [comment]
fixed a long time ago…… as you guys said it just a verisual error

**Comment by PadreWoW** [comment]
fixed?
in what commit?

**Comment by PadreWoW** [comment]
I have last OC revision and names become grey

**Comment by ljwlaji** [comment]
That fix in my core and i'ts too old commit...Can't find it anymore...

**Comment by PadreWoW** [comment]
What your core? :) Do you have repository?

**Comment by ljwlaji** [comment]
Sorry for my bad english...
my local source download at 9/31/2015
and nerver commit to github....
Wish you can understand what i mean..

**Comment by ghost** [comment]
I think he is saying he is using an older version of oregoncore (9/31/2015) and never updated again
