### ISSUE TITLE
Curse of Warlock  Error

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1467]
**Revision**:
last
**Operating system**:
win7
**Current behavior**: 
In one group ,two Warlock cast Curse of the Elements at the same time，the target has two debuff

https://postimg.org/image/c8yed5apz/
https://postimg.org/image/ldfnfsx0n/

**Expected behavior**: 
the curse should be one

**Steps to reproduce the problem**:

**Comment by Zaffy** [comment]
This behavior is intended.

> Curses the target for 10 sec, reducing Arcane, Fire, Frost, and Shadow resistances by 45 and increasing Arcane, Fire, Frost, and Shadow damage taken by 6%. **Only one Curse per Warlock can be active on any one target.**

**Comment by zhy9934** [comment]
if 2 warlock cast the curse of the Elements at the same time. the effect of 6% can Superimposed to double？

**Comment by Zaffy** [comment]
Yes, curses are not exclusive buffs but exclusive per caster.

**Comment by zhy9934** [comment]
Blizzard don't seem like this .
2 warlock cast the curse of the Elements at the same time, the target should has one higher level debuff ?

**Comment by Zaffy** [comment]
Depends on ranks ranked....

Okay I found something useful at [wowiki](http://wowwiki.wikia.com/wiki/Warlock_curses):

> Non-damaging curses do not stack with those cast by another warlock. 

So this seems to be actually a bug.
