### ISSUE TITLE
Server is not working at all

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1469]
**Revision**:
3553
**Operating system**:
Linux-Debian
**Current behavior**: 
Both the oregon-realm and oregon-core are running, but you can not connect. You basically get stuck at "Success". It's like the oregon-core is not working, yet you can interact with the server itself through the command-line.
**Expected behavior**: 
It's expected to work.
**Steps to reproduce the problem**:
clone the github repo. Build the files. Upload the DB from: https://github.com/OregonCore/OregonCore/releases
apply updates from updates directory.

I also get tons of DB errors, while I did everything as said on the OregonWiki.
Would really appreciate some help. Thanks in advance.

**Comment by LordUsagi** [comment]
Multiple things... DB errors or warnings? Usually the core won't launch
correctly if there's a DB error. Make sure you execute the world dump
located in this repos "Releases" and then enable auto db updater to get all
the little updates we've come up with. Secondly, are you connecting from a
local computer, the same one you're hosting on? If not, check that ports
are forwarded and that you've got the correct realmlist set up in your
database.

**Comment by DanielBallaSZTE** [comment]
Yeah I did everything as said above, yet it doesn't work. Would you mind helping me on skype? You seem to be offline lately.

It runs on the same machine.

**Comment by DanielBallaSZTE** [comment]
Also if that helps, the oregon-realm registers the authentication.
[AuthChallenge] account REALYZEE is using 'enGB' locale (0)
User 'REALYZEE' successfully authenticated

Meanwhile the core itself doesn't really do anything.
Like it doesn't communicate with the realm or i don't know..
![image](https://cloud.githubusercontent.com/assets/20175069/16877924/b83b3d88-4aaa-11e6-942c-8664e07db010.png)

And it has lots of errors
![image](https://cloud.githubusercontent.com/assets/20175069/16877942/cc71f0b2-4aaa-11e6-9553-747179f7a33b.png)

**Comment by DanielBallaSZTE** [comment]
If I enable the autoupdate I get the error in the log file:
2016-07-15 10:43:29 SQL ERROR: Table 'world.version' doesn't exist
2016-07-15 10:43:29 Cannot execute file 2016_01_11_misc_db_updates.sql, size: 1$ize: 14342: Duplicate entry '19-0-5066-0-14-5092-0-0' for key 'PRIMARY'

EDIT:

Autoupdate completed..

**Comment by DanielBallaSZTE** [comment]
![image](https://cloud.githubusercontent.com/assets/20175069/16878765/2a7f2c62-4aae-11e6-8289-115ef1ed8b4f.png)
Beautiful.

**Comment by DanielBallaSZTE** [comment]
also, what is this:
2016-07-15 11:12:59 Using World DB: unknown world database

**Comment by DanielBallaSZTE** [comment]
I solved the problem by uploading the database from an older source and then applying the updates. No Idea why it worked..
