### ISSUE TITLE
Spirit Healer unusable

### ISSUE THREAD

**Issue by kuramajssken001** [OregonCore/OregonCore#1470]
**Revision**:
Commits:38cac0a49
**Operating system**:
Windows 7 x64
**Current behavior**: 
Spirit Healer unusable

**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by LordUsagi** [comment]
Missing a lot of information. Unusable doesn't tell us anything. Tell us the steps, the problem, have you tried other spirit healers? I'm closing all your open issues until you can format them properly.
