### ISSUE TITLE
Huge rollback after logging out

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1475]
**Revision**:
3553
**Operating system**:
Linux-debian
**Current behavior**: 
There is like a 5 minute rollback (or even more). We have started a new server, and half of the players (like 15) got a huge rollback. 

**Expected behavior**: 
Just simply log out and not get a rollback.

**Steps to reproduce the problem**:

Buy up tons of items, and log out.

![image](https://cloud.githubusercontent.com/assets/20175069/16895404/6b4248f2-4b75-11e6-919e-34db575c231e.png)

**Comment by DanielBallaSZTE** [comment]
![image](https://cloud.githubusercontent.com/assets/20175069/16895411/8b479e2c-4b75-11e6-993b-cb7fa52243b4.png)

I don't really know about those..

**Comment by Zaffy** [comment]
Please make sure you have properly prepared your database + apply all updates (or enable sql auto-updater)

**Comment by DanielBallaSZTE** [comment]
Autoupdate is on, and everything is done as written on the wiki.

**Comment by Baynar** [comment]
Me and my friend had the same problem a few days ago when we opened a 2nd realm on his linux and i had this bad rollback and we fixed it by inserting a fresh character database and everything was back to normal

**Comment by DanielBallaSZTE** [comment]
Okay, thanks! 

Anyways seems like the problem solved itself, we didn't do anything, and players aren't reporting about rollbacks anymore.
