### ISSUE TITLE
Segmentation error crash

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1476]
**Revision**:
3553
**Operating system**:
Linux (3.16.0-4-amd64) #1 SMP Debian 3.16.7-ckt9-3~deb8u1
**Current behavior**: 
Error log at the and.

**Expected behavior**: 
Error log at the end.

**Steps to reproduce the problem**:
# OregonCore Crash Report

Linux (3.16.0-4-amd64) #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64
Date: 17-Jul-16_02:00:01
Version: OregonCore Rev: 3553 Hash: 5d11c32 (Unix,little-endian)
Build Type: Debug
Compiler: GNU (or compatible)
ACE version: 6.2.8

Memory: 6911713280 / 8391938048 (82.3613% used)
SWAP:   0 / 4294963200 (0% used)

Coredump file MAY be available.
Caught deadly signal: SIGSEGV
Fault at 0x0 referenced from: 0x8a6239: address not mapped to object
# BackTrace Thread LWP 20163
#0 0x8a6239 in GameEventMgr::RunSmartAIScripts(unsigned short, bool) +0x59

  from ./oregon-core
    at ??:0
#1 0x8a90fe in GameEventMgr::ApplyNewEvent(unsigned short) +0x9e

  from ./oregon-core
    at ??:0
#2 0x8a9522 in GameEventMgr::StartEvent(unsigned short, bool) +0x182

  from ./oregon-core
    at ??:0
#3 0x8a97d6 in GameEventMgr::Update() +0x1b6

  from ./oregon-core
    at ??:0
#4 0x7b97c9 in World::Update(unsigned int) +0x3c9

  from ./oregon-core
    at ??:0
#5 0x5ccfa2 in WorldRunnable::run() +0xe2

  from ./oregon-core
    at ??:0
#6 0x5cbc58 in Master::Run() +0x3d8

  from ./oregon-core
    at ??:0
#7 0x5b945c in main +0x1ec

  from ./oregon-core
    at ??:0
#8 0x7fa44f678b45 in __libc_start_main +0xf5

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
#9 0x5caf7f in _start

  from ./oregon-core
    at ??:0
# BackTrace Thread LWP 27518
#0 0x7fa44f738ae3 in __select +0x33

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
#1 0x7fa450b99b64 in _nc_timed_wait +0x194

  from /lib/x86_64-linux-gnu/libtinfo.so.5
    at /lib/x86_64-linux-gnu/libtinfo.so.5:0
#2 0x7fa450db98f8 in _nc_wgetch +0x3a8

  from /lib/x86_64-linux-gnu/libncurses.so.5
    at /lib/x86_64-linux-gnu/libncurses.so.5:0
#3 0x7fa450dba3d5 in wgetch +0x35

  from /lib/x86_64-linux-gnu/libncurses.so.5
    at /lib/x86_64-linux-gnu/libncurses.so.5:0
#4 0x5d6802 in Console::MainLoop() +0x2c2

  from ./oregon-core
    at ??:0
#5 0xa66c82 in ACE_Based::Thread::ThreadTask(void*) +0x42

  from ./oregon-core
    at ??:0
#6 0x7fa451e93376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#7 0x7fa44fa0a0a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#8 0x7fa44f73f87d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 27516
#0 0x7fa44fa0e08f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fa451e5da0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fa451e44dc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xa60df6 in SqlDelayThread::run() +0x46

  from ./oregon-core
    at ??:0
#4 0xa66c82 in ACE_Based::Thread::ThreadTask(void*) +0x42

  from ./oregon-core
    at ??:0
#5 0x7fa451e93376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fa44fa0a0a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fa44f73f87d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 27515
#0 0x7fa44fa0e08f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fa451e5da0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fa451e44dc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xa60df6 in SqlDelayThread::run() +0x46

  from ./oregon-core
    at ??:0
#4 0xa66c82 in ACE_Based::Thread::ThreadTask(void*) +0x42

  from ./oregon-core
    at ??:0
#5 0x7fa451e93376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fa44fa0a0a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fa44f73f87d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0
# BackTrace Thread LWP 27514
#0 0x7fa44fa0e08f in pthread_cond_wait +0xbf

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#1 0x7fa451e5da0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) +0x7d

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#2 0x7fa451e44dc7 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) +0x97

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#3 0xa60df6 in SqlDelayThread::run() +0x46

  from ./oregon-core
    at ??:0
#4 0xa66c82 in ACE_Based::Thread::ThreadTask(void*) +0x42

  from ./oregon-core
    at ??:0
#5 0x7fa451e93376 in ACE_OS_Thread_Adapter::invoke() +0xa6

  from /usr/lib/libACE-6.2.8.so
    at /usr/lib/libACE-6.2.8.so:0
#6 0x7fa44fa0a0a4 in __errno_location +0x80a4

  from /lib/x86_64-linux-gnu/libpthread.so.0
    at ??:0
#7 0x7fa44f73f87d in clone +0x6d

  from /lib/x86_64-linux-gnu/libc.so.6
    at /lib/x86_64-linux-gnu/libc.so.6:0

**Comment by Zaffy** [comment]
Fixed in 38cac0a49e997578764266d4e7ab2c226f349fcc
