### ISSUE TITLE
Server Start

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1477]
**Revision**: 2dc7d24b19222d88b223bec0cab063b37376066b

**Operating system**: windows server 2008 r2 standart sp1

**Current behavior**:  cant start server says loading vendors and nothing happens
....
http://prntscr.com/buqhdr
**Expected behavior**: 
...

**Steps to reproduce the problem**:

**Comment by zhy9934** [comment]
your database has error

**Comment by PadreWoW** [comment]
MAAANYYY errors
