### ISSUE TITLE
Wowerrors

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1478]
**Revision**:
3553
**Operating system**:
Linux-Debian
**Current behavior**: 
Sometimes, when the shaman casts tremor totem, or places a few totems, half of the server gets wowerror.
We were in Gurubashi arena holding a 1v1 event, and the shaman dueled against a warlock. While the duel went on half of the server, including the shaman got wowerror, 3 times in a row. Also happened in arena. 

**Steps to reproduce the problem**:
Don't really know maybe something with tremor totem and warlock's fear.
That is my closest guessing.

**Comment by zurr** [comment]
no errors on engb \ enus locale
use dbc from enus \ engb client

**Comment by DanielBallaSZTE** [comment]
Confirmed shaman's Grounding totem causing wowerrors to every player near it.
