### ISSUE TITLE
Reflective shield

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1480]
**Revision**:
3553
**Operating system**:
Linux-debian
**Current behavior**: 
Reflects 100% or more

**Expected behavior**: 
It should reflect 50% of the damage

**Steps to reproduce the problem**:
Talent reflective shield, place it on yourself, reflect 100% damage

**Comment by talamortis** [comment]
spell id?

**Comment by DanielBallaSZTE** [comment]
Seems to be fixed in the new rev.

**Comment by LordUsagi** [comment]
That's great news!
