### ISSUE TITLE
Searing totem

### ISSUE THREAD

**Issue by DanielBallaSZTE** [OregonCore/OregonCore#1482]
**Revision**:
3553
**Operating system**:
Linux-debian
**Current behavior**: 
Searing totem randomly reveals a rogue in stealth. Targets it and starts casting.

Also I think the problem is with stealth, rather than the totem and vanish. A player on the server could easily target a rogue in stealth, no matter what, he saw him.

**Comment by DkVagabonden** [comment]
Tested and correct.

Anyone knows how to fix this?

**Comment by talamortis** [comment]
fix is in the gridnotifiers.h
