### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by zhy9934** [OregonCore/OregonCore#1483]
**Revision**:
last
**Operating system**:
win server 2008
**Current behavior**: 
crash
**Expected behavior**: 
no crash
**Steps to reproduce the problem**:
crash log:
1.https://gist.github.com/zhy9934/0a76f193b766e6de6957e47feb95f7c7
2.https://gist.github.com/zhy9934/7d9b22e8049e901a47a019ab3daf14f4
3.https://gist.github.com/zhy9934/7bb93b1813daccea8069d15f7545680a
4.https://gist.github.com/zhy9934/e3621a185bb38e0ed584021bcc6d06c4

**Comment by ljwlaji** [comment]
Got Same Crash With You..#1523

**Comment by LordUsagi** [comment]
Are these crashes still occurring?
