### ISSUE TITLE
Cmake Error new revision

### ISSUE THREAD

**Issue by celroot** [OregonCore/OregonCore#1484]
**Revision**:
Last Revision

**Operating system**:
Windows 10 Pro
**Current behavior**: 
Cmake errors when i try to build the VS solution, this never happened with old revisions always was the "Generated done" message... I think is the CmakeList that was modified early.

Some pictures: http://imgur.com/a/dWzxv
CmakeLogout: http://pastebin.com/Y68PZwvw

**Expected behavior**: 
Cmake should generate all correctly.

**Comment by PadreWoW** [comment]
This error is because of this commit:
https://github.com/OregonCore/OregonCore/commit/3d76a21fa205a3019fd7f9d28cbfb0b303034237

There is no MySQL support in core now - you should point mysql LIB and INCLUDE folders manually (if you have these folders - Xampp has no such folders)

**Comment by PadreWoW** [comment]
Revert this commit and all will be fine - tested

**Comment by zgn1988** [comment]
Win 10 Pro no problem

**Comment by LordUsagi** [comment]
Just to add to this... You can see clearly you're missing MySQL libraries
and need to point cmake to them.
