### ISSUE TITLE
Shade of Akama (BB #149)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#149]
This issue was migrated from bitbucket.
**Original Reporter:** niyo
**Original Date:** 07.05.2010 22:06:40 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** resolved
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149

<hr>

If you start the shade of akama event the adds do not spawn and if you killed all 6 channelers the boss does not run to akama and attack him.

so not killable atm

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** avoid
**Original Date:** 16.05.2010 13:24:15 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-177594

<hr>

Issue #132 was marked as a duplicate of this issue.

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 17.05.2010 11:45:31 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-178216

<hr>

hm rogas for me it looks like that you didn't changed anything :o

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 17.05.2010 12:34:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-178241

<hr>

sry my fault forgot hg update^^, i will test the fix

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 17.05.2010 13:12:14 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-178279

<hr>

Script is working perfect, thank you very much.

But you can heal the good Akama and I can't find the right mechanic_immune_mask, maybe someone can help

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** rogas
**Original Date:** 17.05.2010 13:12:17 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-178280

<hr>

i change something :) test and let me know it

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** 
**Original Date:** 18.05.2010 07:12:05 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-178824

<hr>

Bad declare Trinity, need be changed to Oregon in patch

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** rogas
**Original Date:** 18.05.2010 15:38:23 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179142

<hr>

my mistake fixed!

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 18.05.2010 15:45:19 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179145

<hr>

we need a way to disallow to heal the good akama

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** rogas
**Original Date:** 18.05.2010 16:13:46 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179162

<hr>

maybe we can add flag like non selectable when akama start fight ??

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 18.05.2010 16:57:53 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179190

<hr>

yea, that would be a way, but thats blizzlike...
Is there no npc flag or something like that to disallow heal?
or maybe afaction?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 18.05.2010 17:42:44 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179225

<hr>

but thats not blizzlike*

hm... thrall and jaina @ hyjal are not healable maybe we can lookup the flag or sth like that?

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** rogas
**Original Date:** 18.05.2010 21:02:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179341

<hr>

yes i think it's good idea i will check it

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** niyo
**Original Date:** 19.05.2010 13:13:57 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-179735

<hr>

I changed the "type_flags" to 8, now you can't heal him anymore, but before he had "type_flags = 4136".
Dunno how the changed flag affects the scripts he has

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** 
**Original Date:** 20.05.2010 13:28:11 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-180564

<hr>

hhmm... maybe try to change faction

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** stfx
**Original Date:** 27.05.2010 22:01:36 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-185170

<hr>

niyo, try to check it with TC2 to know the "right" solution...

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 01.08.2012 20:17:39 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/149/#comment-1748813

<hr>

**Comment by SLITH3RIN** [comment]
Can someone test it again? On the latest clean OregonCore Akama doesnt move again. Tested on Debian.
