### ISSUE TITLE
Fixing anti-cheat system somehow.

### ISSUE THREAD

**Issue by DkVagabonden** [OregonCore/OregonCore#1490]
**Revision**:
3560+
**Operating system**:
2008R2, win7, win10, 2012r2 
**Current behavior**: 
Beeing able to teleport, speed hack, fly hack, walk on water, noclip.
Without beeing banned or anything.
**Expected behavior**: 
People should not be able to do so.
Send me a pm here and i will send you link to the problem that can do all this.

**Steps to reproduce the problem**:
Trying to find out how to fix this. (I am new to all this)

**Comment by PadreWoW** [comment]
https://github.com/OregonCore/OregonCore/issues/1463

**Comment by DkVagabonden** [comment]
Thanks PadreWoW

**Comment by ljwlaji** [comment]
warden can check on teleport hack now？

**Comment by PadreWoW** [comment]
What has changed?
