### ISSUE TITLE
Druid class quests lines level 0 + no xp.

### ISSUE THREAD

**Issue by DkVagabonden** [OregonCore/OregonCore#1493]
**Revision**:
3560
**Operating system**:
Standard r2 2012
**Current behavior**: 
All the druid class quests are level 0, which means they give no xp?

**Expected behavior**: 
Should be some level and give xp`?

**Steps to reproduce the problem**:
No clue, trying to find out!

**Comment by Zaffy** [comment]
I'm not sure about level, but class quests don't give XP AFAIK

**Comment by Selphius** [comment]
I think it works correctly, class quests should always be colored "yellow" no matter what lvl player has. For example warrior's berserker stance is lvl 30 quest, but you still see it yellow on lvl 70. I think it was specially made like that to distinguish class quests from zone quests.
