### ISSUE TITLE
Mob running away from me...

### ISSUE THREAD

**Issue by Alexdeath** [OregonCore/OregonCore#1495]
**Revision**: last

**Operating system**: debian x32

**Current behavior**:  Any mob, who I hit, running away from me in texture's down... Wtf? :)
....

**Expected behavior**: Mob must be stay and attack me, he attack, but in textures...
...

**Steps to reproduce the problem**: Maybe trouble in maps? Do you know?

**Comment by ljwlaji** [comment]
error maps vmaps mmaps? check it out

**Comment by Alexdeath** [comment]
I'll try extract new map. Write about result.

**Comment by Alexdeath** [comment]
Unresult... But, in console oregon-core I have message: "Error reading ModelSpawn, file name too long!".

**Comment by Desteny** [comment]
Note: don't know if the vmap / mmap generator is working again.
may try to download from here, https://forums.oregon-core.net/viewtopic.php?id=374

**Comment by Alexdeath** [comment]
Thx, it's work.
