### ISSUE TITLE
Some instance entrance portals are not working

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1497]
**Revision**:
3548+
**Operating system**:
Windows R2 2012
**Current behavior**: 
Some portals working.

**Expected behavior**: 
All portals should working!

**Steps to reproduce the problem**:
No need to do something special... Just watch this video > https://youtu.be/OsDC1HWLRs4

**Comment by PadreWoW** [comment]
rev 3559 not confirmed
all portals working

**Comment by Desteny** [comment]
best issue title ever!

vote for closing!

Title should describe the problem in some words, and should not contain revision or product name or bug!

Description should contain details along with the video, if it disapears over years...

**Comment by Desteny** [comment]
+1 for changing title, but i have changed it correctly, like i told the productname is not needed in title
i think it is clear that all issues are related to OregonCore. i dont think herer  will be created a issue for Trinity, Mangos or any other program ;)

portals are as well city portals @ shatt for example, or portals from mage, so it needs more info.

ijnstance entrances are managed by databse, so maybe you arewusing a modified or not up to date database or missing parts, but should be not core related
