### ISSUE TITLE
[Hunter]ManaRegen.

### ISSUE THREAD

**Issue by Alexdeath** [OregonCore/OregonCore#1498]
**Revision**: Last

**Operating system**: Debian 32

**Current behavior**: Hunter, on 70 lvl without equip haven't manareg.
....

**Expected behavior**: Hunter on 70 lvl without equip must have 34 manareg.
...

**Steps to reproduce the problem**:

**Comment by Alexdeath** [comment]
This trouble not only with hunter. Manareg haven't all classes. Need help)

**Comment by PadreWoW** [comment]
Last rev - not confirmed

![1](https://cloud.githubusercontent.com/assets/6802530/18120356/cc37ea34-6f67-11e6-8caf-bbcfb50991c6.jpg)

![2](https://cloud.githubusercontent.com/assets/6802530/18120361/d0e54504-6f67-11e6-8fb5-3f8942b34cca.jpg)

![3](https://cloud.githubusercontent.com/assets/6802530/18120364/d3b26438-6f67-11e6-84aa-216a704b4c6f.jpg)

**Comment by Phatcat** [comment]
I love how you didn't test this on a hunter, Padre ;)

**Comment by PadreWoW** [comment]
Alexdeath commented 2 days ago

This trouble not only with hunter. Manareg haven't all classes. Need help)

**Comment by PadreWoW** [comment]
You see only what you want to see?

**Comment by Phatcat** [comment]
Oh, I did see that. Still you usually go to the root of the problem. also he did mention no specific class, so he may have only tried with 2 - 3 classes, one of the classes you didn't pick.

Why'd you be offended, jesus, you think I'm hating on you guys or something? I'm not.

**Comment by PadreWoW** [comment]
Tested on Hunter - no problem with this class

**Comment by Phatcat** [comment]
Well that's good, then the problem most likely is on his end. I'm sorry if I come off as rude or arrogant at times. I am working on my general attitude..

**Comment by Phatcat** [comment]
Also I am still looking forward to someone either calling bullshit or affirming what I'm saying here; https://github.com/OregonCore/OregonCore/issues/1460

In my opinion we're all in the same boat. Sure we don't work on the same teams but that doesn't mean we can't help each other out.

**Comment by Desteny** [comment]
@Alexdeath it could be a database related problem. are you shure you using the latest clean database for testing?

ClassLevel Stats are modified in some revisions ago and if the database data don't match even from older DBs it can cause problems
