### ISSUE TITLE
Command levelup crashing server

### ISSUE THREAD

**Issue by Alexdeath** [OregonCore/OregonCore#1502]
**Revision**: last

**Operating system**: deb 86

**Current behavior**: levelup must up level target or if you haven't target up level you.
....

**Expected behavior**: if use command .level, server is down and level not change.
...

**Steps to reproduce the problem**:

**Comment by Desteny** [comment]
maybe you have outdated localized oregon_string in your database? or you are using a not matching world database (oregon_string table)

**Comment by Alexdeath** [comment]
Yes, you're right, i've localized oregon_string for levelup. I'll execute clean oregon_string and write here.

**Comment by Alexdeath** [comment]
It's work. Thx.
Sorry for my panic :(

**Comment by Desteny** [comment]
No problem, this is a common problem and i think this issue can help some people later as well ;)
