### ISSUE TITLE
Mana Drain

### ISSUE THREAD

**Issue by DkVagabonden** [OregonCore/OregonCore#1503]
**Revision**:
Newest
**Operating system**:
2012 R2
**Current behavior**: 
Mana Drain dont work at all
**Expected behavior**: 
Should work just like Life drain does.

**Steps to reproduce the problem**:
No clue, looking into it

**Comment by zamalaev** [comment]
SpellEffects.cpp
void Spell::EffectPowerDrain(SpellEffIndex effIndex)
`     if (drain_power == POWER_MANA)
     {
Add a comment to this line
         float manaMultiplier = m_spellInfo->EffectMultipleValue[effIndex];
-        if (manaMultiplier == 0)
-            manaMultiplier = 1;`

need test

**Comment by LordUsagi** [comment]
Latest isn't a revision. 

Not enough information provided.
