### ISSUE TITLE
.character Rename bug

### ISSUE THREAD

**Issue by smoldar** [OregonCore/OregonCore#1509]
if player get rename by command or rename over database, Core must be restarted, without restart of Core player get a lot of bugs.
Other players see new name but must write /w Oldname      and renamed player cant leave Arena team before restart of core.

**Comment by smoldar** [comment]
Solution: Need update core info about player name while player log into game.

**Comment by zamalaev** [comment]
WorldPacket data(SMSG_CHAR_RENAME, 1 + 8 + (newname.size() + 1));
    -data << uint64(guid);
   +data << guid;

need test

**Comment by DanielBallaSZTE** [comment]
Basically kicking the player solves it, no?

**Comment by AbraKabastard** [comment]
Merged into  #1040
