### ISSUE TITLE
Vmaps doesn't extract

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1516]
**Revision**:  
7bd4f7b

**Operating system**: 
Windows x64

**Current behavior**: 
Cannot extract vmaps

**Expected behavior**: 
Being able to extract them

**Steps to reproduce the problem**:

[//]: # use vmap_extractor.exe, you'll see errors when it finish extracting,
[//]: # open cmd and do vmap_assembler.exe Buildings vmaps, you will get an error
http://i.imgur.com/MdNE6a1.png
http://i.imgur.com/gGPMskq.png

**Comment by Desteny** [comment]
You can download the vmaps / mmaps from the forum.

its a known bug and was never fixed

**Comment by ghost** [comment]
I hate when something isn't working, I will investigate and fix it  thanks for your answer

**Comment by Desteny** [comment]
maybe @Zaffy can give you a hint, he was working on it...

**Comment by Zaffy** [comment]
@Blumfield  The few last errors are fine - there's even a warning explaining that. The files just did not ship with the game. Ignore that.

**Comment by zgn1988** [comment]
not confirm

create bat file

vmap4extractor
md vmaps
vmap4assembler buildings vmaps
pause
