### ISSUE TITLE
Comment commit PadreWoW

### ISSUE THREAD

**Issue by zgn1988** [OregonCore/OregonCore#1519]
PadreWoW не надо комментировать каждый мой коммит, я работаю в своей ветке, если вы в чем то не уверенны, либо сами протестируйте, либо ждите пока что-то уйдёт в мастер ветку.

**Comment by PadreWoW** [comment]
Я комментировал не для вас а для создателей репозитория и сделал я это ДО ответвления
Я считаю что коммиты должны проходить аппрув перед тем как их разместят в репозиторий

**Comment by Lumber-Jack-2** [comment]
can you translate this in english?

**Comment by PadreWoW** [comment]
Never mind

**Comment by ljwlaji** [comment]
lol

**Comment by zamalaev** [comment]
Rushor, Your Skype?
