### ISSUE TITLE
Core Crash When Map::Update()

### ISSUE THREAD

**Issue by ljwlaji** [OregonCore/OregonCore#1523]
**Revision**:
Ver.2015
**Operating system**:
Windows Server 2008 R2
**Current behavior**: 
It seems like A map Just Uninstall before This Function Run Call() In Another Threat.
And When Next Millon Second This Map Turn To A "Null"

**Expected behavior**: 
I Try To Fix This In MapUpdater.cpp
 virtual int call()
{
	+if (!this)
	    +return 0;
        m_map.Update (m_diff);
        m_updater.update_finished();
        return 0;
}
But I Don't Think IT'S A Porper Fix;

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ljwlaji** [comment]
So If I Can Get The Function Who Done The Map Releaser Work, I Think I Can Do Some Fix In That Function..
For CrashLog #1483

**Comment by zgn1988** [comment]
Crash occurs when taking the quest

**Comment by zgn1988** [comment]
fixed https://bitbucket.org/zgn/projecttbc/commits/00b757257fd1ea5e3db905c9d7edf1ad60be1725

**Comment by ghost** [comment]
your link doesn't work because you made it private

**Comment by zgn1988** [comment]
after updating the server I send to git branch in zamalaev

**Comment by ljwlaji** [comment]
That“s a private webpage…

**Comment by zgn1988** [comment]
https://github.com/OregonCore/OregonCore/commit/00b757257fd1ea5e3db905c9d7edf1ad60be1725

**Comment by ljwlaji** [comment]
I don't think it crash because the quest status, it also happen in creature::LoadFromDB() ->UpdateMovementflag() -> GetHeight() There are all null Map

**Comment by ljwlaji** [comment]
all stack:
Address   Frame     Function      SourceFile
000000013F924ACC  000000001378ED60  G3D::Table<GameObjectModel const * __ptr64,bool,HashTrait<GameObjectModel const * __ptr64>,EqualsTrait<GameObjectModel const * __ptr64> >::getKeys+9C
000000013F923AE4  000000001378EDA0  BIHWrap<GameObjectModel,BoundsTrait<GameObjectModel> >::balance+64
000000013F9247CE  000000001378EE70  DynamicMapTree::getHeight+CE
000000013F5A8307  000000001378EF10  Map::GetHeight+147
000000013F611B99  000000001378EFA0  Creature::UpdateMovementFlags+89
000000013F611AFB  000000001378EFE0  Creature::UpdateEntry+3DB
000000013F60C895  000000001378F010  Creature::CreateFromProto+A5
000000013F60C6D5  000000001378F070  Creature::Create+105
000000013F60E797  000000001378F100  Creature::LoadCreatureFromDB+D7
000000013F73777C  000000001378F170  LoadHelper<Creature>+7C
000000013F7385B4  000000001378F1C0  ObjectGridLoader::Visit+B4
000000013F73818B  000000001378F250  ObjectGridLoader::LoadN+CB
000000013F5A7944  000000001378F2D0  Map::EnsureGridLoaded+154
000000013F628AAF  000000001378F380

**Comment by ljwlaji** [comment]
A lot of "null" map

**Comment by ljwlaji** [comment]
Don't know why
I already add a
If(!this)
Return;
But the function still run to the next row

**Comment by ljwlaji** [comment]
This problem happened  1-2time pre one day; The server have 50-100 Players online

**Comment by zgn1988** [comment]
Crash occurs when taking the quest
	http://mibpaste.com/ThF84E 
http://mibpaste.com/r11XxL http://mibpaste.com/ycRC4l 
Crash
fix 00b7572
thx cmangos))

**Comment by ljwlaji** [comment]
Yep. It seems same problem...
Thanks zamalaev
But still can't understand why it's comes from a  quest status>_<

**Comment by zgn1988** [comment]
Search NPC on the map

**Comment by ljwlaji** [comment]
Em.... Try to debug it @-@ anyway thanks for your help zamalaev ^^

**Comment by ljwlaji** [comment]
still got this problem...
this issues not fix this crash at all

**Comment by zamalaev** [comment]
sources without patches? crash log please
