### ISSUE TITLE
Some way to make a ElunaEngine branch again?

### ISSUE THREAD

**Issue by dimitrijfedoryno** [OregonCore/OregonCore#1526]
Some way to make a ElunaEngine branch again?

**Comment by Lumber-Jack-2** [comment]
the branch isn't even active https://github.com/OregonCore/OregonCore/commits/master why should therer be more stress with a ElunaEngine? would be double work to my mind.

**Comment by dimitrijfedoryno** [comment]
Where i can find active branch for oregoncore? Or i What's the most active emu is for 2.4.3?

**Comment by ghost** [comment]
most active would be mangos, but you can make oregoncore active by doing pull request...

**Comment by dimitrijfedoryno** [comment]
I like to use the FusionCMS and i does not have the module for the mangos, i think the pull requests will be better :) Thank you for your answer and i'll be happy if i can have OC with ElunaEngine :)

**Comment by Saitohimea** [comment]
You can try mangos 2.4.3 they have get more active and eluna works there aswell.
