### ISSUE TITLE
Quest [The Cipher of Damnation] attun to Tempest Keep, crash server.

### ISSUE THREAD

**Issue by amaroc** [OregonCore/OregonCore#1527]
**Revision**:
[worldserver]
ConfVersion=2015071262

**Operating system**:
Ubuntu 16.04 (also tested on Windows 8 (same version of oregon).

**Current behavior**: 
Server get crashed on starting dialog when i doing quest 10588.

**Expected behavior**: 
Must be started dialog, and i cant attack this big mob\boss, before i talk with priests wich must come to me from behind.... (sory for russian english). 

**Steps to reproduce the problem**:
I added to self quest:
.quest add 10588
[The Cipher of Damnation] 
Get item from it (30657), i stay near (.go creature 84600) GulDan in Shadowmoon valey, use this item, and apears big boss. 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

I think it is crash log (from server.log):
https://gist.github.com/amaroc/dd67de32d9d6332b2fe12003af7dec2b
But i found "real" crash log: 
https://gist.github.com/amaroc/379c298c901890116b1f4ea1110ceb48

I found this text entry deleted from DB World, https://github.com/OregonCore/OregonCore/blob/7bd4f7b3480c503451813ab65f5a98228e5869aa/sql/updates/world/2016_03_24_creature_template.sql - but ho i can prevent this crashes? Recompile without this dialog? I tried add text to DB , it say this text,  but any way crashes after it too ;) Exist any configuration to ignore this "errors" and just log it in file if it heppens? 

PS: server crashes even if i .add npc 21181 (wich i must slain).

**Comment by ljwlaji** [comment]
Did you get the crash log with debug mode?

**Comment by amaroc** [comment]
Looks like it crash log with debug mode:
Version: OregonCore Rev: 3602 Hash: 2c4336c (Unix,little-endian)
Build Type: Debug
https://gist.github.com/amaroc/379c298c901890116b1f4ea1110ceb48
