### ISSUE TITLE
Player can attack friendly npcs by mass spells when they are in combat

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1529]
**Revision**:
last
**Operating system**:
winserv 2008r2
**Current behavior**: 
Player can attack friendly npcs when they are in combat
For example: Kayra Longmane (escort) in Zangarmarsh
You can hit her by any mass spell (frost nova for example) when is in combat
p,s OOC_NOT_ATTACAKBLE flag (unit_flags = 256) not working

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by amaroc** [comment]
Same thing, near Karazhan. NPC sometimes get agro on my char (undead) and i can kill them with AOE mass kill, maybe wrong faction...
sorry for offtopic: пытался найти контакт Падре но ненашел, подскажите - я вот ваше решение по неймплейтам тестировал, что бы красные были как положено, но так и не смог найти разницы между предыдущем решением и вашем (вплане ваше делает так как должно быть по цветам визуально, а вот разницы с выпадающими кв. итемами я не нашел, вы писали что вы древний баг какой то пробудили и по 1 кв. итему падает - так оно и падает по 1 кв. итему  и при старом решении, а вот из сундуков или с боссов кв. итемы с вашим решением норм забираются всей групой).

**Comment by ljwlaji** [comment]
I did remember a Func which call a CanAttack (not sure It's In OC or TC)

If OC Dosen;t have that func , you can try to add a if (IsFriendlyTo)
Try to Edit it, And you will get what you want. ^^

**Comment by ljwlaji** [comment]
And Did Oc Dead Again Again Again？？？ lol

**Comment by PadreWoW** [comment]
I think so :(

**Comment by fkwall** [comment]
I found that BUG too
