### ISSUE TITLE
Warlock Pet Spells

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1530]
**Revision**:
Last
**Operating system**:
Windows R2 2012

**The problem**:
Greetings, I own a wow server (255 Level is the cap) and I have a problem that I don't know how to fix. I'm having a problem with warlock's pets. I fixed their stats for Lvl255 - hp, armor, stamina and etc. but their spells hit like the pets are Level 70. Any idea how may I fix it? 

**On 2.4.3. the changes on Spell dbc does not work properly.**

**Comment by LordUsagi** [comment]
Hey!

We don't really try to figure out stuff in relation to insane level caps and crazy damage modifiers and so we also don't respond to any bug reports really relating to that.

In any case, if you do find some core addition that can help these niche scenarios you can submit a pull request and upon review we may decide to implement it into the cores design for future custom content creators.

I suggest trying many of the custom WoW server communities that are scattered online, and also checking out Trinity related topics for people who have pulled this off in Wrath of the Lich King, as it can probably be easily ported over!

Good luck and thanks for the report!
