### ISSUE TITLE
Paladin's Cleanse bug

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1531]
**Revision**:
Last

**Operating system**:
Windows R2 2012

**The BUG**:
Paladin's Cleanse effect should remove 1 Poison, 1 Disease and 1 Magic effect, right? But actually it removes all poison, disease and magic effects with only 1 click. Any ideas how it may be fixed?

**Comment by Lumber-Jack-2** [comment]
why do you still create issues here? the project is dead to my mind

**Comment by kepo123** [comment]
@Rushor Really? Damn... Another dead project for 2.4.3 ...

**Comment by PadreWoW** [comment]
yep :(

**Comment by Lumber-Jack-2** [comment]
not completely dead, because they update stuff every 1-2 month, but however.. :(

**Comment by zgn1988** [comment]
@Rushor 👍

**Comment by PadreWoW** [comment]
чел ты куда пропал???

**Comment by zgn1988** [comment]
ProjectLegion)) скоро че нить закину и сюда)

**Comment by PadreWoW** [comment]
ты лучше ответь в своём проекте по TBC мне реально нужна помощь с багом с масс атаками на нейтралов
у меня есть наработки но до конца не получается

**Comment by kepo123** [comment]
English please.

**Comment by PadreWoW** [comment]
zamalaev ты куда пропал?????

**Comment by Lumber-Jack-2** [comment]
what?

**Comment by PadreWoW** [comment]
Oregon is DEAD....... too bad :(

**Comment by Selphius** [comment]
@PadreWoW 
It's normal I guess, most devs don't have time for it, some are discouraged since they don't get any thanks or anything (Pservers using opensource core like TC/OC, rename it and get all credits to themselves. Community calls OpenSource cores as STOCK core shit not even worth using). It's really discouraging for most, who contribute a lot to such projects.

**Comment by kepo123** [comment]
@Selphius 
- soo.. no more updates?

**Comment by Selphius** [comment]
@kepo123 
I can't really tell you, since I am me - a one person army, who stopped contributing to WoW OpenSource projects. Each dev has his own persona and goals, you would need to ask this question to each OC dev to know the answer.

**Comment by LordUsagi** [comment]
I can't reproduce this issue on a clean core. Any help?

**Comment by LordUsagi** [comment]
Unable to reproduce. No feedback in 48 hours.
