### ISSUE TITLE
Packing instances is extremly slow

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1532]
**Revision**:
Last
**Operating system**:
Windows R2 2012
**The BUG**
While we are restarting the server, "Instances" loads extremely slow (10 minutes)
Any ideas how may I fix it? - http://prnt.sc/dwlt21 ... 2-3 minutes per procent.

**Comment by Zaffy** [comment]
Hello, can you specify the "Last" revision? Since in your screenshot there's a progress bar and we removed them quite a long ago for perfomance reasons.

**Comment by kepo123** [comment]
Well, they just told me last rev. May you give me a link where exactly they are removed so we can take a look because I am not core developer and I am not much into stuff like that? I am just a owner :D.

**Comment by Zaffy** [comment]
They were removed in 77a9da58db4176167c04576104f7348af0de8bfa, also a little of code was accidentaly removed and restored in 6af48e46bda1249001e58b681d74dbcd84509df4

I cant support your old version of core, sorry, I'm closing this.

**Comment by kepo123** [comment]
Well. We removed the progress bar and still wait 10 minutes to load. The problem could not be the machine.

The machine specifications: Intel Xeon E5-2630 (8 cores), 32 gb ram, 1gbps network.

**Comment by Artamedes** [comment]
then you should use the latest orgencore and see that :^) obviously something is wrong here

**Comment by kepo123** [comment]
Is there any lesson how to update it, because we have a lot of core changes and if they are lost while updating it, everything goes to hell.

**Comment by Artamedes** [comment]
You probably won't get help for that here, just pull the latest, and add whatever you changed in.

**Comment by ghost** [comment]
git pull origin and resolve merge conflict on your own

**Comment by kepo123** [comment]
@sunshitwowsucks But there are really a lot of changes.
