### ISSUE TITLE
Rogue + Skinning = Bug

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1533]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
WHen you try to use skinning on every mob you can see a bug - after skinning mob doesn't disappear and show that you can loot it, but loot window is empty
![untitled](https://cloud.githubusercontent.com/assets/6802530/23695634/408d851a-03f1-11e7-9028-ac928ca5b499.png)
![untitled1](https://cloud.githubusercontent.com/assets/6802530/23695635/44bae2c2-03f1-11e7-9fba-343645ec534c.png)

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Problem is only with rogues

**Comment by PadreWoW** [comment]
Tested on clean core without third-party scripts

**Comment by LordUsagi** [comment]
Rogues only? Might be something to do with pickpocketing check messing up some stuff, haha!

**Comment by PadreWoW** [comment]
Bears have no pickpocket loot :)
