### ISSUE TITLE
Chat channels can not change

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1534]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
Chat channels can not change
**Expected behavior**: 
...

**Steps to reproduce the problem**:
Teleport to Ruins of Alterac (for example) and then teleport to Shattrath - channels will not change and you can not say anything in channels
![1](https://cloud.githubusercontent.com/assets/6802530/23797567/8cfd3316-05b1-11e7-8950-8af8f4755395.png)
![2](https://cloud.githubusercontent.com/assets/6802530/23797571/90b89ce8-05b1-11e7-9274-b91129136ba8.png)
![3](https://cloud.githubusercontent.com/assets/6802530/23797572/93446c08-05b1-11e7-9af6-bbc748d14d51.png)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Tested on clear core without third-party patches

**Comment by LordUsagi** [comment]
This is funny. Only occurs some times.
Edit: Could be related to map transfers. It seems to occur 100% of the time when changing between Shattrath and Stormwind for instance. But this won't occur changing between Shattrath and Netherstorm
