### ISSUE TITLE
Shattrath Flasks: Stats dont get reset after aura expire/cancel

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1535]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
Shattrath Flasks can be used everywhere + if you break flask effect -> stats are not clear
**Expected behavior**: 
...
Drink Shattrath Flask -> click on flask spell icon -> stats are not clear
![1](https://cloud.githubusercontent.com/assets/6802530/23851805/daa1d0ae-07f5-11e7-82d3-f8450aced5e6.png)
![2](https://cloud.githubusercontent.com/assets/6802530/23851812/de474914-07f5-11e7-95c8-47c79be80bdc.png)
![3](https://cloud.githubusercontent.com/assets/6802530/23851818/e15aaba0-07f5-11e7-8781-fe421fab6dc2.png)

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Fix for using:
(but there is a problem - spell should remove when not in dungeon)

    `/* Shattrath Flask of Fortification */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41609', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Fortification - Requires Area BT');

    /* Shattrath Flask of Relentless Assault */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41608', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Relentless Assault - Requires Area BT');

    /* Shattrath Flask of Mighty Restoration */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41610', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Mighty Restoration - Requires Area BT');

    /* Shattrath Flask of Pure Death */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46837', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Pure Death - Requires Area BT');

    /* Shattrath Flask of Supreme Power */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '41611', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Supreme Power - Requires Area BT');

    /* Shattrath Flask of Blinding Light */
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '1', '4', '0', '3845', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area TK'); 
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '2', '4', '0', '4075', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area Sun');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '3', '4', '0', '3848', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area Arc');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '4', '4', '0', '3849', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area Mech');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '5', '4', '0', '3847', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area Bot');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, 
    `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '6', '4', '0', '3607', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area SSC');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '7', '4', '0', '3606', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area Hyj');
    INSERT INTO `world`.`conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('17', '0', '46839', '0', '8', '4', '0', '3959', '0', '0', '0', '0', '0', '', 'Shattrath Flask of Blinding Light - Requires Area BT');

**Comment by PadreWoW** [comment]
A little fix to remove aura when exit dungeon (add this to void WorldSession::HandleMoveWorldportAckOpcode()

after bool allowMount = !mEntry->IsDungeon()  || mEntry->IsBattlegroundOrArena(); ):


    // Remove Shattrath Flask Auras if Not In Dungeon + Remove Bloodberry Elixir Aura
	if (!mEntry->IsDungeon())
	{
		if (GetPlayer()->HasAura(46839))
		GetPlayer()->RemoveAurasDueToSpell(46839);     // Shattrath Flask of Blinding Light
		else if (GetPlayer()->HasAura(41611))
			GetPlayer()->RemoveAurasDueToSpell(41611); // Shattrath Flask of Supreme Power
		else if (GetPlayer()->HasAura(46837))
			GetPlayer()->RemoveAurasDueToSpell(46837); // Shattrath Flask of Pure Death
		else if (GetPlayer()->HasAura(41610))
			GetPlayer()->RemoveAurasDueToSpell(41610); // Shattrath Flask of Mighty Restoration
		else if (GetPlayer()->HasAura(41608))
			GetPlayer()->RemoveAurasDueToSpell(41608); // Shattrath Flask of Relentless Assault
		else if (GetPlayer()->HasAura(41609))
			GetPlayer()->RemoveAurasDueToSpell(41609); // Shattrath Flask of Fortification
		else if (GetPlayer()->HasAura(45373))
			GetPlayer()->RemoveAurasDueToSpell(45373); // Bloodberry Elixir
	}

**Comment by PadreWoW** [comment]
Please check it :)

**Comment by PadreWoW** [comment]
But stats are not clear even with my fix - just remove icon :(

**Comment by LordUsagi** [comment]
I think the flask aura has a TRIGGER aura too thats hidden, and perhaps thats why you dont see stats getting added/removed

**Comment by PadreWoW** [comment]
Yep that's right

**Comment by PadreWoW** [comment]
I found it yesterday
Fix will be here today
![untitled](https://cloud.githubusercontent.com/assets/6802530/23888679/3c8eef0a-089a-11e7-8838-8565dd52e9ff.png)

**Comment by PadreWoW** [comment]
Add this to SpellAuras.cpp to void Aura::_RemoveAura()

`
if (m_spellProto->Id == 46839)
		m_target->RemoveAurasDueToSpell(46840);
	else if (m_spellProto->Id == 41611)
		m_target->RemoveAurasDueToSpell(41604);
	else if (m_spellProto->Id == 46837)
		m_target->RemoveAurasDueToSpell(46838);
	else if (m_spellProto->Id == 41610)
		m_target->RemoveAurasDueToSpell(41605);
	else if (m_spellProto->Id == 41608)
		m_target->RemoveAurasDueToSpell(41606);
	else if (m_spellProto->Id == 41609)
		m_target->RemoveAurasDueToSpell(41607);
	else if (m_spellProto->Id == 45373)
		m_target->RemoveAurasDueToSpell(45374);
`

**Comment by PadreWoW** [comment]
all works fine - tested
not so gracefully but it works......

**Comment by PadreWoW** [comment]
Anyone tested my fix?

**Comment by Zaffy** [comment]
Not yet. I will test it soon and let you let you know or merge it.

**Comment by LordUsagi** [comment]
Don't

**Comment by Zaffy** [comment]
Why?

**Comment by PadreWoW** [comment]
any news?

**Comment by Zaffy** [comment]
Looking into it. Your code is a hackfix. I try to find a proper way that would fix all things of this kind.

**Comment by AbraKabastard** [comment]
I'm going to apply a hackfix for this. But, @PadreWoW are you sure that you shouldnt be able to use the elixirs outside of dungeon? even if affect dont apply?
