### ISSUE TITLE
Lockpicking on items, crash

### ISSUE THREAD

**Issue by amaroc** [OregonCore/OregonCore#1538]
**Revision**:
OregonCore Rev: 3602  (Unix,little-endian)
**Operating system**:
Ubuntu 16.04

**Current behavior**: 
.additem 21842:20
Put on 21842 from stack to your bag in another slot.
Cast (Lockpicking) http://ru.wowhead.com/spell=1809 on 21842 (not on stack).
When cast goes, move this item to your stack back. 
Well done. We crash server.
+ another behavior without crash:
Use lockpicking on item 21842 or another item, it will delete it.

**Expected behavior**: 
Red text message, when you tried use Lockpicking on bad items like cloth, or weapons etc..

**Steps to reproduce the problem**:
* I wrote it on the "current behavior" section.

[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
i am sorry dont have crash report, server compiled without debug mode.

**Comment by PadreWoW** [comment]
Not confirmed (last rev.)

![untitled1](https://cloud.githubusercontent.com/assets/6802530/24344024/30f0a5a2-12d2-11e7-9871-396b9bf14469.png)

**Comment by amaroc** [comment]
All works perfectly on my rev. Try do it on [Netherweave cloth], maybe on green items it dosn't work.
I did it again.
Crash log:
https://pastebin.com/5pMuw7eL
1. .additem 20 [Netherweave cloth]  (not imbued).
2.  Place 1x[Netherweave cloth] to another slot in bag.
3.  Cast on 1x[Netherweave cloth]  lockpicking
4. On time when it casting move netherweave cloth back to 19xNetherweave cloth.
Done.

**Comment by PadreWoW** [comment]
Not confirmed

![untitled](https://cloud.githubusercontent.com/assets/6802530/24416390/47c0f6ee-13ed-11e7-8a80-0277969c640c.png)

**Comment by amaroc** [comment]
Revision: 3797
Ubnt 16.04
Clean core without path`es.
Crash log: https://pastebin.com/hM7zKeqp

@PadreWoW  move one netherweave cloth x1, use loockpicking on it, then move it back to x199 stack (only when cast is goes not after).

**Comment by PadreWoW** [comment]
I can not use loockpicking on it, - i see INVALID TARGET immediately

**Comment by AbraKabastard** [comment]
Can confirm all
