### ISSUE TITLE
Pet commands crashes the server (CRITICAL!!!!)

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1542]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
Do this:
Attack any mob -> put your pet to aggressive or defensive -> your pet start to attack this mob -> push "Follow" or "Stay" command when pet in combat -> Crash

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Tested on clear core without any third-party patches

![untitled1](https://cloud.githubusercontent.com/assets/6802530/24346248/28d5a638-12dc-11e7-8213-332258fc33dd.png)

**Comment by PadreWoW** [comment]
p.s push "Follow" or "Stay" command several times

**Comment by PadreWoW** [comment]
Video:

https://www.4shared.com/zip/5_egE_h2ei/Video.html

**Comment by ljwlaji** [comment]
Dose it Happened before Fix The Eye of Beast spell?

**Comment by PadreWoW** [comment]
It happens on LAST rev

**Comment by PadreWoW** [comment]
I did not check old revs

**Comment by amaroc** [comment]
Rev. 3602.
Cannot confirm.
What i do:
1. Start range attack mob (right click on it)
2. My pet on passive mode and "follow for me"
3. I click defense or agressive mode
4. Pet start atack target
5. I click many times random Follow\Stop Follow Cntrl+2 \ Cntrl+3 
No crash.

**Comment by PadreWoW** [comment]
Crash dump

[3781_oregon-core.exe_[31-3_11-33-59].txt](https://github.com/OregonCore/OregonCore/files/884974/3781_oregon-core.exe_.31-3_11-33-59.txt)

Video
https://www.4shared.com/get/0w4gZF96ei/crash.html

**Comment by PadreWoW** [comment]
3602 is VERY OLD rev
I tested it on 3781
check my video and dump

**Comment by PadreWoW** [comment]
Debugging dump points here:

![untitled2](https://cloud.githubusercontent.com/assets/6802530/24548267/001d8190-161d-11e7-9146-0621fe085170.png)

**Comment by PadreWoW** [comment]
PROBLEM FOUND!

THIS IS IT!

https://github.com/OregonCore/OregonCore/commit/2c59e0c3460b6a0d06a783f5fc8d58670bdd491b

**Comment by PadreWoW** [comment]
I was wrong
Problem is not found yet

**Comment by PadreWoW** [comment]
Problem with pet's spell - scorpid poison

**Comment by PadreWoW** [comment]
Spell IDs
24640
24641
24583
24584
24586
24588
24587
24589
27060
27361

**Comment by DanielBallaSZTE** [comment]
Okay so on the picture you linked.
I am just guessing.
Isn't it an overindexing issue with the array? `ASSERT(index + 1 < m_valuesCount`
Try it with changing it to `ASSERT(index < m_valuesCount`

I think that could be the issue. Not sure though.

**Comment by PadreWoW** [comment]
What array? where? what .cpp?
What are you talking about?

**Comment by PadreWoW** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/6802530/24653516/ce1e385e-193e-11e7-9a63-1671f892f71e.png)

**Comment by amaroc** [comment]
@PadreWoW he talks about OregonCore/src/game/Object.h:236
235:         {
236:             ASSERT(index + 1 < m_valuesCount || PrintIndexError(index , false));
237:             return *((uint64*) & (m_uint32Values[ index ]));

Also, can confirm, checked this at last rev (3797). Did it with same pet.

Btw, my pet same as your, don`t have "scropid poisons spells".  He have only one spell (lighting bolt) and this spell was "disabled", so i just did as you wrote and get crash.

**Comment by amaroc** [comment]
@DanielBallaSZTE i tried compile as you wrote (without + 1 ) and get same crash.
```
235:         {
236:             ASSERT(index < m_valuesCount || PrintIndexError(index , false)); // was index + 1
237:             return *((uint64*) & (m_uint32Values[ index ]));
```
I think problem not in this file (Object.h) - this file has changed more then 10 months. On 3602 rev (December 2016) i dont get this crash.

I also found strange behavior:
On my pet bar "Lighting bolt" shows as "Disabled" for auto-use by pet. Bet when i open Spell book\Pet spells i see that this spell is "Acitve" for auto-use.
![123](https://cloud.githubusercontent.com/assets/4218383/24662704/8a013f70-195e-11e7-9719-8ab6e7a2b5bc.png)

Also i get crash when this spell is disabled on pet spell bar and in spell book.

**Comment by PadreWoW** [comment]
there are TWO causes
1) Bug with commands
2) Bug with scropid poisons spells
Each of them leads to a crash

**Comment by PadreWoW** [comment]
1 fix - Roll back commit: https://github.com/OregonCore/OregonCore/commit/2c59e0c3460b6a0d06a783f5fc8d58670bdd491b
2 temporary fix - add scropid poisons spells to DISABLES (not a really fix but removes crashes)

**Comment by Macsimka** [comment]
I think need check me->GetVictim() here.
https://github.com/OregonCore/OregonCore/blob/fda0dced92301dab4eb41948929f62b660986678/src/game/PetAI.cpp#L575
Anyway need debug this, it's should be easy.
