### ISSUE TITLE
Quest Corrupted Sabers - FIX Here

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1543]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
Quest Corrupted Sabers is not working

**Expected behavior**: 
...
This is the Fix:

`UPDATE `world`.`creature_template` SET `AIName` = 'EventAI' WHERE `entry` = '9937'; 
INSERT INTO `world`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES (993701, '9937', '1', '0', '100', '0', '1500', '1500', '0', '0', '3', '9936', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Model Change Small Corrupted'); 
INSERT INTO `world`.`creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES (993702, '9937', '1', '0', '100', '0', '3500', '3500', '0', '0', '3', '10042', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Model Change Big Corrupted'); 

-- Insert Gossip /custom made id/
DELETE FROM `gossip_menu_option` WHERE `menu_id`=55002 AND `id`=1;
INSERT INTO `gossip_menu_option` (`menu_id`,`id`,`option_icon`,`option_text`,`option_id`,`npc_option_npcflag`,`action_menu_id`) VALUES
(55002,1,0,'I want to release the saber to Winna.',1,131,0);
-- Only show gossip if near Winna
DELETE FROM `conditions` WHERE `SourceGroup`=55002 AND `SourceTypeOrReferenceId`=15;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES 
(15,55002,1,0,29,1,9996,5,0,0,0,'','Only show second gossip Corrupted Saber is near Wina in 5 yards');

INSERT INTO `world`.`gossip_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('50002', '0', '7', '4506', '30', '0', '-10291.2', '-4315.28', '-38.382', '4.07'); 
INSERT INTO `world`.`gossip_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES ('50002', '0', '18', '2000', '0', '0', '-10291.2', '-4315.28', '-38.382', '4.07'); 
UPDATE `world`.`gossip_menu_option` SET `action_script_id` = '50002' WHERE `menu_id` = '55002' AND `id` = '1';`

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Selphius** [comment]
EventAI part seems to work fine for me.
Second part (Gossip) doesn't.
When corrupted cat is near Winna though, ( <5 yards) gossip on cat doesn't appear to release it and complete the quest.

**Comment by PadreWoW** [comment]
All works fine

![untitled4](https://cloud.githubusercontent.com/assets/6802530/24364467/82e35cbc-131b-11e7-9a8e-d063f99c2d9d.png)

**Comment by Selphius** [comment]
Still doesn't work for me. Deleted all records from the tables, then added them again ony by one without errors. I changed even value to 10 yards. And still the same no gossip menu or anything. I set gossip flag on cat to see if he even has any gossip when near this Winna, but he only has empty box with "Greetings name"

**Comment by PadreWoW** [comment]
Maybe wrong cat? I use common kitten all the time

**Comment by Selphius** [comment]
![wowscrnshot_032717_205202](https://cloud.githubusercontent.com/assets/13300602/24372756/4c5191d2-132f-11e7-8357-16d58aec4577.jpg)

Cat entry: 9937

**Comment by PadreWoW** [comment]
This is my kitten's stats
Try it

INSERT INTO `world`.`creature_template` (`entry`, `heroic_entry`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `class`, `race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `ManaModifier`, `HealthModifier`, `RacialLeader`, `RegenHealth`, `equipment_id`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES ('9937', '0', '0', '0', '9990', '0', '9990', '0', 'Common Kitten', NULL, NULL, '55002', '1', '1', '-1', '64', '64', '0', '0', '20', '188', '1', '1', '1.14286', '1', '0', '1', '1', '0', '7', '2000', '2200', '1', '0', '0', '0', '0', '0', '0', '0', '1.76', '2.42', '100', '12', '0', '0', '0', '100008', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'EventAI', '0', '3', '1', '1', '0', '1', '0', '0', '2', '');

**Comment by Selphius** [comment]
Ok, I already see where must have been the problem: 
gossip_menu_id in creature_template. Now I see you have it set here too ;]
Gonna test it later. Thanks.

Ps. why won't you commit your fix?

Edit: Yep, works fine now.

**Comment by PadreWoW** [comment]
I don't know how to commit it :)
