### ISSUE TITLE
Quest Patience and Understanding Bugged

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1544]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
....
Player can not attack Sal'salabim in Shattrath

**Expected behavior**: 
...
Sal'salabim should become enemy and attack player whe player try to ask him about The Master Planner's Blueprints (gossip in core)

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Selphius** [comment]
Can't reproduce it. 

I have it working properly on clean core. I add myself a quest "10004", go talk to him, select gossip -> he turns hostile and i can fight back normally with GM off, at low hp he turns friendly and can end quest.

So maybe you changed something in Script/DB?

**Comment by PadreWoW** [comment]
Tested right now on last clear core
bugged
after you talk to Salabim he talk demon's speech and do nothing then

![untitled2](https://cloud.githubusercontent.com/assets/6802530/24364206/afb06a6a-131a-11e7-84fe-8111cd9b9e3d.png)

![untitled3](https://cloud.githubusercontent.com/assets/6802530/24364212/b44f505e-131a-11e7-9cf1-8f5aa28a5033.png)

**Comment by Selphius** [comment]
How it looks for me. 

![wowscrnshot_032717_182257](https://cloud.githubusercontent.com/assets/13300602/24366792/823b7b92-131a-11e7-9481-0ffaf6a3fc30.jpg)
![wowscrnshot_032717_182301](https://cloud.githubusercontent.com/assets/13300602/24366793/846b0fa4-131a-11e7-9942-919effda37e6.jpg)

Check this values, maybe you have them changed.

`#define FACTION_HOSTILE_SA              90`
`#define FACTION_FRIENDLY_SA             35`

`bool GossipSelect_npc_salsalabim(Player* player, Creature* pCreature, uint32 /*sender*/, uint32 action)
{
	if (action == GOSSIP_ACTION_INFO_DEF + 1)
	{
		player->CLOSE_GOSSIP_MENU();
		DoScriptText(SAY_DEMONIC, pCreature);
		pCreature->setFaction(FACTION_HOSTILE_SA);
		((npc_salsalabimAI*)pCreature->AI())->AttackStart(player);
	}
	return true;
}`

**Comment by Selphius** [comment]
Ok, seems like I managed to reproduce it. I used old maps up to this moment. 
I deleted maps folder, and created new maps by map extractor. After that when I tried this quest, NPC indeed doesn't change faction to hostile one, which is simply weird. Why would "maps" affect the script's faction change.

**Comment by PadreWoW** [comment]
Yep. I tested him on tester`s island and all works fine.

**Comment by PadreWoW** [comment]
This problem in whole Shattrath - not only in tavern

**Comment by PadreWoW** [comment]
+1 Problem with quest "What Book I Don't See Any Book"

![untitled1](https://cloud.githubusercontent.com/assets/6802530/24398950/dc04fc18-13b3-11e7-945f-1fd020b74761.png)

Whole Shattrath bugged.......

**Comment by PadreWoW** [comment]
5303522.map - Shattrath World's End Tavern

**Comment by Selphius** [comment]
quest "What Book I Don't See Any Book" works fine for me with this maps. He turns hostile and can complete the q if i beat him down. Only problem is his lackeys turn hostile for a 0.5s and turn back neutral and go back to sleep.

**Comment by PadreWoW** [comment]
We need new maps......

**Comment by Selphius** [comment]
Lackey's won't work until maps are fixed it seems. Same goes for Sal'labim from tavern.
Well at least you made me test Quest "What Book I Don't See Any Book" and I found it can only be done once, after that no one can do it - no reset function, to make event `Done = false` so other people can attempt it. I mean there is in void Reset(), but it's never called upon.

**Comment by PadreWoW** [comment]
any news?
can we return old MAPS?

**Comment by DanielBallaSZTE** [comment]
Maps are bugged indeed, for me they don't even display the zone I'm in.
This is going to be a huge rework, I decided to help OregonCore not to die, so I'm starting to fix things here and there. 
As soon as I'm finished with my exams I'm going to start reworking the current system.

**Comment by PadreWoW** [comment]
Hi!
Any news?

**Comment by DanielBallaSZTE** [comment]
Just finished my last exam this day, from now on I'll have time to work on the core.

**Comment by PadreWoW** [comment]
Hi! Any news?
