### ISSUE TITLE
Curse of the Elements - stackable 

### ISSUE THREAD

**Issue by amaroc** [OregonCore/OregonCore#1546]
**Revision**:
3602
**Operating system**:
ubnt 16.04 

**Current behavior**: 
This spell  CoE ( http://tbc.openwow.com/spell=27228 ) can be stackable on boss and mobs (i think also on players).  So its better to have 15 warlocks in raid, and you get +150%  spell damage on boss minumum or 195% with 15 affliction warlocks.. 

**Expected behavior**: 
1. This curse  (only CoE, i dont know  about  [Curse of Recklessness]) must be one at one target.
2. More powerfull curse with (Melediction 1\3++) can remove previous CoE with 0\3 in Melediction. Etc..
3. Same curse with same "melediction ( http://tbc.openwow.com/spell=32484 )" from another warlock, can remove this curse, and just "update" time.

**Comment by PadreWoW** [comment]
very old rev
try the last one

**Comment by amaroc** [comment]
@PadreWoW why do you leave 3 same comments, and don't wish check on your last revision? I did it on last rev, and get same result. You get something for "3 comments"?

![screenshot from 2017-04-04 18-07-29](https://cloud.githubusercontent.com/assets/4218383/24663787/96e77cb0-1961-11e7-8284-1263278b43bb.png)

**Comment by PadreWoW** [comment]
There is no SPELL_GROUP_STACK_RULE_EXCLUSIVE_SAME_EFFECT = 3 :(

**Comment by PadreWoW** [comment]
This can help

https://gitorious.org/spepew/viola/commit/89bae3b51c5208931bb3b409f8092e07c55b80e3

**Comment by AbraKabastard** [comment]
All curses should be only stackable per 1 warlock right?
