### ISSUE TITLE
Fly mount and.st bug

### ISSUE THREAD

**Issue by amaroc** [OregonCore/OregonCore#1547]
**Revision**:
3602 

**Operating system**:
ubnt 16.04
**Current behavior**: 
1. If you on fly mount, and you use .st  command you will be ported to start zone and can fly.
2. Same things happens on portals in Shattrat, when you in Swift Flight Form  (Druid) .learn 40120
3. Also you can use fly mount near wall, if you do it "right" you can also fly. So you dont have fly mount buff, but have fly aura and speed.

**Expected behavior**: 
1. When you use .st, it`s clear you from all auras\buff.
2. When you use portal, its also clear you from "fly" auras buffs
3. When you use fly mount, fly & speed aura must appears and disapear when "Fly mount buff" appears and disapears.

PS: dont checked but maybe when you summon people on mount or with Druid flyght form, maybe he can fly without this buff too.

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
very old rev
try the last one

**Comment by amaroc** [comment]
@PadreWoW please dont make same comments again before you dont check it. Its just "bla-bla-bla".

So i checked it on last rev 3797 and all this bugs works fine.

1.If you on fly mount, and you use .st command you will be ported to start zone and can fly.
2.Same  things happens on portals in Shattrat, when you in Swift Flight Form (Druid) .learn 40120
3.Also you can use fly mount near wall, if you do it "right" you can also fly. So you dont have fly mount buff, but have fly aura and speed.

For  #3 bug, i have 2 screenshots, where it 100% works (some walls in shattrat dont dismount you).
![screenshot from 2017-04-04 18-37-49](https://cloud.githubusercontent.com/assets/4218383/24665486/36763556-1966-11e7-8da7-8e43b8b5523c.png)
![screenshot from 2017-04-04 18-37-42](https://cloud.githubusercontent.com/assets/4218383/24665578/791e951a-1966-11e7-955a-e4f8fb98b040.png)

so .tele shadowmoon then goes to ally base (first screen on map). And then stay where i point on second screenshot and use mount, if you got "dismount" now you can easy fly and kill all mobs in "fly".

**Comment by DanielBallaSZTE** [comment]
A possible fix would be checking player movement on the issue of .st command

**Comment by DanielBallaSZTE** [comment]
Can confirm the second.

**Comment by DanielBallaSZTE** [comment]
So I could reproduce the second one, and fixed it.

**Comment by Thema89** [comment]
**Issue n°1:** @amaroc you should remember to **always test in GM OFF**. This is the major cause of fake-reports and fake-bugs reporting I've ever seen during these years. If you try it in GM off (or even better, using a non GM account so you can't fail), you'll see _it is working as intended_. Surely it still needs to be fixed as it's not normal even for a GameMaster, btw it's not a big issue. So I confirm these bug and it can be reproduced, BUT only for GameMasters (_GM on_) using .start and not for players.
Plus, it can be reproduced even by using .tele while being in _GM on_ and mounted.

**Issue n°2:** good job @DanielBallaSZTE! _"informal LGTM"_ for you too, also tested and it works fine.

**Issue n°3:** it hasn't been easy, but confirmed! Here's a more straight-forward way to reproduce (try more than once if doesn't reproduce at first try):
• _.tele wildhammer_
• _.go xyz -4065.578125 2143.758057 110.629860_  (will teleport you to that exact position)
• summon your flying mount (will dismount and debuff, but you will be able to fly at 1x speed)
