### ISSUE TITLE
Aggro on dead body

### ISSUE THREAD

**Issue by amaroc** [OregonCore/OregonCore#1548]
**Revision**:
3602

**Operating system**:
16.04 ubnt
**Current behavior**: 
On first boss ManaTombs heroic, i saw how boss stucked on tank after tank (player) dead. And boss continius attack dead body of tank. Same things i saw on another instance but now cant remember where exactly.

**Expected behavior**: 
Must drop agro and switch target.

**Steps to reproduce the problem**:
Go to manatombs with party,  get agro by tank, die,  and watch. Maybe it occurs not often (dont tested it).

**Comment by PadreWoW** [comment]
very old rev
try the last one

**Comment by markvetwow** [comment]
Confirm this issue on last rev 3797+.

**Comment by DanielBallaSZTE** [comment]
Is it just the boss in ManaTombs or happens to other creatures too? If so there's a problem in CreatureAI.cpp, I've seen something in the code, there's a few strange cases of rechecks there exactly for that case, seems like they didn't succeed making it work.

**Comment by PadreWoW** [comment]
no fix?
