### ISSUE TITLE
Does HellGroundCore or MangosOne Can Check AntiCheat？

### ISSUE THREAD

**Issue by ljwlaji** [OregonCore/OregonCore#1549]
**Revision**:

**Operating system**:

**Current behavior**: 
....

**Expected behavior**: 
...

**Steps to reproduce the problem**:

Wonder if those core can find the client using anticheat,we can move the check sum to Oregon
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Desteny** [comment]
First of all if your are talking about Anticheat and Checksums, you probably interested in `Warden Checks`
As far as i know Mangos doesn't have more rules then the normal public available set (maybe not even those) Hellground had the standard once and added some more, but only a few are on public leaks of hellgroundcore. but how ever with those few checks ~10 you will never dedect all cheat programms out there.
Trinity for example has done about 800 - 900 checks for WOTLK but don't even they have a 100% solution (100% probably will never be reached)
