### ISSUE TITLE
Very weak attack with Warlock's Shadow Bolt 1 rank (ONLY HORDE WARLOCKS!)

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1550]
**Revision**:
last
**Operating system**:
Serv2008R2
**Current behavior**: 
Very weak attack with Warlock's Shadow Bolt 1 rank (ONLY HORDE WARLOCKS!)
Should be 12-16 but it's only 3-6

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Bug is here:

https://github.com/OregonCore/OregonCore/commit/5a0e00a2c9c09296c80ba0421c2b281ee45b3ce5

**Comment by PadreWoW** [comment]
I think problem is somewhere HERE:

`
if ((schools & 1) && school != SPELL_SCHOOL_NORMAL && school != SPELL_SCHOOL_HOLY)
        {
			sLog.outError("11");
            // Base victim resistance
            uint32 amount = GetResistance(SpellSchools(school));
            // Add SPELL_AURA_MOD_TARGET_RESISTANCE aura value at caster
            // Negative value is spell penetration, but effective resistance can't be negative since betas
            if (const int32 casterMod = attacker->GetTotalAuraModifierByMiscMask(SPELL_AURA_MOD_TARGET_RESISTANCE, (1 << school)))
                amount = uint32(std::max((int32(amount) + casterMod), 0));
            if (!amount)
            {
				sLog.outError("12");
                resistance = 0; // No resistance for this school: use it!
                break;
            }
            else if (!resistance || amount < resistance)
                resistance = amount;    // First school encountered or more vulnerable: memorize and continue
        }
`

**Comment by PadreWoW** [comment]
sLog.outError("11");
sLog.outError("12");

are my debug logs
And i saw that Alliance warlock has sLog.outError("12"); when casts Shadow Bolt - that means resistance = 0;
and Horde Warlock has NO this point!

**Comment by PadreWoW** [comment]
I think the cause is racial resistances !
This code uses CASTER resistances - not victim....

**Comment by PadreWoW** [comment]
Maybe this can help?

https://github.com/blueboy/portalclassic/blob/master/src/game/Unit.cpp

**Comment by PadreWoW** [comment]
float ratio = float(float(resistance) / (attacker->getLevelForTarget(this) * 5)) * 0.75f; - this is not right

float(resistance) is always 0 -> ration is always 0

**Comment by PadreWoW** [comment]
float ratio = float(float(resistance) / (attacker->getLevelForTarget(this) * 5)) * 0.75f; - is not right
for example:
float resistance = 10
attacker->getLevelForTarget(this) = 1 lvl
(10/1*5) * 0.75 = 1.5

return std::min(ratio, 0.75f);
return std::min(1.5, 0.75f); -> return 0.75 !!!!!!!

when 1 lvl player has 10 resistance he will take only 25% damage!!!!!

**Comment by PadreWoW** [comment]
May be float ratio = float(float(resistance) / (attacker->getLevelForTarget(this) * **75**)) * 0.75f; ?

**Comment by PadreWoW** [comment]
any news? :(

**Comment by PadreWoW** [comment]
problem is still here :((((
my fix is completely wrong :((((
can anyone help?

**Comment by AbraKabastard** [comment]
I tried on both a Horde and Alliance character, both level 1. Hitting a target dummy that was also level 1. Damage was consistently 4 or 5 on both factions and both had spikes of about 8 damage.

Characters were Human and Orc.

**Comment by PadreWoW** [comment]
Should be 12-16

**Comment by PadreWoW** [comment]
With my fix, damage become normal
float ratio = float(float(resistance) / (attacker->getLevelForTarget(this) * **75**)) * 0.75f;

**Comment by AbraKabastard** [comment]
I'm looking at this http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance#toc and it is for TBC but it looks like formulas in core are correct. Problem might be somewhere else.

**Comment by PadreWoW** [comment]
Problem in resistance
I sad it a long time ago
return std::min(ratio, 0.75f);
return std::min(1.5, 0.75f); -> return 0.75 !!!!!!!

when 1 lvl player has 10 resistance he will take only 25% damage!!!!!

**Comment by PadreWoW** [comment]
Test player with shadow resistance and you will see it

**Comment by PadreWoW** [comment]
and problem not only with shadow resistance, but with all resistance in game
and resistance on player will REDUCE damage to mobs!!!!! this is completely wrong
This code uses CASTER resistances - not victim....

**Comment by AbraKabastard** [comment]
I'm going to fix this to day. This is a big bug!

**Comment by AbraKabastard** [comment]
Good work man. Couldn't have done it without you!

**Comment by PadreWoW** [comment]
Joking? My knowledge in c++ is small. Just simple codes for quests and mobs :)

**Comment by AbraKabastard** [comment]
No joke. You saved me big time by showing me where to look.
