### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by CrawDance** [OregonCore/OregonCore#1552]
**Revision**: last

**Operating system**: server 2008 r2

**Current behavior**:  It crashes somehow due to a gobject it seems
....

**Expected behavior**: It shouldnt get a crash  ¯\_(ツ)_/¯ 
...

**Steps to reproduce the problem**:

Screen shot : http://i.imgur.com/KP86p3j.png

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
184555 and 183203 are nonstandard GOs - you create them yourself and this is your own bug

![untitled3](https://cloud.githubusercontent.com/assets/6802530/24740641/e11317e6-1aaa-11e7-840e-eb4d10b8fdaa.png)

**Comment by CrawDance** [comment]
Not only this error , but also a few more DB Errors , I applied this [DB](https://github.com/OregonCore/OregonCore/releases) 20/Jan/2017
And I didn't modify the core too , But it is very un-stable.

**Comment by Selphius** [comment]
If you downloaded this DB 20/Jan/2017, then you also need to update all changes related to DB from OregonCore/sql/updates OR if you use autopatcher it is done automatically.
PadreWoW said what causes it for you. I am working on clean core and I am not experiencing this

**Comment by CrawDance** [comment]
I've applied the updates too. But I've no clue why these errors happen.

**Comment by AbraKabastard** [comment]
No crash log attached to crash issue.
