### ISSUE TITLE
errors on build how to fix that?

### ISSUE THREAD

**Issue by princesbem** [OregonCore/OregonCore#1555]
Error	1	error LNK2019: unresolved external symbol _mysql_server_init@12 referenced in function "public: __thiscall Database::Database(void)" (??0Database@@QAE@XZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	2	error LNK2019: unresolved external symbol _mysql_server_end@0 referenced in function "public: __thiscall Database::~Database(void)" (??1Database@@QAE@XZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	3	error LNK2019: unresolved external symbol _mysql_thread_init@0 referenced in function "public: void __thiscall Database::ThreadStart(void)" (?ThreadStart@Database@@QAEXXZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	4	error LNK2001: unresolved external symbol _mysql_thread_init@0	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(SqlDelayThread.obj)	oregon-core
Error	5	error LNK2019: unresolved external symbol _mysql_thread_end@0 referenced in function "public: void __thiscall Database::ThreadEnd(void)" (?ThreadEnd@Database@@QAEXXZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	6	error LNK2001: unresolved external symbol _mysql_thread_end@0	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(SqlDelayThread.obj)	oregon-core
Error	7	error LNK2019: unresolved external symbol _mysql_fetch_fields@4 referenced in function "private: bool __thiscall Database::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@Database@@AAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	8	error LNK2001: unresolved external symbol _mysql_fetch_fields@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	9	error LNK2019: unresolved external symbol _mysql_field_count@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	10	error LNK2019: unresolved external symbol _mysql_affected_rows@4 referenced in function "private: bool __thiscall Database::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@Database@@AAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	11	error LNK2019: unresolved external symbol _mysql_error@4 referenced in function "protected: bool __thiscall Database::DirectExecute(bool,char const *)" (?DirectExecute@Database@@IAE_N_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	12	error LNK2019: unresolved external symbol _mysql_set_character_set@8 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	13	error LNK2019: unresolved external symbol _mysql_init@4 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	14	error LNK2019: unresolved external symbol _mysql_real_connect@32 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	15	error LNK2019: unresolved external symbol _mysql_query@8 referenced in function "protected: bool __thiscall Database::DirectExecute(bool,char const *)" (?DirectExecute@Database@@IAE_N_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	16	error LNK2019: unresolved external symbol _mysql_real_query@12 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	17	error LNK2019: unresolved external symbol _mysql_store_result@4 referenced in function "private: bool __thiscall Database::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@Database@@AAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	18	error LNK2019: unresolved external symbol _mysql_use_result@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	19	error LNK2019: unresolved external symbol _mysql_set_server_option@8 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	20	error LNK2019: unresolved external symbol _mysql_get_server_info@4 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	21	error LNK2019: unresolved external symbol _mysql_get_client_info@0 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	22	error LNK2019: unresolved external symbol _mysql_options@12 referenced in function "public: bool __thiscall Database::Initialize(char const *)" (?Initialize@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	23	error LNK2019: unresolved external symbol _mysql_free_result@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	24	error LNK2001: unresolved external symbol _mysql_free_result@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	25	error LNK2019: unresolved external symbol _mysql_real_escape_string@16 referenced in function "public: unsigned long __thiscall Database::escape_string(char *,char const *,unsigned long)" (?escape_string@Database@@QAEKPADPBDK@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	26	error LNK2019: unresolved external symbol _mysql_thread_safe@0 referenced in function "public: __thiscall Database::Database(void)" (??0Database@@QAE@XZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	27	error LNK2019: unresolved external symbol _mysql_stmt_init@4 referenced in function "private: struct PreparedStatement * __thiscall Database::_GetOrMakePreparedStatement(char const *,char const *,class PreparedValues *)" (?_GetOrMakePreparedStatement@Database@@AAEPAUPreparedStatement@@PBD0PAVPreparedValues@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	28	error LNK2019: unresolved external symbol _mysql_stmt_prepare@12 referenced in function "private: struct PreparedStatement * __thiscall Database::_GetOrMakePreparedStatement(char const *,char const *,class PreparedValues *)" (?_GetOrMakePreparedStatement@Database@@AAEPAUPreparedStatement@@PBD0PAVPreparedValues@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	29	error LNK2019: unresolved external symbol _mysql_stmt_execute@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	30	error LNK2019: unresolved external symbol _mysql_stmt_store_result@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	31	error LNK2019: unresolved external symbol _mysql_stmt_param_count@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	32	error LNK2019: unresolved external symbol _mysql_stmt_attr_set@12 referenced in function "private: struct PreparedStatement * __thiscall Database::_GetOrMakePreparedStatement(char const *,char const *,class PreparedValues *)" (?_GetOrMakePreparedStatement@Database@@AAEPAUPreparedStatement@@PBD0PAVPreparedValues@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	33	error LNK2019: unresolved external symbol _mysql_stmt_bind_param@8 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	34	error LNK2019: unresolved external symbol _mysql_stmt_close@4 referenced in function "public: __thiscall Database::~Database(void)" (??1Database@@QAE@XZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	35	error LNK2019: unresolved external symbol _mysql_stmt_reset@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	36	error LNK2001: unresolved external symbol _mysql_stmt_reset@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	37	error LNK2019: unresolved external symbol _mysql_stmt_free_result@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	38	error LNK2001: unresolved external symbol _mysql_stmt_free_result@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	39	error LNK2019: unresolved external symbol _mysql_stmt_error@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	40	error LNK2001: unresolved external symbol _mysql_stmt_error@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	41	error LNK2019: unresolved external symbol _mysql_stmt_num_rows@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	42	error LNK2001: unresolved external symbol _mysql_stmt_num_rows@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	43	error LNK2019: unresolved external symbol _mysql_stmt_field_count@4 referenced in function "private: bool __thiscall Database::_ExecutePreparedStatement(struct PreparedStatement *,class PreparedValues *,char * *,bool)" (?_ExecutePreparedStatement@Database@@AAE_NPAUPreparedStatement@@PAVPreparedValues@@PAPAD_N@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	44	error LNK2001: unresolved external symbol _mysql_stmt_field_count@4	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	45	error LNK2019: unresolved external symbol _mysql_commit@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	46	error LNK2019: unresolved external symbol _mysql_rollback@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	47	error LNK2019: unresolved external symbol _mysql_autocommit@8 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	48	error LNK2019: unresolved external symbol _mysql_next_result@4 referenced in function "public: bool __thiscall Database::ExecuteFile(char const *)" (?ExecuteFile@Database@@QAE_NPBD@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	49	error LNK2019: unresolved external symbol _mysql_close@4 referenced in function "public: __thiscall Database::~Database(void)" (??1Database@@QAE@XZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(Database.obj)	oregon-core
Error	50	error LNK2019: unresolved external symbol _mysql_fetch_row@4 referenced in function "public: bool __thiscall QueryResult::NextRow(void)" (?NextRow@QueryResult@@QAE_NXZ)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	51	error LNK2019: unresolved external symbol _mysql_stmt_fetch@4 referenced in function "public: __thiscall PreparedQueryResult::PreparedQueryResult(struct st_mysql_stmt *)" (??0PreparedQueryResult@@QAE@PAUst_mysql_stmt@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	52	error LNK2019: unresolved external symbol _mysql_stmt_bind_result@8 referenced in function "public: __thiscall PreparedQueryResult::PreparedQueryResult(struct st_mysql_stmt *)" (??0PreparedQueryResult@@QAE@PAUst_mysql_stmt@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	53	error LNK2019: unresolved external symbol _mysql_stmt_result_metadata@4 referenced in function "public: __thiscall PreparedQueryResult::PreparedQueryResult(struct st_mysql_stmt *)" (??0PreparedQueryResult@@QAE@PAUst_mysql_stmt@@@Z)	C:\Users\Administrator\Desktop\Build\src\oregoncore\shared.lib(QueryResult.obj)	oregon-core
Error	54	error LNK1120: 44 unresolved externals	C:\Users\Administrator\Desktop\Build\bin\Release\oregon-core.exe	oregon-core

**Comment by CrawDance** [comment]
install mysql 5.5 instead of 5.7
