### ISSUE TITLE
Guild Bank Log duplicates

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1556]
**Revision**:
last
**Operating system**:
2008R2
**Current behavior**: 
Guild Bank Log duplicates

**Expected behavior**: 
...

**Steps to reproduce the problem**:
Put some items to Guild Bank
See logs in GB log tab
Restart server
See duplicate logs

![image](https://cloud.githubusercontent.com/assets/6802530/25232995/f0aab98e-25e5-11e7-8f5b-59042d4d96fb.png)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Problem is in void Guild::DisplayGuildBankLogs(WorldSession* session, uint8 TabId)

Here:
`
else
    {
        // here we display current tab logs
        WorldPacket data(MSG_GUILD_BANK_LOG_QUERY, m_GuildBankEventLog_Item[TabId].size() * (4 * 4 + 1 + 1) + 1 + 1);
        data << uint8(TabId);                               // Here a real Tab Id
        // number of log entries
        data << uint8(m_GuildBankEventLog_Item[TabId].size());
        for (GuildBankEventLog::const_iterator itr = m_GuildBankEventLog_Item[TabId].begin(); itr != m_GuildBankEventLog_Item[TabId].end(); ++itr)
        {
            data << uint8(itr->LogEntry);
            data << uint64(MAKE_NEW_GUID(itr->PlayerGuid, 0, HIGHGUID_PLAYER));
            data << uint32(itr->ItemOrMoney);
            data << uint8(itr->ItemStackCount);
            if (itr->LogEntry == GUILD_BANK_LOG_MOVE_ITEM || itr->LogEntry == GUILD_BANK_LOG_MOVE_ITEM2)
                data << uint8(itr->DestTabId);              // moved tab
            data << uint32(time(NULL) - itr->TimeStamp);
        }
        session->SendPacket(&data);
    }

`

**Comment by PadreWoW** [comment]
part "FOR" starts two times after restart the server

**Comment by AbraKabastard** [comment]
This is much more complicated. It seems when retrieving guild event logs from database its doing it twice

**Comment by PadreWoW** [comment]
I have fix. Will place it here tomorrow

**Comment by PadreWoW** [comment]
Here is right code:
`
void ObjectMgr::LoadGuilds()
{
    Guild* newGuild;
    uint32 count = 0;

    //                                                    0             1          2          3           4           5           6
    QueryResult_AutoPtr result = CharacterDatabase.Query("SELECT guild.guildid,guild.name,leaderguid,EmblemStyle,EmblemColor,BorderStyle,BorderColor,"
                                 //   7               8    9    10         11        12
                                 "BackgroundColor,info,motd,createdate,BankMoney,COUNT(guild_bank_tab.guildid) "
                                 "FROM guild LEFT JOIN guild_bank_tab ON guild.guildid = guild_bank_tab.guildid GROUP BY guild.guildid ORDER BY guildid ASC");

    if (!result)
    {



        sLog.outString(">> Loaded %u guild definitions", count);
        return;
    }

    // load guild ranks
    //                                                                0       1   2     3      4
    QueryResult_AutoPtr guildRanksResult   = CharacterDatabase.Query("SELECT guildid,rid,rname,rights,BankMoneyPerDay FROM guild_rank ORDER BY guildid ASC, rid ASC");

    // load guild members
    //                                                                0       1                 2    3     4       5                  6
    QueryResult_AutoPtr guildMembersResult = CharacterDatabase.Query("SELECT guildid,guild_member.guid,rank,pnote,offnote,BankResetTimeMoney,BankRemMoney,"
            //   7                 8                9                 10               11                12
            "BankResetTimeTab0,BankRemSlotsTab0,BankResetTimeTab1,BankRemSlotsTab1,BankResetTimeTab2,BankRemSlotsTab2,"
            //   13                14               15                16               17                18
            "BankResetTimeTab3,BankRemSlotsTab3,BankResetTimeTab4,BankRemSlotsTab4,BankResetTimeTab5,BankRemSlotsTab5,"
            //   19               20                21                22               23                       24
            "characters.name, characters.level, characters.class, characters.zone, characters.logout_time, characters.account "
            "FROM guild_member LEFT JOIN characters ON characters.guid = guild_member.guid ORDER BY guildid ASC");

    // load guild bank tab rights
    //                                                                      0       1     2   3       4
    QueryResult_AutoPtr guildBankTabRightsResult = CharacterDatabase.Query("SELECT guildid,TabId,rid,gbright,SlotPerDay FROM guild_bank_right ORDER BY guildid ASC, TabId ASC");


    do
    {
        //Field *fields = result->Fetch();

        ++count;

        newGuild = new Guild;
        if (!newGuild->LoadGuildFromDB(result) ||
            !newGuild->LoadRanksFromDB(guildRanksResult) ||
            !newGuild->LoadMembersFromDB(guildMembersResult) ||
            !newGuild->LoadBankRightsFromDB(guildBankTabRightsResult) ||
            !newGuild->CheckGuildStructure()
           )
        {
            newGuild->Disband();
            delete newGuild;
            continue;
        }
        newGuild->LoadGuildEventLogFromDB();
        //newGuild->LoadGuildBankEventLogFromDB(); // This is an error string! I commented it out and all works fine
        newGuild->LoadGuildBankFromDB();
        AddGuild(newGuild);

    }
    while (result->NextRow());

    sLog.outString(">> Loaded %u guild definitions", count);
}
`
