### ISSUE TITLE
[Spells] Visual bug after interrupting.

### ISSUE THREAD

**Issue by markvetwow** [OregonCore/OregonCore#1560]
**Revision**: 3797+

**Operating system**: Win 8.1 x64

**Current behavior**: 

When you interrupting a target spell by any cause (kick,stun,fear etc.). Visual part of a spell doesn't disappear. So,on client side it looks,like creature is still casting,even after spell interrupting.

**Expected behavior**: 

Visual part of a spell must not shown,when creature don't cast.

**Steps to reproduce the problem**:

1. Pull any mob, i choosed Shadowmoon Warlock from BF (id:17371). Wait until Shadow Bolt or any other spell starts casting.
2. Interrupt spell by any source.
3. :(

**A little video appliaction to issue**:

[YouTube.com Link](https://youtu.be/vvoeeuUgSQw)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AbraKabastard** [comment]
This one is really bugging me!

**Comment by PadreWoW** [comment]
I have no this bug on my server, but i can not find my fix :) trying.... :)

**Comment by PadreWoW** [comment]
error somewhere in spell.cpp i'm shure! tested!

**Comment by PadreWoW** [comment]
Found!

Bug is HERE:

void Spell::SendInterrupted(uint8 result)
{
    WorldPacket data(SMSG_SPELL_FAILURE, (8 + 4 + 1));
    data << m_caster->GetObjectGUID();
    data << m_spellInfo->Id;
    data << result;
    m_caster->SendMessageToSet(&data, true);

    data.Initialize(SMSG_SPELL_FAILED_OTHER, (8 + 4));
	data << m_caster->GetObjectGUID(); <-------- ERROR!
    data << m_spellInfo->Id;
    m_caster->SendMessageToSet(&data, true);
}

Should be data << m_caster->GetPackGUID();

**Comment by AbraKabastard** [comment]
Freakin' amazing @padrewow
