### ISSUE TITLE
[Crash]the server crash when you create a Hunter character

### ISSUE THREAD

**Issue by Komaeda91** [OregonCore/OregonCore#1563]
**Revision**:the lastest version

**Operating system**:windows 2008R2

**Current behavior**: 
crash when create a Hunter character

**Expected behavior**: 
should not crash

**Steps to reproduce the problem**:

logon the game
create one hunter character
the server crash

**Comment by Desteny** [comment]
maybe wrong or invalid .dbc files?
extracted by the latest version of OC tools?

**Comment by kotishe** [comment]
No, i have this bug too

**Comment by kotishe** [comment]
But only if you summon pet, also warlock pet

**Comment by Desteny** [comment]
ok the summon pet crash is known, but author of this issue talks about the caracter creation it self, not even about the login to the world, for me it would be like the client crashs on character creation.

if there is a custom mod to add pets after car creation and you enter the world it could be the same crash

**Comment by Selphius** [comment]
Can't reproduce it, on my end everything seems to work fine. No crash.
Created hunter - no crash. Went and tamed beast - no crash. Called pet - no crash. Made pet attack - no crash. Made pet use skills - no crash. 
Same for warlock. Summoned imp - no crash. Made him attack and use skills - no crash.

Am I doing something wrong to reproduce it?

**Comment by Desteny** [comment]
probably a custom modification or patch? 
or any migrated character data / pet data?
or a specific pet?

**Comment by miraco** [comment]
Tested this Today and yeah i got the crash too
on newest Revision 

Windows 10

**Comment by LordUsagi** [comment]
First one to post a crash log gets a cookie :cookie:

**Comment by magick123** [comment]
https://pastebin.com/AntQgd2e

**Comment by magick123** [comment]
cookie?

**Comment by magick123** [comment]
defiantly databse related i downloaded a differant older database and it creates hunters fine but with the one in releases causes crash

**Comment by magick123** [comment]
https://github.com/OregonCore/OregonCore/tree/zamalaev this revision doesn't crash on hunter creation but master does

**Comment by AbraKabastard** [comment]
This is no longer an issue, right?

**Comment by Phentora** [comment]
I have reproduced this crash on Rev 3866 Hash: 5a880201 on Debug mode. I also have .dmp file is that helps.

https://paste.ee/p/Ko2RP
