### ISSUE TITLE
Config ThreatRadius is not working

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1565]
**Revision**:
last
**Operating system**:
serv2008r2
**Current behavior**: 
Config ThreatRadius is not working
There is m_configs[CONFIG_THREAT_RADIUS] = sConfig.GetIntDefault("ThreatRadius", 60);
in World.cpp but no use for this config in creature.cpp!
NO sWorld.getConfig(CONFIG_THREAT_RADIUS) !
mobs pursue the player for a very long time

in bool Creature::CanCreatureAttack
float dist = 
is wrong!

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
I think this is correct:

`
float dist = std::max<float>(GetAttackDistance(victim), sWorld.getConfig(CONFIG_THREAT_RADIUS)) + m_CombatDistance;
`

**Comment by Desteny** [comment]
the original code `float dist = std::min<float>(GetMap()->GetVisibilityRange(), SIZE_OF_GRID_CELL * 2)` seems a bit strange for me as well, 
the code from @PadreWoW is like on trinity: https://github.com/TrinityCore/TrinityCore/blob/036f67c0c144954827733cad0c5881eba1bd88e7/src/server/game/Entities/Creature/Creature.cpp#L2268

i think this could be correct, but it can cause sideeffects... would be nice to been tested carefully

**Comment by PadreWoW** [comment]
tested?

**Comment by Desteny** [comment]
i don't have any server running, for this i cant realy test, someone else?!

**Comment by DanielBallaSZTE** [comment]
Yes, tested and that code works. Gonna make a PR

**Comment by PadreWoW** [comment]
small bug :(
if mob's speed = player's speed - mob will NEVER leave you :(

**Comment by PadreWoW** [comment]
The problem is only when you damage the mob

Bug is here:

`
if (Unit* u = GetCharmerOrOwner())
    {
        if (u->GetTypeId() == TYPEID_PLAYER)
        {
            if (GetMap()->IsDungeon())
                return true;

            // don't check distance to home position if recently damaged, this should include taunt auras
            if (!isWorldBoss() && (GetLastDamagedTime() > getMSTime() || HasAuraType(SPELL_AURA_MOD_TAUNT)))
                return true;
        }
}
`

**Comment by PadreWoW** [comment]
I think this is more correct:

`
// don't check distance to home position if recently damaged, this should include taunt auras
	if (!isWorldBoss())
		if ((time(NULL) - GetLastDamagedTime() <= MAX_AGGRO_RESET_TIME) || HasAuraType(SPELL_AURA_MOD_TAUNT))
			return true;

`

**Comment by ljwlaji** [comment]
oregon still alive ?
