### ISSUE TITLE
about "Spirit Healer" unusable, Bug!

### ISSUE THREAD

**Issue by ghost** [OregonCore/OregonCore#1568]
**Revision**:
3803+
**Operating system**:
win10 x64 and win2008server x64 
mysql5.5.56 openssl1.0.2Lx64 vs2015up3x64 cmake3.6.1x64

**Steps to reproduce the problem**:
"Spirit Healer" unusable, After the player dies, Right click on "Spirit Healer", No menu, No revive!
 Where's the problem? I'm using the latest source code!

**Comment by PadreWoW** [comment]
Not confirmed

![default](https://user-images.githubusercontent.com/6802530/27376743-c289cc4a-567b-11e7-995b-94459bf67ca4.png)

**Comment by DanielBallaSZTE** [comment]
Your rev is 3803+
Which means you have modified something in your sourcecode. Could you reproduce it on a clean core?

**Comment by ghost** [comment]
No changes have been made!

**Comment by LordUsagi** [comment]
Isn't this usually a problem with localization?

**Comment by PadreWoW** [comment]
LordUsagi YOU ARE HERE!
PLEASE FIX THE PROBLEM WITH MAPS :)
