### ISSUE TITLE
transfer item_instance hellgorundcore to oregon

### ISSUE THREAD

**Issue by pakhmolkosh** [OregonCore/OregonCore#1569]
how i can transfer item_instance  from hellgorund core to oregoncore

from :
http://wiki.looking4group.eu/index.php/Item_instance
to :
https://docs.oregon-core.net/schema_characters_table_item_instance.html

... 
[item_instance.zip](https://github.com/OregonCore/OregonCore/files/1165279/item_instance.zip)

**Comment by Desteny** [comment]
this script / commit should help you
https://github.com/OregonCore/OregonCore/commit/82a4249b7e3850236a24eb7d6130313482ec5268 

there you can see the code changed from old trinity / mangos blob moved to separated fields.
i think there was also a mysql script file for update the existing table.

`but i dont know if HG has changed something to the default TC structure`!!
but as far as i know at the old ages it was plug n play to move char data
