### ISSUE TITLE
Error when using totems

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1571]
**Revision**:
last
**Operating system**:
2008R2
**Current behavior**: 
When using totems (stoneclaw totem for example) you can see error:

2017-08-16 16:14:14 Attempt get value from invalid value field: 236 (count: 234) for object typeid: 3 type mask: 9 Entry: 15478

\src\game\Object.h:301 in Object::HasFlag ASSERTION FAILED2
:
  index < m_valuesCount :: PrintIndexError<index, false>

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AbraKabastard** [comment]
Fixed in f5d67b1d5b910a8eb16f2589312b5ebcc2fda964
