### ISSUE TITLE
Bug with Areatriggers for Tempest Keep Dungeons

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1572]
**Revision**:
last
**Operating system**:
2008R2
**Current behavior**: 
In EVERY TK dungeon (The Eye, Botanica, Arcatraz, Mechanar) when players are in dungeon and you restart the server - you can see the error after core starts:
2017-08-21 14:51:33 Player XXXX (guid: YY) Map: 552, X: 1.400170, Y: 0.044801, Z: -0.204293, O: 0.011571. **Areatrigger not found.**

And all players will teleport to start location instead of dungeon entrance

All areatriggers are present in the database and DBC

**Expected behavior**: 
...

**Steps to reproduce the problem**:
Go to TK dungeon (any)
stop the core
start the core
try to enter the game
see the error and teleport to start location

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zgn1988** [comment]
Mmm, i start testet

**Comment by PadreWoW** [comment]
YOU ARE HERE!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by PadreWoW** [comment]
Answer me in Skype or in VK

**Comment by PadreWoW** [comment]
or in WoWJP

**Comment by zgn1988** [comment]
Напиши в Discord проблемы с ноутом были

**Comment by AbraKabastard** [comment]
Confirmed
