### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Findail1** [OregonCore/OregonCore#1576]
Building error like "d:\server\creating\oregoncore_source\src\game\Corpse.h(52): error C3665: 'Corpse::~Corpse' : override specifier 'override' not allowed on a destructor" Have any ideas? Using Visual Studio 2010 and latest OregonCore

**Comment by DSlayerMan** [comment]
@Findail1 According to the official [documentation](https://docs.oregon-core.net/intro.html) VS2012 or higher is required.

**Comment by Findail1** [comment]
Try on 2012 and 2015 . Same thing

**Comment by talamortis** [comment]
Change Line 52 to code below
`~Corpse() override;`

**Comment by talamortis** [comment]
Change Line 52 to code below
`~Corpse() override;`

**Comment by AbraKabastard** [comment]
I can't reproduce this error.
