### ISSUE TITLE
Possible incorrect entry in creature_template

### ISSUE THREAD

**Issue by Phentora** [OregonCore/OregonCore#1579]
**Revision**:
Rev. 3806
**Operating system**:
Windows 10 Pro x64
**Current behavior**: 
Entry 17473 ( Shadowmoon Summon Visual ) should not be in the database according to WoWHead and other sources. It was added in patch 5.4.2.17658.

This also throws a error in the core console:
![image](https://user-images.githubusercontent.com/14198137/32835986-e36f9e5e-ca10-11e7-9b85-d09b75cc2db0.png)

**Expected behavior**: 
Creature should not be in database.

**Steps to reproduce the problem**:
1. Launch OregonCore.
2. Go to Toggle Output.
3. Notice the line related to the creature entry.

**Comment by AbraKabastard** [comment]
Is this solved with your latest changes?

**Comment by Phentora** [comment]
Strangely this is solved by other commits. I don't know which but the error doesn't show up anymore.
