### ISSUE TITLE
OregonCore is trinity or mangos based?

### ISSUE THREAD

**Issue by SilvioDoMine** [OregonCore/OregonCore#1588]
I have a friend of mine that is interessed in TBC Development, but he only devs in Trinity. So, I wanted to know if this Core was more Trinity of Mangos based.

**Comment by miraco** [comment]
Trinity

**Comment by AbraKabastard** [comment]
We're definitely Trinity based but we've been so far behind for years that there is quite a few noticeable differences. We'd love to get systems ported down from 3.3.5a core to ours but this takes time.
