### ISSUE TITLE
Huge update time diff after last commits

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1589]
**Revision**:
last
**Operating system**:
2008 R2
**Current behavior**: 
....
Huge update time diff after last commits
HUGE LAGS in game 2000+ ms to cast spells
![untitled](https://user-images.githubusercontent.com/6802530/35317791-7bfee076-00e9-11e8-9edd-0ee3c3e2f872.jpg)

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Problem in this commit:
https://github.com/OregonCore/OregonCore/commit/f4a70ee34049000a2846ae103fbe65c9d2e0d53e

**Comment by AbraKabastard** [comment]
I should've mentioned that the commit needs you to re-extract mmaps. I was hoping to add some other changes before that was necessary, to prevent extract and then extract again but unfortunately got stuck. I think it's safe to extract now :)

**Comment by PadreWoW** [comment]
checked with re-extracted mmaps and new ace.dll and libmysql.dll
HUGE lags

Without this commit and with old mmaps - no problems

**Comment by Desteny** [comment]
if you can reproduce it with one player like on your screenshot try to use `CONFIG_MIN_LOG_UPDATE` to get more detailed info on your world update diff from `RecordTimeDiff` Method.
it shows in console.

in this case you are able to see if it results from map update it self, or from AI update and related changes like https://github.com/OregonCore/OregonCore/commit/aea8536b4072d1c549b964f699d1043430a7f0b4 or from player update

Edit: Config Setting named `MinRecordUpdateTimeDiff`

Edit2: and may change this line https://github.com/OregonCore/OregonCore/blob/master/src/game/World.cpp#L1710 from `sLog.outDetail` to your activated log level, else you cant see anything

**Comment by AbraKabastard** [comment]
Interesting tool that I had no idea about

**Comment by AbraKabastard** [comment]
After re-extraction of mmaps I am receiving no huge diffs on a locally tested machine with a locally connected player.

**Comment by PadreWoW** [comment]
any mobs aroud you? or you tested on GM Island?

**Comment by AbraKabastard** [comment]
I went to Tempest Keep and walked around inside. I flew around Outlands, went into Shattrath. Teleported to Stormwind.

**Comment by PadreWoW** [comment]
Tested again with NEW MMAPS, NEW DLLS
Compiled from 0
Changed in config:

GridUnload = 1 (was 0)
MapUpdate.Threads = 2 (was 1)

Lags.....
Become a little faster but whatever lags
Update time diff 110-673 (lags in game 100-450ms when casting)

Processor and RAM load = 20-25% (Intel Core i5 - 4 cores, 16 GB RAM)

With old maps - no lags

**Comment by PadreWoW** [comment]
Very strange - no lags in "Tempest Keep The Eye"
But HUGE lags in Trade District Stormwind

**Comment by PadreWoW** [comment]
Medium lags in Elwynn Forest and Duskwood (smaller than in Stormwind)
I think it's beacause geodata in Stormwind is more difficult

**Comment by Phentora** [comment]
Quick observation here. Maybe its not very helpful but i have "compared" the time it takes to extract the mmaps from TrinityCore and from OregonCore and it took way more time for me to extract the mmaps on OregonCore.

I think it took about 8 hours more with the OregonCore tools.

I'm hanging on IRC if anyone want to talk.

**Comment by AbraKabastard** [comment]
Did you use the Python tool? It takes under 30 minutes for me

**Comment by PadreWoW** [comment]
Python tool? for what?

**Comment by PadreWoW** [comment]
I use cmake and visual studio 2013 for compile sources

**Comment by Phentora** [comment]
I did not use the tool. The standard mmaps exe uses one 25% of my CPU so that might be why the TC is much faster.

**Comment by Phentora** [comment]
I will do some tests in a few hours to see if the same issue occurs to me. Will post results here.

**Comment by AbraKabastard** [comment]
Sounds great. There's a python tool for extracting mmaps that uses 100% of your CPU running multiple threads.

**Comment by Desteny** [comment]
TC mmap extractor was updated quite some year(s) ago to work multitreaded internaly (if i remember right)
OC has the old one (singel threaded)

normaly if you use a batch file to start 4 instances of the extractor, one for map 0, one for 1, one for 530 and the last for all except those 3 you have a fast extract because one of the big maps alone needs more time then all the other maps together.

i think the pyton tool uses this logic as well, right?

**Comment by AbraKabastard** [comment]
yes you are correct. the python tool runs multiple windows extracting 4 maps at a time it looks. very cool stuff!

**Comment by Phentora** [comment]
I have been trying to reproduce this issue for about 30 minutes but it doesn't occur to me. Update diff is stable at 15-16.

I have tried creating 3 different characters in 3 different zones and moving a little bit, killing mobs and doing quests. I have tried moving from Stormwind then to Elwyn Forrest (by running ) and then to Duskwood and the diff is still at 15.

Using OregonCore Rev: 3869 Hash: ffc80075 (Win64,little-endian) on Debug mode. Maps, Vmaps and MMaps compiled yesterday.

**Comment by Desteny** [comment]
Are you running this tests on windows?
in the past there where some notable differences between some operating systems.

i think @PadreWoW uses some linux / unix

**Comment by Phentora** [comment]
Yes. I am using Windows 10 64-bit

**Comment by PadreWoW** [comment]
Windows Server 2016

**Comment by Phentora** [comment]
I could test this on a virtual machine running Win Server 2016. But i have no idea when i have time this week.

**Comment by Desteny** [comment]
as far as i know win server 2016 and win10 are the same. there should be no notable difference in this case.

maybe there are diffences in the size of the generated maps / vmaps / mmaps.

it would be nice if both can post there folder size and file count... maybe there is a difference.

if not i still suggest to activate the logging feature (in code) like i described uppon and look what part of the update loop causes the high diff values. this can help a lot

**Comment by Phentora** [comment]
Sound like a plan !

Maps: 167 MB (3586 files)
Vmaps: 356 MB (6812 files)
MMaps: 1.45 GB (2775 files)

**Comment by PadreWoW** [comment]
Compiled under MS Windows Server 2016
Visual Studio Express 2013

All folders:
DBC + MAPS + VMAPS + MMAPS
1.86GB (on disk 1.88GB)

DBC
47.7MB (on disk 48.0MB) - 186 items
MAPS
168MB (on disk 175MB) - 3604 items
VMAPS
250MB (on disk 261MB) - 6835 items
MMAPS
1.40GB (on disk 1.41GB) - 2560 items

**Comment by kotishe** [comment]
Nice work guys, need move my patches on this fork

**Comment by Phentora** [comment]
I have the same DBC directory size and file count as PadreWoW.

**Comment by PadreWoW** [comment]
maybe lags because of AC3 anticheat that I added to my core?
but strange that I have no lags on old mmaps

**Comment by Phentora** [comment]
So this is a custom modification to your core ? Can you try to test this issue without the AC3 anticheat modification ?

**Comment by PadreWoW** [comment]
maybe later
after we fix bug:
https://github.com/OregonCore/OregonCore/issues/1598

**Comment by Desteny** [comment]
strange are the difference between @Phentora and @PadreWoW  map / vmap / mmap file count. 
sometimes they are lower, sometimes higher, but the strange thing is the vmap size, one is 356MB one is 250MB seems to be a lot different / missing informations here....

**Comment by AbraKabastard** [comment]
Just for reference, here's my information:
Maps: 167 mb - 3,586 files
VMaps: 356 mb - 6,812 files
MMaps: 1.45 gb - 2,775 files

Edit: which after looking are the same numbers as @Phentora

**Comment by Desteny** [comment]
DBC files can vary based on client language, but map / vmap / mmap files should be the same if extracted from a clean client.

but if the client was modified or had problems while patching the result could be different.

only a suggestion, try to share your files with @PadreWoW if his server works nice with your files then we must review the extractor code. may add some more output to a log file to find out whats the difference

**Comment by Phentora** [comment]
If you guys want to join me and @AbraKabastard , we are on Discord at https://discord.gg/sH3E4u .

**Comment by SLITH3RIN** [comment]
I am looking forward to implement new mmap system on our server, but we have added AC3 anticheat too. I will report if we will have the same issue on test server and main server.

**Comment by PadreWoW** [comment]
I recompiled core with tools (without any 3-rd party patches)
and extracted new dbc maps vmaps mmaps
The number of files is the same, but vmaps directory has 359MB (371MB on Disk)......bigger size
Other folders have the same size
What a hell?

**Comment by PadreWoW** [comment]
I added new maps to my core
And i can see this

![10](https://user-images.githubusercontent.com/6802530/35680853-8dee80fa-076c-11e8-9de4-25685f83d57d.png)

**Comment by Phentora** [comment]
Did you re-extract dbc,maps,vmaps and mmaps after you recompiled ? You need to use the new tools for this. Old maps aren't good anymore and that's why you're getting those errors.

**Comment by PadreWoW** [comment]
I recompiled core + tools
Reextracted all maps vmaps mmaps dbc
And i can see picture above
I added NEW maps to my OLD core

**Comment by Phentora** [comment]
Ok. Then use the new core and new maps. Console error clearly says "...was built with generator v4, expected v3".

The old core doesn't know how to interpret the new mmaps.

**Comment by PadreWoW** [comment]
I can not use new core because of 400+ fixes, addons, patches :)

**Comment by Phentora** [comment]
I don't understand. Isn't our scope at the moment to find out if the original core itself is causing issues on your environment ?

You will need to make fresh databases and recompile the stock core from OC and give that a try. This won't break the modification you did. We just need to see if the issue is present in the stock core or only on the one with your mods.

**Comment by PadreWoW** [comment]
I understand
And I try to find out WHAT EXACTLY conflicts with my core :)
What part of code can do these lags

**Comment by Phentora** [comment]
Exactly mate ! 👍
