### ISSUE TITLE
Players save data BUG

### ISSUE THREAD

**Issue by keyshuwen** [OregonCore/OregonCore#1595]
**Revision**: new Core  3866

**Operating system**: Win 10 x64

**Current behavior**: Player DB data cannot be saved

**Expected behavior**: 
...

**Steps to reproduce the problem**:
Add an item to the knapsack
To attack the creature, in battle AIT+ F4 closes the game window
When you get in, you'll find that the player is back to the starting point, and the added stuff is gone. 
:(
Forgive me for not good English.

**Comment by AbraKabastard** [comment]
I cannot reproduce even after following your steps. I'd like some more feedback from others regarding this issue.

**Comment by keyshuwen** [comment]
In combat status, AIT+F4

**Comment by AbraKabastard** [comment]
I did. I come back as a ghost. Item still in my inventory. How do you add item to the player? Loot or GM command?

**Comment by keyshuwen** [comment]
No items need to be added.
As long as you enter the combat state, then AIT + F4 will appear BUG.
:(

**Comment by keyshuwen** [comment]
I'm sorry, I haven't updated characters. I suggest merging characters. :)  Close.

**Comment by keyshuwen** [comment]
I'm sorry, I haven't updated characters. I suggest merging characters. :) Close.
