### ISSUE TITLE
Creatures wont chase after being stunned

### ISSUE THREAD

**Issue by keyshuwen** [OregonCore/OregonCore#1598]
Revision:
OregonCore Rev: 3871
Operating system:
Windows 10 Pro x64
Current behavior:
Creature cannot restore movement after creature is restricted.

Expected behavior:

Steps to reproduce the problem:
Charge Stun creature, the creature will stay in place. And will not attack.
Example:
Spell 100

:(

**Comment by PadreWoW** [comment]
confirm

**Comment by AbraKabastard** [comment]
Is this new or has it been there for a while?

**Comment by keyshuwen** [comment]
I don't know, maybe for a while.

**Comment by PadreWoW** [comment]
I know where is the problem
Here:
`
void Unit::SetRooted(bool apply)
{
    if (apply)
    {
        // MOVEMENTFLAG_ROOT cannot be used in conjunction with MOVEMENTFLAG_MASK_MOVING (tested 3.3.5a)
        // this will freeze clients. That's why we remove MOVEMENTFLAG_MASK_MOVING before
        // setting MOVEMENTFLAG_ROOT
        RemoveUnitMovementFlag(MOVEMENTFLAG_MOVING);
        m_movementInfo.AddMovementFlag(MOVEMENTFLAG_ROOT);
        StopMoving();

        if (GetTypeId() == TYPEID_PLAYER)
        {
            WorldPacket data(SMSG_FORCE_MOVE_ROOT, 10);
            data << GetPackGUID();
            data << (uint32)2; // @todo Identify this
            SendMessageToSet(&data, true);
        }
        else
        {
            WorldPacket data(SMSG_SPLINE_MOVE_ROOT, 8);
            data << GetPackGUID();
            SendMessageToSet(&data, true);
        }
    }
    else
    {
        if (!HasUnitState(UNIT_STATE_STUNNED))      // prevent moving if it also has stun effect
        {
            if (GetTypeId() == TYPEID_PLAYER)
            {
                WorldPacket data(SMSG_FORCE_MOVE_UNROOT, 10);
                data << GetPackGUID();
                data << (uint32)2; // @todo Identify this
                SendMessageToSet(&data, true);
            }
            else
            {
                WorldPacket data(SMSG_SPLINE_MOVE_UNROOT, 8);
                data << GetPackGUID();
                SendMessageToSet(&data, true);
            }

            m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ROOT);
        }
    }
}
`

**Comment by PadreWoW** [comment]
}
        sLog.outError("remove rooted"); // added for testing
        m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ROOT);
    }

I can see my test error in logs, but i think m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ROOT); is wrong, npc can not move because of this wrong string

**Comment by PadreWoW** [comment]
Problem may be since this commit:
https://github.com/OregonCore/OregonCore/commit/b22678c389576912786e2f24a9a093001de4032e

**Comment by PadreWoW** [comment]
I commented out ALL code with "rooted" in Unit.cpp..........NO EFFECT!!!!!
Mobs can not move after for example Frost Nova.......
what a hell?.......

**Comment by PadreWoW** [comment]
FIXEEEDDDD!!!!!!!!!! I FOUND IT!!!!!
But you SHOULD test it before commit!!!

**Comment by PadreWoW** [comment]
Here is fix:

`
void Unit::SetRooted(bool apply)
{
    if (apply)
    {
        // MOVEMENTFLAG_ROOT cannot be used in conjunction with MOVEMENTFLAG_MASK_MOVING (tested 3.3.5a)
        // this will freeze clients. That's why we remove MOVEMENTFLAG_MASK_MOVING before
        // setting MOVEMENTFLAG_ROOT
        RemoveUnitMovementFlag(MOVEMENTFLAG_MOVING);
        m_movementInfo.AddMovementFlag(MOVEMENTFLAG_ROOT);
        StopMoving();

        if (GetTypeId() == TYPEID_PLAYER)
        {
            WorldPacket data(SMSG_FORCE_MOVE_ROOT, 10);
            data << GetPackGUID();
            data << (uint32)2; // @todo Identify this
            SendMessageToSet(&data, true);
        }
        else
        {
            WorldPacket data(SMSG_SPLINE_MOVE_ROOT, 8);
            data << GetPackGUID();
            SendMessageToSet(&data, true);
        }
    }
    else
    {
		ClearUnitState(UNIT_STATE_ROOT); <---------- THIS IS FIX

        if (!HasUnitState(UNIT_STATE_STUNNED))      // prevent moving if it also has stun effect
        {
            if (GetTypeId() == TYPEID_PLAYER)
            {
                WorldPacket data(SMSG_FORCE_MOVE_UNROOT, 10);
                data << GetPackGUID();
                data << (uint32)2; // @todo Identify this
                SendMessageToSet(&data, true);
            }
            else
            {
                WorldPacket data(SMSG_SPLINE_MOVE_UNROOT, 8);
                data << GetPackGUID();
                SendMessageToSet(&data, true);
            }

            m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ROOT);
        }
    }
}
`
