### ISSUE TITLE
crash creature level

### ISSUE THREAD

**Issue by keyshuwen** [OregonCore/OregonCore#1601]
**Revision**:  3889

**Operating system**: Win 10 x64

**Current behavior**: 
 crash

**Expected behavior**: 
...

**Steps to reproduce the problem**:
The latest database discovery.
DB:  creature_template entry 5237 minLevel 41 Maxlevel 12  crash.
Is it related to the latest revision?

Code location: 

    CreatureBaseStats const* cCLS = sObjectMgr.GetCreatureClassLvlStats(level, cInfo->unit_class, cInfo->exp);
    
    // health
    health = cCLS->BaseHealth * cInfo->ModHealth;   --------------------------->//crash

    health *= _GetHealthMod(rank); // Apply custom config settting
    if (health < 1)
        health = 1;

    SetCreateHealth(health);
    SetMaxHealth(health);
    SetHealth(health);
    SetPlayerDamaged(false);

    // mana
    mana = cCLS->BaseMana * cInfo->ModMana;

**Comment by PadreWoW** [comment]
what did you do when server crashed?
need more information
most crashes related to spells and pets, not my commit - i have no crash with it

**Comment by PadreWoW** [comment]
I have periodical crashes related to hunters (i think with pets)
today for example was crash and in game was only one player - HUNTER

**Comment by keyshuwen** [comment]
No, I had no idea. After the update, the game broke into the game crash.
Is my database wrong?
There are several wrong updates.
Hope to have a new database.

:(

**Comment by kotishe** [comment]
I have this crash too on pet, summon pet and use hunter mind control (Beast eye) = crash

**Comment by AbraKabastard** [comment]
Please compile in debug mode and attach a crash dump.

**Comment by kotishe** [comment]
here https://mlx.su/paste/view/1eac3bb2

**Comment by AbraKabastard** [comment]
That was in debug mode? Strange!

**Comment by kotishe** [comment]
Yes, no info about crash point=( Cjmpile today and test in debug

**Comment by AbraKabastard** [comment]
Damn! What do you do to cause crash or just random?

**Comment by PadreWoW** [comment]
Crashes can not be random! It's COMPUTER PROGRAM!

**Comment by kotishe** [comment]
Its OregonCore dude! =) Joke. summon pet and use hunter mind control (Beast eye) = crash

**Comment by kotishe** [comment]
AbraKabastard info about function i mean/

**Comment by AbraKabastard** [comment]
No crash for me 👍 I can summon pet and use eyes of the beast and no crash

**Comment by kotishe** [comment]
Okay is my fault. Try other catch on clean core.

**Comment by keyshuwen** [comment]
It has to do with the database. Close  :)

**Comment by keyshuwen** [comment]
@AbraKabastard 
It should be this mistake.

creature_template entry 5237 minLevel 41 Maxlevel 12 crash.

Code location:

CreatureBaseStats const* cCLS = sObjectMgr.GetCreatureClassLvlStats(level, cInfo->unit_class, cInfo->exp);

// health
health = cCLS->BaseHealth * cInfo->ModHealth;   --------------------------->//crash

health *= _GetHealthMod(rank); // Apply custom config settting
if (health < 1)
    health = 1;

SetCreateHealth(health);
SetMaxHealth(health);
SetHealth(health);
SetPlayerDamaged(false);

// mana
mana = cCLS->BaseMana * cInfo->ModMana;


I don't know if you can get mail or not. Only call you.  I'm sorry.
modify entry 5237 Maxlevel = 42.
It looks all right.  :)

**Comment by PadreWoW** [comment]
I have no such bug
I have min=42 max=43 lvl

**Comment by keyshuwen** [comment]
BaseDatabase 20/Jan/2017 + update 

There is this BUG.   :(
