### ISSUE TITLE
Bug with enchant

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1602]
**Revision**:

**Operating system**:
Win Serv 2016
**Current behavior**: 
When (for example rogue or warrior) use "+mana" enchant he will get +energy/rage !!!

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
![13](https://user-images.githubusercontent.com/6802530/35733264-c8e1d3bc-082d-11e8-9a50-1568df099570.png)

**Comment by AbraKabastard** [comment]
Problem is in spell effects but I want to try to change stat system to be more readable in case of fixing bugs like this and the -1 stat bug. Fix will be tested and pushed today.

**Comment by AbraKabastard** [comment]
Fixed in 69a6536a9eac9ded6b59fe3f3bdeee6b750f30de
