### ISSUE TITLE
PALADIN TALENT VENGEANCE AURA DAMAGE BUG

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1609]
**Revision**: 3929

**Operating system**: Windows 7 Ultimate

**Current behavior**: 

Aura/Talent Vengeance  only can add much damage
http://db.hellfire-tbc.com/?spell=20057

Image: https://ibb.co/kyC1g6

**Expected behavior**: 

**Steps to reproduce the problem**:

Paladin, take a weapon and armor & test.

**Comment by d3athbl0w** [comment]
I tried reversed this commit and it has been fixed the damage.

the stack is normal only 3 :D

https://github.com/OregonCore/OregonCore/commit/69a6536a9eac9ded6b59fe3f3bdeee6b750f30de

**Comment by AbraKabastard** [comment]
Reversing commit is NOT a fix

**Comment by AbraKabastard** [comment]
Please test after this commit 👍 Let me know

**Comment by d3athbl0w** [comment]
Take a look at this

https://ibb.co/gydYwH vengeance damage set to 9652 & more, the damage is a bug
https://ibb.co/iiiDVc  when vengeance finish damage set to 3861 & more, the damage is a bug

as I said the error comes from this commit: https://github.com/OregonCore/OregonCore/commit/69a6536a9eac9ded6b59fe3f3bdeee6b750f30de

**Comment by AbraKabastard** [comment]
Closed in 6493cb82add56821a6f3782f3d8d070b9237c8c3

**Comment by flumby** [comment]
This broke more things fails to even compile correctly. This is one of many errors.


pet.cpp: Severity    Code    Description    Project    File    Line    Suppression State
Error    C3861    'SetModifierValue': identifier not found    game    C:\OregonCore\src\game\Pet.cpp    996
