### ISSUE TITLE
Attack power items or spells  they can not raise the damage does not go up

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1610]
**Revision**: 3929

**Operating system**: Windows 7 Ultimate

**Current behavior**: 

The attack power items or spells does not go up the damage when equip items, the damage only goes up when a weapon is equipped

Image: https://ibb.co/iX6ddm

**Expected behavior**: 

**Steps to reproduce the problem**:

Paladin, take a weapon and armor & test.

**Comment by d3athbl0w** [comment]
I reverted this commit and it was fixed ^-^

https://github.com/OregonCore/OregonCore/commit/69a6536a9eac9ded6b59fe3f3bdeee6b750f30de

the problem is in the commit

**Comment by AbraKabastard** [comment]
Can you explain some more information? Some ItemID will maybe help me. I can't notice bug!

**Comment by d3athbl0w** [comment]
Put on any dps armor, the damage does not go up

**Comment by keyshuwen** [comment]
The intensity of the attack does not improve the damage correctly.

**Comment by AbraKabastard** [comment]
Attack Power doesn't make Damage rise?

I go to work now but I will fix this tonight 👍If you need to revert commit temporarily, do so.

**Comment by d3athbl0w** [comment]
Take a look at this: 
https://ibb.co/fhb6ix
https://ibb.co/gwxhqc

as I said the error comes from this commit: https://github.com/OregonCore/OregonCore/commit/69a6536a9eac9ded6b59fe3f3bdeee6b750f30de

**Comment by AbraKabastard** [comment]
Closed in 6493cb82add56821a6f3782f3d8d070b9237c8c3
