### ISSUE TITLE
[Spell/Visual] Black Qiraji Resonating Crystal visual dissapears on reapply

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1616]
1) Ride this item: http://www.wowhead.com/item=21176/black-qiraji-resonating-crystal

2) Use the item again with the mount.

3) Check this out:
![wowscrnshot_021218_220025](https://user-images.githubusercontent.com/14060040/36131101-9b13adc2-1046-11e8-8adb-16d6d482466e.jpg)
![wowscrnshot_021218_220047](https://user-images.githubusercontent.com/14060040/36131102-9bdd7526-1046-11e8-84ce-90a4dac0f93a.jpg)

**Comment by AbraKabastard** [comment]
Item doesn't share cooldowns with mounts either.
