### ISSUE TITLE
Pets Vanish

### ISSUE THREAD

**Issue by flumby** [OregonCore/OregonCore#1617]
**Revision**:
3916+ revision, tested with a non gm character.

**Operating system**:
Debian
**Current behavior**: 
When you have tamed a beast and do any of the following:

Dismiss Pet, Log out, Die

You lose your pet and have to retame as it states you do not have a pet.

**Expected behavior**: 
...
Pet should save, logging out should not make you lose your pet, also if you die you should not lose your pet.
**Steps to reproduce the problem**:
Die with a pet.
Logout with a pet
Dismiss a pet 
You won't be able to get it back without taming a new one.
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AbraKabastard** [comment]
Latest is not a revision number. Please test without a GM character.

**Comment by flumby** [comment]
3916+ revision, tested with a non gm character.
