### ISSUE TITLE
Database/Pets: Pets not saving to database

### ISSUE THREAD

**Issue by flumby** [OregonCore/OregonCore#1618]
**Revision**:
3916+ revision, tested with a non gm character.

**Operating system**:
Debian
**Current behavior**: 
When you have tamed a beast and do any of the following:

Dismiss Pet, Log out, Die

You lose your pet and have to retame as it states you do not have a pet.

**Expected behavior**: 
...
Pet should save, logging out should not make you lose your pet, also if you die you should not lose your pet.
**Steps to reproduce the problem**:
Die with a pet.
Logout with a pet
Dismiss a pet 
You won't be able to get it back without taming a new one.
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by flumby** [comment]
IT allows you to press Call pet but nothing happens.  

If you relog, and try call pet it states you don't have a pet.

**Comment by flumby** [comment]
`            // save pet
            std::ostringstream ss;
            ss  << "INSERT INTO character_pet (id, entry,  owner, modelid, level, exp, Reactstate, loyaltypoints, loyalty, trainpoint, slot, name, renamed, curhealth, curmana, curhappiness, abdata,TeachSpelldata,savetime,resettalents_cost,resettalents_time,CreatedBySpell,PetType) "
                << "VALUES ("
                << m_charmInfo->GetPetNumber() << ", "
                << GetEntry() << ", "
                << owner << ", "
                << GetNativeDisplayId() << ", "
                << getLevel() << ", "
                << GetUInt32Value(UNIT_FIELD_PETEXPERIENCE) << ", "
                << uint32(GetReactState()) << ", "
                << m_loyaltyPoints << ", "
                << GetLoyaltyLevel() << ", "
                << m_TrainingPoints << ", "
                << uint32(mode) << ", '"
                << name.c_str() << "', "
                << uint32((GetByteValue(UNIT_FIELD_BYTES_2, 2) == UNIT_RENAME_ALLOWED) ? 0 : 1) << ", "
                << curhealth << ", "
                << curmana << ", "
                << GetPower(POWER_HAPPINESS) << ", '";

            for (uint32 i = 0; i < 10; i++)
                ss << uint32(m_charmInfo->GetActionBarEntry(i)->Type) << " " << uint32(m_charmInfo->GetActionBarEntry(i)->SpellOrAction) << " ";
            ss << "', '";

`

**Comment by flumby** [comment]
In the Insert SQL statement in pet.cpp, does it matter that the columns arn't specified in the correct order? but also that some have spaces inbetween columnname1, columnname2, and some together columnname3,columnname4 ?

**Comment by flumby** [comment]
<< Currently how it is >>
` "INSERT INTO character_pet (id, entry,  owner, modelid, level, exp, Reactstate, loyaltypoints, loyalty, trainpoint, slot, name, renamed, curhealth, curmana, curhappiness, abdata,TeachSpelldata,savetime,resettalents_cost,resettalents_time,CreatedBySpell,PetType) "`
<< What it should be ?? >>
`"INSERT INTO character_pet (id, entry, owner, modelid, CreatedBySpell, PetType, level, exp, Reactstate, loyaltypoints, loyalty, trainpoint, name, renamed, slot, curhealth, curmana, curhappiness, savetime, resettalents_cost, resettalents_time, abdata, teachspelldata)"`  or somthing similar?

**Comment by AbraKabastard** [comment]
If there was an error with this SQL statement you'd notice it in db_errors.log or it would appear in your console view!
**Edit:** looks like there is one
