### ISSUE TITLE
Bug with mob/npc adding in game when in GM mode

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1622]
**Revision**:
last
**Operating system**:
WinServ 2016
**Current behavior**: 
....
Bug with mob/npc adding in game when in GM mode
When you in GM mode and add new NPC/Mob into the world (.npc add command) and then turn GM mode off, you can not see npc/mob

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
I think this issue related to phase system

**Comment by AbraKabastard** [comment]
NPCs spawned using commands are spawned into whatever phase the spawner is in. In GM mode you're in phase_all. This is intended behavior!

**Comment by PadreWoW** [comment]
I think this is not right.....
For example I want to add some mobs to dungeon, and they will immediately start attacking me

**Comment by PadreWoW** [comment]
i can not add them in GM mode because they will be invisible now
