### ISSUE TITLE
HP blood bar shows errors.

### ISSUE THREAD

**Issue by keyshuwen** [OregonCore/OregonCore#1628]
**Revision**:   3967 
**Operating system**:   win10  x64

**Current behavior**: 

![qq 20180225103457](https://user-images.githubusercontent.com/4241825/36637479-92f46778-1a17-11e8-9b81-c5074c18c053.png)

I didn't set it, but it showed a percentage. This would lead to a Interface error.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AbraKabastard** [comment]
In TBC there were no number values, only percent

**Comment by keyshuwen** [comment]
no , TBC is optional

Pictures come to MANGOS_TBC

![33](https://user-images.githubusercontent.com/4241825/36638132-3bc498a0-1a27-11e8-93f9-5c6dd1bdd7f9.png)

UI option - status text - display percentage

Removal of display percentage,  shows number values.

**Comment by keyshuwen** [comment]
I think it should be BUG.
@AbraKabastard  
![0180225151035](https://user-images.githubusercontent.com/4241825/36639048-3b4dd10e-1a3e-11e8-8151-df54ca1728ce.png)

![qq 20180225151137](https://user-images.githubusercontent.com/4241825/36639080-a4550c94-1a3e-11e8-9905-5e49ce2a7466.png)

Attack it

![qq 20180225151400](https://user-images.githubusercontent.com/4241825/36639082-b006b33a-1a3e-11e8-8bb5-5334b7235920.png)

Showing confusion, I didn't use any Interface.
