### ISSUE TITLE
[Spells] Immolate currently treated as a curse

### ISSUE THREAD

**Issue by romgenie** [OregonCore/OregonCore#1629]
**Revision**:
'OregonCore Rev: 3967 Hash: 71a6c59 (Unix,little-endian)'

**Operating system**:
Linux - Ubuntu 16.04 

**Current behavior**: 
As a warlock, after casting Immolate, then casting any curse it will overwrite Immolate.

**Expected behavior**: 
After casting Immolate, then casting any curse it should not overwrite Immolate.

**Steps to reproduce the problem**:
Cast Immolate on any creature, then cast any curse on a creature and Immolate will be overwritten.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DanielBallaSZTE** [comment]
Are you sure it's treated as a curse? Try and remove it on an other character with remove curse.
The fact that it doesn't stack with curses doesn't necessarily mean it's treated as one.

**Comment by amaroc** [comment]
On 3602 rev. all ok. I did: Immolate+CoA; Imm+CoE; and reverse.
