### ISSUE TITLE
SESSION: received not allowed opcode CMSG_GROUP_SWAP_SUB_GROUP (0x0280)

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1635]
**Revision**:
last
**Operating system**:
serv 2016
**Current behavior**: 
....
SESSION: received not allowed opcode CMSG_GROUP_SWAP_SUB_GROUP (0x0280)

May be this can help to implement this Opcode?
https://github.com/cmangos/mangos-wotlk/commit/4dd3a22469bbdeae035fdfdcddc88db9f6e74ec2

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ReyDonovan** [comment]
https://github.com/ReyDonovan/OregonCoreR2/commit/66b1bd4736a05054e5242cdd88d7d9d7169eccbd
