### ISSUE TITLE
Warrior's "Sweeping Strikes" can attack any NPC even neutral

### ISSUE THREAD

**Issue by PadreWoW** [OregonCore/OregonCore#1636]
**Revision**:
last
**Operating system**:
serv 2016
**Current behavior**: 
....
Warrior's "Sweeping Strikes" can attack any NPC even neutral
Even NPC is not selectable and not attackable!

**Expected behavior**: 
...
"Sweeping strikes" must attack only your enemies not any nearby NPCs!

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by PadreWoW** [comment]
Blade Flurry has the same bug

**Comment by amaroc** [comment]
Aprove =) 3602 rev. Go to Cenarion expedition in Zangramash. Its works on neutral but didnt work on allies npc.
