### ISSUE TITLE
GM.InWhoList

### ISSUE THREAD

**Issue by kepo123** [OregonCore/OregonCore#1639]
**Revision**:
Latest
**Operating system**:
Windows Server R2 2012 

**Steps to reproduce the problem**:
"GM.InWhoList" and "GM.InGMList" doesn't work. I set them to "0 = false" but when there is a gm in-game, the normal players still can see him.

**Comment by PadreWoW** [comment]
not confirmed

**Comment by OMGhixD-OG** [comment]
[https://cdn.discordapp.com/attachments/321434005943746561/531311764047134740/Screenshot_10.png](https://cdn.discordapp.com/attachments/321434005943746561/531311764047134740/Screenshot_10.png)

Not confirmed.

**Should be closed.**
