### ISSUE TITLE
Multishot does to much dmg in OHF

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1647]
**Revision**:
Last
**Operating system**:
Windows Server 2016
**Current behavior**: 
Multishot does to much dmg in OHF
![unknown](https://user-images.githubusercontent.com/14060040/57591228-5e0df900-74fe-11e9-9b80-a64bbede6dfc.png)

**Expected behavior**: 

Not so much damage xD

**Steps to reproduce the problem**:

Go to OHF

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
can you please tell me the creature ID?

**Comment by AbraKabastard** [comment]
Durnholde Rifleman (from the SS) cant see if its heroic or not

**Comment by d3athbl0w** [comment]
> Durnholde Rifleman (from the SS) cant see if its heroic or not

Heroic

**Comment by talamortis** [comment]
could you also please check other creatures that have "multi shot" spell please try make sure the creatures are elite aswell thanks.

**Comment by talamortis** [comment]
https://github.com/talamortis/OregonCore/commit/87e290a144968618ff27895be105c3d92c3c6266
