### ISSUE TITLE
Pets don't break combat

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1648]
**Revision**:
Last
**Operating system**:
Windows Server 2016
**Current behavior**: 
pets don't break combat after attacking mob dies have to dismiss or mount for pet to break -combat
**Expected behavior**: 
pets should break combat

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by talamortis** [comment]
Thank you for reporting this

fixed https://github.com/talamortis/OregonCore/commit/69ef497428c8138fb889d365a8556d31f92b76d4

@AbraKabastard  are you able to port across thanks.

**Comment by AbraKabastard** [comment]
@d3athbl0w If you don't mind testing this on your server before I merge it in

**Comment by AbraKabastard** [comment]
Fixed in effe8d7f846446d02ccbbc52f41b6d7f50cd3630
