### ISSUE TITLE
Quest NPC in Shattrath "Haggard War Veteran"

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1649]
**Revision**:
Last
**Operating system**:
Windows Server 2016
**Current behavior**: 
the quest NPC in Shattrath "Haggard War Veteran"  is not in the spot where he should be to start the questline to choose your aldor or scryer faction

**Expected behavior**: 
....

**Steps to reproduce the problem**:
....
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AbraKabastard** [comment]
Where should he be? He's spawned.

Try 
```.go c 70177```

**Comment by d3athbl0w** [comment]
Sorry invalid report
