### ISSUE TITLE
you can not eat and drink at the same time

### ISSUE THREAD

**Issue by d3athbl0w** [OregonCore/OregonCore#1653]
**Revision**:
Last rev
**Operating system**:
Windows server 2016
**Current behavior**: 
you can not eat and drink at the same time, and eating takes away certain buffs as if, "eating" shared use with others.

**Expected behavior**: 
...

**Steps to reproduce the problem**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by yuanf225** [comment]
good job bro
