### ISSUE TITLE
access_requirement not working

### ISSUE THREAD

**Issue by turbosnek** [OregonCore/OregonCore#1666]
Hi, I have a problem with access_requirement. I don' have complete quest Hard to Kill to enter Magister terrace HC, but I can enter. My GM mode is off.

Struck my DB table

`INSERT INTO `access_requirement` (`id`, `level_min`, `level_max`, `item`, `item2`, `heroic_key`, `heroic_key2`, `quest_done`, `quest_failed_text`, `heroic_quest_done`, `heroic_quest_failed_text`, `comment`) VALUES ('51', '70', '0', '0', '0', '0', '0', '0', NULL, '11492', 'Heroic Difficulty requires completion of the \"Hard to Kill\" quest.', 'instance Magisters\' Terrace (585)')
`

Sorry for my English. I am Czech

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/80965862-3862b980-8e0b-11ea-8884-feceb0820e1e.png)
Sorry but i cant reproduce the issue anyone else can confirm?
