### ISSUE TITLE
Scratches (10556) (BB #930)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#930]
This issue was migrated from bitbucket.
**Original Reporter:** bewtihozzy
**Original Date:** 29.05.2015 20:31:33 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/930

<hr>

Use the Fistful of Feathers on the Lashh'an Spell Circle, then return to Daranelle at Sylvanaar before the kaliri spirit fades.
-Have Daranelle analyze the Kaliri aura
-Fistful of Feathers] (Provided)

Bug: Impossible to "Have Daranelle analyze the Kaliri aura"

**Comment by Selphius** [comment]
Fixed in https://github.com/OregonCore/OregonCore/commit/ad8eba4d58febc49cd64e210fa81a21890b3c33a
