### ISSUE TITLE
What Came First, the Drake or the Egg? (10609) (BB #934)

### ISSUE THREAD

**Issue by OregonAsari** [OregonCore/OregonCore#934]
This issue was migrated from bitbucket.
**Original Reporter:** bewtihozzy
**Original Date:** 29.05.2015 20:52:20 GMT+0000
**Original Priority:** major
**Original Type:** bug
**Original State:** new
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/934

<hr>

What Came First, the Drake or the Egg? (10609)
Collect 3 Proto-Nether Drake Essences, 3 Adolescent Drake Essences and 3 Mature Drake Essences. 

bug: I couldnt find any mob in the quest zone with those names...only found "Lesser Nether Drake" and killed like 20 of them and no quest drops...

Thanks

**Comment by OregonAsari** [comment]
This comment was migrated from bitbucket.
**Original User:** LordUsagi
**Original Date:** 30.05.2015 03:46:46 GMT+0000
**Direct Link:** https://bitbucket.org/oregon/oregoncore/issues/934/#comment-18474603

<hr>

Nether Drake Eggs (184867) should summon Nether Whelps (20021) but currently they are perma-spawned.

Using the discombobulation device on the nether whelps works and is supported.

**Comment by Selphius** [comment]
Fixed in commit: https://github.com/OregonCore/OregonCore/commit/67849950f34bb6ba91cfb3e8b810d99480ef256f
